### ISSUE TITLE
(DB) Timestamp or (firebase.database.ServerValue.TIMESTAMP)

### ISSUE THREAD

**Issue by GV3** [myflashlab/Firebase-ANE#10]
Hi Guys, 

I've found this in the Firebase documentation. And was wondering where the value of this timestamp comes from and if it would make sense to include this in the library.

What do you think? 

**ServerValue**
CONSTANT   STATIC
{TIMESTAMP: non-null Object}

A placeholder value for auto-populating the current timestamp (time since the Unix epoch, in milliseconds) as determined by the Firebase servers.

Example
var sessionsRef = firebase.database().ref('sessions');
var mySessionRef = sessionsRef.push();
mySessionRef.update({ startedAt: firebase.database.ServerValue.TIMESTAMP });

from : https://firebase.google.com/docs/reference/js/firebase.database

**Comment by myflashlab** [comment]
You know, there are a lot of things to be covered yet. Our immediate goal is to complete the overall Firebase SDK with the most useful/common APIs and then we will go deeper into more details step by step. Thanks for pointing that out though. We're on it :)

**Comment by myflashlab** [comment]
This feature is now supported and will be available with the next coming release.
