### ISSUE TITLE
Notification don't fade in top bar (gcm)

### ISSUE THREAD

**Issue by greatpatawee** [myflashlab/Firebase-ANE#100]
Hello why Notification in android don't fade in top bar like Gmail or LINE notification?

it appear on top bar but not fade

pls help me how i set it?

**Comment by myflashlab** [comment]
How FCM notifications are presented are entirely controlled by the Firebase SDK and you do not have access to how they are managed.

There are ways to make this controllable and while we have this in our to-do list, it is not in our immediate priority. If you need more information on this regard, please contact us through MyFlashLabs.com.
