### ISSUE TITLE
Custom Icon for FCM not working

### ISSUE THREAD

**Issue by maheenkhalid** [myflashlab/Firebase-ANE#102]
Hello I am trying to set custom image for the push notification. I have included v4.0.0. But I cannot understand how to add protobuf in the application. Can you kindly help me with that?

**Comment by maheenkhalid** [comment]
Just for the reference, I am using flashDevelop as IDE.

**Comment by maheenkhalid** [comment]
Ok, so I found protobuf.framework file in the iOS dependencies folder. But my custom icon is still not working. I don't understand the reason.

**Comment by myflashlab** [comment]
As mentioned here: http://www.myflashlabs.com/custom-icon-sound-fcm-air-native-extension/
> Firebase for iOS does not support custom icons.

**Comment by maheenkhalid** [comment]
I am trying to make it work with android, not iOS. I am still getting my default image(app icon) as fcm icon.

**Comment by myflashlab** [comment]
well, you were talking about iOS frameworks! anyway, in the above link we have explained how to set the notification icon on Android. Which part is confusing for you?

**Comment by maheenkhalid** [comment]
Nothing is exactly confusing me. But when I try test notifications, my icon is still default. I dont see the custom icon. I have no idea what's wrong.
