### ISSUE TITLE
Using Multiple ANE's 

### ISSUE THREAD

**Issue by fyrcyning** [myflashlab/Firebase-ANE#104]
I am wanting to use the Firebase ANE for my app but also need geofencing.  As there is no ANE by myflashlabs for geofencing I have purchased the distriqt Location ANE.

I can get the ANE's working perfectly seperately but get a conflict with both attempting to the com.google.android.gms.  I get a warning "Warning: packageName com.google.android.gms used by more than one ANE.  Ignoring this entry"

I have tried dropping/alternating the google play services ANE's from each provider but have had no success.

Any help resolving this would be appreciated.

**Comment by myflashlab** [comment]
We have provided a way for other ANE developers to build their ANEs in a way to avoid such conflicts. You can read more about that here https://github.com/myflashlab/common-dependencies-ANE#for-adobe-air-developers

Anyhow, adding geofencing to our [GPS ANE](https://github.com/myflashlab/GPS-ANE/) is in our to-do list. we don't have an exact date on when it will be ready but it will happen in early May.

**Comment by fyrcyning** [comment]
Great, thanks for the info.  I will wait for the GPS ANE update and use that instead of the distriqt ANE.
