### ISSUE TITLE
FCM-AIR-AS3: Id: framework not found FirebaseMessaging

### ISSUE THREAD

**Issue by DezarM** [myflashlab/Firebase-ANE#105]
HI. I find this issues https://github.com/myflashlab/Firebase-ANE/issues/99
but this don't help me.
i add ANE on my IOS project on adobe animate CC

this ane's work's on android.
but on ios i see error - Id: framework not found FirebaseMessaging

my manifest.xml fragment code

  extensions
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.billing</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>

i also read https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md
but HOW i can add framework's on project?

**Comment by DezarM** [comment]
anyone?

**Comment by myflashlab** [comment]
The error message is very clear. You are missing the ```FirebaseMessaging.framework``` framework! As described in the [dependencies](https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md) age, you need to add that to your AIR SDK ```stub``` folder. Just like other frameworks you added for the Core.

**Comment by myflashlab** [comment]
Find the framework in the Firebase SDK zip folder you downloaded https://dl.google.com/firebase/sdk/ios/3_13_0/Firebase-3.13.0.zip

**Comment by DezarM** [comment]
> you need to add that to your AIR SDK stub folder. Just like other frameworks you added for the Core.
i don't know how.
can u help me?

**Comment by myflashlab** [comment]
go to your AIR SDK folder and find the ```stub``` directory: ```YOUR_AIR_SDK\lib\aot\stub``` there you will see iOS frameworks. If you have added the Firebase Core frameworks, you must have already known this location. Now simply copy the ```Messaging > FirebaseMessaging.framework``` file from the [Firebase iOS SDK](https://dl.google.com/firebase/sdk/ios/3_13_0/Firebase-3.13.0.zip) you downloaded and paste it in to the stub folder! Finally make sure your IDE is using that AIR SDK you copied the files to. I don't know any other ways to explain this!

**Comment by DezarM** [comment]
ty.
works
