### ISSUE TITLE
(Auth) AuthEvents.AUTH_STATE_CHANGED takes a long time to fire

### ISSUE THREAD

**Issue by reyco1** [myflashlab/Firebase-ANE#106]
As soon as my app loads and all my Firebase classes are initialized, I add the listener for the "auth state change" in order to know if the current user is logged in

`Auth.listener.addEventListener(AuthEvents.AUTH_STATE_CHANGED, onAuthStateChanged);`

... problem is that both in debug mode and even when packaged as a release candidate, it takes upwards of 20-30 seconds before I get a response to the **onAuthStateChanged** handler. In the mean time, my app looks like its frozen.

Any ideas how to fix this? I'm developing for android.

**Comment by reyco1** [comment]
@myflashlab anyone?

**Comment by myflashlab** [comment]
Why don't you use the ```Auth.isLoggin``` property instead?

```actionscript
if (Auth.isLoggin)
{
	trace("user is logged in");
	trace("displayName = " + 		FirebaseUser.displayName);
	trace("email = " + 				FirebaseUser.email);
	trace("photoUrl = " + 			FirebaseUser.photoUrl);
	trace("providerId = " + 			FirebaseUser.providerId);
	trace("userId = " + 				FirebaseUser.userId);
	trace("isEmailVerified = " +		FirebaseUser.isEmailVerified);
	
	var userInfoOnProviders:UserInfo;
	for (var i:int = 0; i < FirebaseUser.providersData.length; i++) 
	{
		userInfoOnProviders = FirebaseUser.providersData[i];
		trace("-------------")
		trace("providerId = " + 			userInfoOnProviders.providerId);
		trace("displayName = " + 		userInfoOnProviders.displayName);
		trace("email = " + 				userInfoOnProviders.email);
		trace("photoUrl = " + 			userInfoOnProviders.photoUrl);
		trace("userId = " + 				userInfoOnProviders.userId);
		trace("-------------")
	}
}
else
{
	trace("user is NOT logged in");
}
```

**Comment by reyco1** [comment]
Worked like a charm! Only thing is that everywhere I searched it said that `Auth.listener.addEventListener(AuthEvents.AUTH_STATE_CHANGED, onAuthStateChanged);` was the best way to go. Thanks guys!
