### ISSUE TITLE
How to Import GoogleService-Info.plist?

### ISSUE THREAD

**Issue by kyoungminPyon** [myflashlab/Firebase-ANE#108]
Hello
i'm Send FCM Message use FireBase FCM.
Android has been developed without any problems
I can not load the configuration file from IOS
We will contact you.
I put it in the project's bin folder as described in the wiki
I still can not get the configuration file
When I purchased FireBase Core,
I selected google-services.json to create the file firebasecore.ane.
How can I configure GoogleService-Info.plist for IOS to process?

In the image below, the SC_FT_Mobile_UI folder is the project folder in which the ipa file is created.

![img](https://cloud.githubusercontent.com/assets/28042744/25424033/d1106e32-2aa1-11e7-9302-4e2e257ac0d6.png)

**Comment by myflashlab** [comment]
for the ```GoogleService-Info.plist``` just having it available in the bin folder is good enough. When you initialize the Firebase, it returns a Boolean which tells you if it has been able to correctly locate the config .plist file

```actionscript
var isConfigFound:Boolean = Firebase.init();
```

**Comment by kyoungminPyon** [comment]
After creating the bin folder in the project folder
GoogleService-Info.plist and google-services.json
To compile
Var isConfigFound: Boolean = Firebase.init ();
I've run the code above and it shows False.

![img](https://cloud.githubusercontent.com/assets/28042744/25425173/02365536-2aa6-11e7-8d3c-425cb1171c50.png)

위의 이미지에서는 .json 밖에 선택을 못하는데
plist 는 선택을 안하고 bin 폴더에만 넣으면 된다는 이야기인가요?

**Comment by myflashlab** [comment]
if ```isConfigFound``` returns false, it means that the ANE has not been able to locate the .plist file in your bin folder. 

I confirm. For the iOS side, you do NOT need to import the plist file in to the aneMaker software.

**Comment by kyoungminPyon** [comment]
![img2](https://cloud.githubusercontent.com/assets/28042744/25426315/ac610e0e-2aa9-11e7-8a9f-716452fd7108.png)

The above image is the root folder of my project
I created a bin folder there and put GoogleService-Info.plist and google-services.json, but I can not find my settings.
What is the problem?

**Comment by myflashlab** [comment]
I guess, FT_Mobile_UI.swf is your app's main swf file, correct? if so, put the .plist file next to it and see what happens then.

**Comment by kyoungminPyon** [comment]
![img33](https://cloud.githubusercontent.com/assets/28042744/25431439/8a761f0c-2abb-11e7-8d0b-c36c8d8507b3.png)

이야기 한대로 GoogleService-Info.plist 파일을 같은 폴더에 위치하게 하여
컴파일 해 보았지만 여전히 설정파일은 못 찾고 있습니다.
정확히 GoogleService-Info.plist 파일이 어디에 위치해야 하는건가요?
함수로 어느 폴더에서 읽어오는지 알아내는 방법은 없나요?

**Comment by myflashlab** [comment]
when your app starts, trace this command: ```File.applicationDirectory.resolvePath("GoogleService-Info.plist").exists```

does it return true? or false? That's the exact place where the ANE reads the plist file.

**Comment by kyoungminPyon** [comment]
I have to leave now
I will test it tomorrow morning and respond.

**Comment by kyoungminPyon** [comment]
var isChk:Boolean = File.applicationDirectory.resolvePath("GoogleService-Info.plist").exists;
var str:String = File.applicationDirectory.resolvePath("GoogleService-Info.plist").nativePath;
Popup.container.openAlert(str + "/" + isChk.toString());

I tested it as above but the result is false as below.

![img_0007](https://cloud.githubusercontent.com/assets/28042744/25463192/7a87683e-2b2f-11e7-8d64-7950bf160c6a.PNG)

**Comment by myflashlab** [comment]
Ok, that makes sense. you need to place the plist file somewhere in your app where ```applicationDirectory``` can find it. You may read about this location here: http://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118666ade46-7fe4.html

**Comment by kyoungminPyon** [comment]
The GoogleService-Info.plist file was successfully read.
Thank you for your help.
