### ISSUE TITLE
How To IOS 10.3 Background PUSH?

### ISSUE THREAD

**Issue by kyoungminPyon** [myflashlab/Firebase-ANE#109]
I tried to push and test all the device tokens using firebase FCM
When the app is running, the message comes as processed by AS 3.0.
However, there is no push when the app is shutting down.
How do I get a push when an app exits?
I think.
```xml
<Key> UIBackgroundModes </ key>
<Array>
     <String> remote-notification </ string>
</ Array>
```

If you add it to application.xml
I have not got a push in the background.
When the app is floating, the following sources work and push is good.

```actionscript
FCM.listener.addEventListener(FcmEvents.MESSAGE, onMessage);

function onMessage(e:FcmEvents):void
{
	trace(e.msg)
	var payload:Object = FCM.parsePayloadFromString(e.msg);
	
	if (payload)
	{
		for (var name:String in payload)
		{
			trace(name + " = " + payload[name]);
		}
	}
}
```

**Comment by myflashlab** [comment]
When the app is closed and you open the app from the notification menu, you should listen to the ```InvokeEvent``` listener as described here: https://github.com/myflashlab/Firebase-ANE/blob/master/FD/src/MainFcm.as#L99-L112

```actionscript
private function onInvoke(e:InvokeEvent):void
{
	var payload:Object = FCM.parsePayloadFromArguments(e.arguments);
	
	if (payload) // If available, it means that the Invoke listener contains FCM data
	{
		C.log("---------------------------------");
		for (var name:String in payload)
		{
			C.log(name + " = " + payload[name]);
		}
		C.log("---------------------------------");
	}
}

the ```FCM.listener.addEventListener(FcmEvents.MESSAGE, onMessage);``` listener is only good when the app is in foreground.
```

**Comment by myflashlab** [comment]
More over, make sure you have correctly set the **Entitlements** node in your manifest .xml as follow: https://github.com/myflashlab/Firebase-ANE/blob/master/FD/application.xml#L191-L231

**Comment by kyoungminPyon** [comment]
I'm already set InvokeEvent.
but Background Push Not Work.
I set it as follows.

FCM.listener.addEventListener(FcmEvents.TOKEN_REFRESH, onTokenRefresh);
FCM.listener.addEventListener(FcmEvents.MESSAGE, onMessage);
NativeApplication.nativeApplication.addEventListener(InvokeEvent.INVOKE,onInvoke);


public static function onTokenRefresh(e:FcmEvents):void
		{			
			//Popup.container.openAlert("tokenR : " + e.token);
		}
		
		public static function onMessage(e:FcmEvents):void
		{
			
			var payload:Object = FCM.parsePayloadFromString(e.msg);
			
			if (payload)
			{
				for (var name:String in payload)
				{					
					Popup.container.openAlert("name : " + payload[name]);
				}
			}
		}
		
		public static function onInvoke(e:InvokeEvent):void
		{
			var payload:Object = FCM.parsePayloadFromArguments(e.arguments);
			
			if (payload) // If available, it means that the Invoke listener contains FCM data
			{
				for (var name:String in payload)
				{
					trace(name + " : " + payload[name]);
				}
			}
		}

**Comment by kyoungminPyon** [comment]
Entitlements node sees the .mobileprovision file and set it up properly.

**Comment by kyoungminPyon** [comment]
The source below has been resolved.

NativeApplication.nativeApplication.addEventListener(Event.ACTIVATE, handleActivate);
NativeApplication.nativeApplication.addEventListener(Event.DEACTIVATE, handleDeactivate);

public static function handleActivate(e:Event):void
		{
			NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.KEEP_AWAKE;
		}
		
		public static function handleDeactivate(e:Event):void
		{
			NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.NORMAL;
		}

**Comment by myflashlab** [comment]
?! I'm not sure I am understanding this. What do ```Event.ACTIVATE``` and ```Event.DEACTIVATE``` events have to do with FCM messages?

**Comment by kyoungminPyon** [comment]
I think it's a matter of disabling the app.
