### ISSUE TITLE
Unable to hook up FirebaseCore ANE to flashdevelop iOS project

### ISSUE THREAD

**Issue by kerrgrant** [myflashlab/Firebase-ANE#11]
Hi,

Not sure if this is the right place to post this but i'm having trouble hooking up the FirebaseCore ANE to my project Flashdevelop project (iOS target, ultimately for the purposes of analytics). I've included all the specified dependency ANEs as specified in the setup guide, i.e. 

```
<!-- download the dependency ANEs from https://github.com/myflashlab/common-dependencies-ANE -->
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID
                <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>		
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>		
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
		
		<!-- And finally embed the Firebase core ANE -->
		<extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
```

However when I attempt to build and package i'm getting the following error message:

```
ld: framework not found FirebaseAnalytics
ld: framework not found FirebaseAnalytics
Compilation failed while executing : ld64
```

Any ideas what could be causing this? I'm using AIR SDK 22.

Cheers,
Grant.

**Comment by Dextercitox** [comment]
I had that problem with IntelliJ Idea, and it get me a little bit crazy for a couple of hours. In my case the problem was, that IntelliJ, pickup the default iOS SDK path from xCode, instead using the AIR one, no matter if you copy the frameworks in place, it never find them.

The solution was quite simple, erase the path in the project settings, and leave it blank, and it uses AIR to pickup the iOS SDK automatically, this way, it uses the framweworks directory and it works perfectly.

Hope it helps !

**Comment by myflashlab** [comment]
The error message as @Dextercitox pointed out, means that you have not correctly linked to the iOS frameworks. please download them first after reading here. https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md#v110

then [read here](https://github.com/myflashlab/Firebase-ANE/wiki/A.3.-Add-the-SDK) at **Note3** to learn where you should copy the frameworks.

**Comment by kerrgrant** [comment]
Thanks a lot guys it's building and packaging now. My bad, I didn't come across the info on where to put the frameworks!
