### ISSUE TITLE
IOS - Unable to package the application - 'Undefined symbols for architecture arm64'

### ISSUE THREAD

**Issue by syberkitten** [myflashlab/Firebase-ANE#110]
I've been experiencing problems trying to compile the firebaseAuth
for IOS (Android version is working well)

Have also tried using the latest firebase 3.17.0 IOS dependencies
(from here: https://dl.google.com/firebase/sdk/ios/3_17_0/Firebase-3.17.0.zip)

and followed these instructions:
https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md#v110
https://github.com/myflashlab/Firebase-ANE/wiki/A.3.-Add-the-SDK

And note3 here, for the location to drop IOS libraries into:
https://github.com/myflashlab/Firebase-ANE/wiki/A.3.-Add-the-SDK

All this got me further ... but now, I'm failing at this stage:
Failed to package AIR application xxxx.ipa:
         Undefined symbols for architecture arm64:
         "_OBJC_CLASS_$_MyFlashLabsClass", referenced from:
         objc-class-ref in libcom.myflashlab.air.extensions.firebase.auth.a(exFirebaseAuth.o)
         objc-class-ref in libcom.myflashlab.air.extensions.firebase.core.a(exFirebaseCore.o)
         Undefined symbols for architecture armv7:
         "_OBJC_CLASS_$_MyFlashLabsClass", referenced from:
         objc-class-ref in libcom.myflashlab.air.extensions.firebase.auth.a(exFirebaseAuth.o)
         objc-class-ref in libcom.myflashlab.air.extensions.firebase.core.a(exFirebaseCore.o)
         ld: symbol(s) not found for architecture arm64
         ld: symbol(s) not found for architecture armv7
         Compilation failed while executing : ld64

My stats:
- IntelliJ IDEA 14
- Air SDK 25
- FirebaseANE 4.0
- Official Firebase Libraries (Firebase-3.17.0)
- Operating system: Mac OSX 10.11.6 El Capitan
- Xcode 8.2.1

**Comment by myflashlab** [comment]
You need to update your dependency ANEs also. specifically for this error message, you need to update the OverrideAir ane to its latest version.

**Comment by myflashlab** [comment]
table of dependencies are explained in this page: https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md#v400 read them carefully and you'll be fine.

**Comment by syberkitten** [comment]
Great! adding using the latest OverrideAir.ANE v4.0
solved the issue. 👍

**Comment by myflashlab** [comment]
> PS. why not put these dependencies inside the dist given to club members?

It would make things a lot more complicated! The current way, everyone knows where to look for for the latest version but if we distribute them inside the packages, there will be many different versions and will surely confuse everyone. :)
