### ISSUE TITLE
get data from notificatioon on android

### ISSUE THREAD

**Issue by DSigalov** [myflashlab/Firebase-ANE#113]
Can I get data from notifiation when user opens the app by clicking the notification on android?

**Comment by myflashlab** [comment]
Of course you can. make sure you read this post: http://www.myflashlabs.com/send-fcm-messages-server/

**Comment by DSigalov** [comment]
after add "click_action": "MY_INTENT" i get same issue https://github.com/myflashlab/Firebase-ANE/issues/37 with same error stacktrace. 
have You any progress with this problem?

**Comment by myflashlab** [comment]
We have not been able to duplicate the problem 🤔

**Comment by FabioNani** [comment]
The same problem happens to me. I'm using an ASUS Zenfone 3. By including in my JSON the "click-action" tag: "MY_INTENT". the App breaks. When you remove it, it opens normally.

##Manifest##
`
 <android>

  
    <manifestAdditions><![CDATA[
	
	    <manifest android:installLocation="auto">
	
	      <uses-permission android:name="android.permission.INTERNET"/>
	      <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
		  <uses-permission android:name="android.permission.WAKE_LOCK"/>
	
      
  
	      <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
	      <permission android:name="air.mt.teste.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
	      <uses-permission android:name="air.mt.teste.permission.C2D_MESSAGE"/>
	
	      <application android:hardwareAccelerated="true">
		
		

                <service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
                    <intent-filter>
                        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                    </intent-filter>
                </service>
                <service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
                    <intent-filter>
                        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
                    </intent-filter>
                </service>
                <activity 
                    android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
                    android:theme="@style/Theme.Transparent"
                    android:exported="false"
                    android:noHistory="true"
                    android:clearTaskOnLaunch="true"
                    android:hardwareAccelerated="false"
                    android:stateNotNeeded="true">
                    <intent-filter>
                        <action android:name="MY_INTENT" />
                        <category android:name="android.intent.category.DEFAULT" />
                    </intent-filter>
                </activity>
		
        
  
		        <provider android:authorities="air.mt.teste.firebaseinitprovider" android:exported="true" android:initOrder="100" android:name="com.google.firebase.provider.FirebaseInitProvider"/>
        
  
		        <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
		

        
  
		        <receiver android:exported="true" android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                <category android:name="air.mt.teste"/>
            </intent-filter>
        </receiver>
		        <receiver android:exported="true" android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver"/>
				
				  
									

  
		        <activity android:exported="true" android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"/>
	
		
	      </application>
	
      </manifest>]]>
    </manifestAdditions>
  </android>
`
##JSON##
`
{
 "registration_ids" : ["XXX"],
 "notification" : {
 "title" : "A DRI precisa saber...",
 "body" : "Toque aqui e responda agora."
 "sound" : "default",
 "badge": "5",
 "icon" : "myicon",
 "color" : "#0066CC",
 "click-action": "MY_INTENT",
 "priority" : "high"
 }, 
 "data" : {
 "nome" : "Fabio",
 "sobrenome" : "Nani"
 }
}
`

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
