### ISSUE TITLE
 No notification is shown on the mobile

### ISSUE THREAD

**Issue by denisgl777** [myflashlab/Firebase-ANE#114]
I use your FCM ANE
I use your settings I made push notifications in the application on the iphone (iOS 10)
With this notification, the message sent from the firebase console is displayed using the trace
But when the application is minimized the notification does not appear
```
  <key> UIBackgroundModes </ key>
<Array>
<String> remote-notification </ string>
</ Array>
```
added to the descriptor and
And an event listener was added
`NativeApplication.nativeApplication.addEventListener(InvokeEvent.INVOKE, onInvoke);`
In the console firebase certificates added

**Comment by myflashlab** [comment]
Are you sure you have setup the manifest .xml correctly? https://github.com/myflashlab/Firebase-ANE/wiki/G.1-Add-FCM

Are you sure you are not sending data messages? http://www.myflashlabs.com/send-fcm-messages-server/

**Comment by myflashlab** [comment]
Please let us know how you are doing regarding this issue?

**Comment by denisgl777** [comment]
The problem was in the certificates, everything was decided!
