### ISSUE TITLE
Initialise Core

### ISSUE THREAD

**Issue by Jari** [myflashlab/Firebase-ANE#115]
How do I initialise Firebase? Is there a core swc anywhere to add to my project? 
I have generated a firebaseCore.ane bit I cannot find a swc or as3 library for Firebase. 
Below library is missing.

import com.myflashlab.air.extensions.firebase.core.Firebase;

Firebase.init();

**Comment by myflashlab** [comment]
When you add the .ane file, those libraries will be available in your project. You might find these videos helpful: https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by myflashlab** [comment]
Let us know how you are doing regarding this issue?

**Comment by Jari** [comment]
Got it going. Thank you. Just needed to add the ane into the project.
