### ISSUE TITLE
Crashing on Android

### ISSUE THREAD

**Issue by Jari** [myflashlab/Firebase-ANE#117]
App is crashing at start up on Android 6.01. Tried with Air 24 and 25. When adding the following line to The Application Descriptor app crashes on launch. Followed instructions and changed package name but still crashes app on launch. Without the below I cannot seem to get Firebase to initialise.

		
		<provider
			android:name="com.google.firebase.provider.FirebaseInitProvider"
			android:authorities="air.com.doitflash.firebaseCore.firebaseinitprovider"
			android:exported="false"
			android:initOrder="100" />

**Comment by myflashlab** [comment]
You certainly need to change ```air.com.doitflash.firebaseCore``` to your own package name. Besides, make sure you are adding the dependencies correctly https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

If you still can't run, sending us the AndroidStudio logcat would be very helpful.

**Comment by myflashlab** [comment]
Please let us know if this problem is solved?
