### ISSUE TITLE
(Android) App crashes as soon as it opens

### ISSUE THREAD

**Issue by gtechman** [myflashlab/Firebase-ANE#118]
The app crashes as soon as it opens. Below is my manifest. Air SDK is 25.0

Issue seems to be the same as #117 

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<application xmlns="http://ns.adobe.com/air/application/25.0">
    <id>com.futurelinesystems.filterwatch</id>
    <versionNumber>1.0.0</versionNumber>
    <filename>FilterWatch</filename>
    <description></description>
    <!-- To localize the description, use the following format for the description element.
	<description>
		<text xml:lang="en">For use with FilterWatch Ventillation Managment System</text>
		<text xml:lang="fr">À utiliser avec FilterWatch Ventillation Managment System</text>
		<text xml:lang="ja">FilterWatch kanki kanri shisutemu to no heiyō</text>
	</description>
	-->
    <name>FilterWatch</name>
    <!-- To localize the name, use the following format for the name element.
	<name>
		<text xml:lang="en">English App name goes here</text>
		<text xml:lang="fr">French App name goes here</text>
		<text xml:lang="ja">Japanese App name goes here</text>
	</name>
	-->
    <copyright></copyright>
    <initialWindow>
        <content>FW_Maintenance_man.swf</content>
        <systemChrome>standard</systemChrome>
        <transparent>false</transparent>
        <visible>true</visible>
        <fullScreen>false</fullScreen>
        <autoOrients>false</autoOrients>
        <aspectRatio>portrait</aspectRatio>
        <renderMode>cpu</renderMode>
    </initialWindow>
    <customUpdateUI>false</customUpdateUI>
    <allowBrowserInvocation>false</allowBrowserInvocation>
    <icon>
        <image96x96>AppIconsForPublish/FilterWatch%20Eye%202%20Icon.png</image96x96>
    </icon>
    <android>
        <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
			<uses-permission android:name="android.permission.INTERNET" />
			<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
			<uses-permission android:name="android.permission.WAKE_LOCK"/>
	
			<!-- 
				Required by firebase_iid.ane 
				Change "air.com.doitflash.firebaseCore" to your own app package name
			-->
			<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
			<permission android:name="air.com.futurelinesystems.filterwatch.permission.C2D_MESSAGE" android:protectionLevel="signature" />
			<uses-permission android:name="air.com.futurelinesystems.filterwatch.permission.C2D_MESSAGE" />
			<application>
				
				<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				
				<!-- Change "air.com.doitflash.firebaseCore" to your own app package name -->
				<data android:scheme="air.com.futurelinesystems.filterwatch" />
			</intent-filter>
		</activity>
		
		<!-- 
			Required by the firebase_common.ane 
			Change "air.com.futurelinesystems.filterwatch" to your own app package name
		-->
		<provider
			android:name="com.google.firebase.provider.FirebaseInitProvider"
			android:authorities="air.com.futurelinesystems.filterwatch.firebaseinitprovider"
			android:exported="false"
			android:initOrder="100" />
		
		<!-- Required by the googlePlayServices_basement.ane -->
		<meta-data 
			android:name="com.google.android.gms.version" 
			android:value="@integer/google_play_services_version" />
		
		<!-- 
			Required by firebase_iid.ane 
			Change "air.com.futurelinesystems.filterwatch" to your own app package name
		-->
		<receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.com.futurelinesystems.filterwatch" />
            </intent-filter>
        </receiver>
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
		
		<!-- Required by googlePlayServices_base.ane -->
		<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>
				
				<!-- Required by firebase_messaging.ane -->
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
					<intent-filter>
						<action android:name="com.google.firebase.MESSAGING_EVENT"/>
					</intent-filter>
				</service>
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
					<intent-filter>
						<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
					</intent-filter>
				</service>
				<activity 
					android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
					android:theme="@style/Theme.Transparent"
					android:exported="false"
					android:noHistory="true"
					android:clearTaskOnLaunch="true"
					android:hardwareAccelerated="false"
					android:stateNotNeeded="true">
					<intent-filter>
						<action android:name="MY_INTENT" />
						<category android:name="android.intent.category.DEFAULT" />
					</intent-filter>
				</activity>
				
			</application>
		</manifest>]]></manifestAdditions>
    </android>
    <supportedLanguages>en</supportedLanguages>
    <versionLabel>Beta</versionLabel>
    <extensions>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.gcm</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.iid</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
    </extensions>
</application>
```

**Comment by myflashlab** [comment]
The first thing I noticed is that you are missing many dependencies. visit this page: https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md and make sure you are adding all the ANE dependencies.

**Comment by gtechman** [comment]
Thank you for the reply. Adding the dependencies fixed it, however, I am unable to get FCM working. I'm not getting any response from it. I want to use only FCM in the app, do I need anything else other than the core ANE and the FCM ANE? Thanks in advance. I posted the updated manifest just in case I'm missing something else:


`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<application xmlns="http://ns.adobe.com/air/application/25.0">
    <id>com.futurelinesystems.filterwatch</id>
    <versionNumber>1.0.0</versionNumber>
    <filename>FilterWatch</filename>
    <description></description>
    
    <name>FilterWatch</name>
    
    <copyright></copyright>
    <initialWindow>
        <content>FW_Maintenance_man.swf</content>
        <systemChrome>standard</systemChrome>
        <transparent>false</transparent>
        <visible>true</visible>
        <fullScreen>false</fullScreen>
        <autoOrients>false</autoOrients>
        <aspectRatio>portrait</aspectRatio>
        <renderMode>cpu</renderMode>
    </initialWindow>
    <customUpdateUI>false</customUpdateUI>
    <allowBrowserInvocation>false</allowBrowserInvocation>
    <icon>
        <image96x96>AppIconsForPublish/FilterWatch%20Eye%202%20Icon.png</image96x96>
    </icon>
    <android>
        <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
			<uses-permission android:name="android.permission.INTERNET" />
			<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
			<uses-permission android:name="android.permission.WAKE_LOCK"/>
	
			
			<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
			<permission android:name="air.com.futurelinesystems.filterwatch.permission.C2D_MESSAGE" android:protectionLevel="signature" />
			<uses-permission android:name="air.com.futurelinesystems.filterwatch.permission.C2D_MESSAGE" />
			<application>
				
				<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				
				
				<data android:scheme="air.com.futurelinesystems.filterwatch" />
			</intent-filter>
		</activity>
		
		
		<provider
			android:name="com.google.firebase.provider.FirebaseInitProvider"
			android:authorities="air.com.futurelinesystems.filterwatch.firebaseinitprovider"
			android:exported="false"
			android:initOrder="100" />
		
		
		<meta-data 
			android:name="com.google.android.gms.version" 
			android:value="@integer/google_play_services_version" />
		
		
		<receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.com.futurelinesystems.filterwatch" />
            </intent-filter>
        </receiver>
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
		
		
		<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>
				
				
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
					<intent-filter>
						<action android:name="com.google.firebase.MESSAGING_EVENT"/>
					</intent-filter>
				</service>
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
					<intent-filter>
						<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
					</intent-filter>
				</service>
				<activity 
					android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
					android:theme="@style/Theme.Transparent"
					android:exported="false"
					android:noHistory="true"
					android:clearTaskOnLaunch="true"
					android:hardwareAccelerated="false"
					android:stateNotNeeded="true">
					<intent-filter>
						<action android:name="MY_INTENT" />
						<category android:name="android.intent.category.DEFAULT" />
					</intent-filter>
				</activity>
				
			</application>
		</manifest>]]></manifestAdditions>
    </android>
    <supportedLanguages>en</supportedLanguages>
    <versionLabel>Beta</versionLabel>
    <extensions>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.iid</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    </extensions>
</application>`

**Comment by myflashlab** [comment]
Yes, the dependencies are still missing :) I really need to suggest that you take your time and read the documentations more carefully. Just a hint: you are still missing ```firebase_messaging.ane```. 

Read the Wiki/depenendcies page and try to do everything according to the wiki and you'll be fine.

**Comment by gtechman** [comment]
I went back though methodically and made sure I followed everything correctly. I believe I have all the required dependencies now. Everything appears to be working correctly except I am unable to obtain a registration token. The core initialization returns true and google availability is successful but it never retrieves a token.


`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<application xmlns="http://ns.adobe.com/air/application/25.0">
    <id>com.futurelinesystems.filterwatch</id>
    <versionNumber>1.0.0</versionNumber>
    <filename>FilterWatch</filename>
    <description></description>
    
    <name>FilterWatch</name>
    
    <copyright></copyright>
    <initialWindow>
        <content>FW_Maintenance_man.swf</content>
        <systemChrome>standard</systemChrome>
        <transparent>false</transparent>
        <visible>true</visible>
        <fullScreen>false</fullScreen>
        <autoOrients>false</autoOrients>
        <aspectRatio>portrait</aspectRatio>
        <renderMode>cpu</renderMode>
    </initialWindow>
    <customUpdateUI>false</customUpdateUI>
    <allowBrowserInvocation>false</allowBrowserInvocation>
    <icon>
        <image96x96>AppIconsForPublish/FilterWatch%20Eye%202%20Icon.png</image96x96>
    </icon>
    <android>
        <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
			<uses-permission android:name="android.permission.INTERNET" />
			<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
			<uses-permission android:name="android.permission.WAKE_LOCK"/>
	
			
			<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
			<permission android:name="air.com.futurelinesystems.filterwatch.permission.C2D_MESSAGE" android:protectionLevel="signature" />
			<uses-permission android:name="air.com.futurelinesystems.filterwatch.permission.C2D_MESSAGE" />
			<application>
				
				<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				
				
				<data android:scheme="air.com.futurelinesystems.filterwatch" />
			</intent-filter>
		</activity>
		
		
		<provider
			android:name="com.google.firebase.provider.FirebaseInitProvider"
			android:authorities="air.com.futurelinesystems.filterwatch.firebaseinitprovider"
			android:exported="false"
			android:initOrder="100" />
		
		
		<meta-data 
			android:name="com.google.android.gms.version" 
			android:value="@integer/google_play_services_version" />
		
		
		<receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.com.futurelinesystems.filterwatch" />
            </intent-filter>
        </receiver>
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
		
		
		<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>
				
				
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
					<intent-filter>
						<action android:name="com.google.firebase.MESSAGING_EVENT"/>
					</intent-filter>
				</service>
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
					<intent-filter>
						<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
					</intent-filter>
				</service>
				<activity 
					android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
					android:theme="@style/Theme.Transparent"
					android:exported="false"
					android:noHistory="true"
					android:clearTaskOnLaunch="true"
					android:hardwareAccelerated="false"
					android:stateNotNeeded="true">
					<intent-filter>
						<action android:name="MY_INTENT" />
						<category android:name="android.intent.category.DEFAULT" />
					</intent-filter>
				</activity>
				
			</application>
		</manifest>]]></manifestAdditions>
    </android>
    <supportedLanguages>en</supportedLanguages>
    <versionLabel>Beta</versionLabel>
    <extensions>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.iid</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
    </extensions>
</application>`

**Comment by myflashlab** [comment]
Well, the manifest file now seems to be OK and you should be receiving the token like [this](https://github.com/myflashlab/Firebase-ANE/blob/master/FD/src/MainFcm.as#L241-L243)

Please watch the AndroidStudio logcat console when you are calling 
```actionscript
FCM.init();
FCM.listener.addEventListener(FcmEvents.TOKEN_REFRESH, onTokenRefresh);
FCM.listener.addEventListener(FcmEvents.MESSAGE, onMessage);
```
and see if any error message is generated?

Also try to subscribe to a topic like below and still while watching the logcat.
```actionscript
FCM.subscribeToTopic("news");
```
then, use the firebase console or [this guid](http://www.myflashlabs.com/send-fcm-messages-server/) to send a notification and see if Google returns a successful fcm operation or not.

You need to find an error message or something so we can understand why the token is not returned.

**Comment by gtechman** [comment]
I was missing FCM.init. I am now able to receive notifications. However I am receiving an empty object on the InvokeEvent. All the data shows up in the banner normally but when I tap the notification it is not able to parse the object in the app. The raw data coming in on the InvokeEvent is this:

air.com.futurelinesystems.filterwatch://%7B%22google.sent_time%22%3A1497034405325%2C%22from%22%3A%22527870697798%22%2C%22google.message_id%22%3A%220%3A1497034405343577%253e0d28a53e0d28a5%22%2C%22collapse_key%22%3A%22air.com.futurelinesystems.filterwatch%22%7D,android.intent.action.VIEW

Thanks for all your help.

**Comment by myflashlab** [comment]
Happy to hear that :) Alright, you must have missed reading this post: http://www.myflashlabs.com/send-fcm-messages-server/ it will help you understand FCM messages/usage in simple words

**Comment by gtechman** [comment]
Hi, I am sending mixed messages to the app. I have a notification and data message coming through. I have tried to send just a notification message and the same thing happens.

**Comment by myflashlab** [comment]
A notification message is not designed to include data in it. If you need to send data to be used inside the app, you need to use mix messages or data messages.

**Comment by gtechman** [comment]
Sorry, I meant I was sending mixed messages. This is the PHP array being passed to Firecloud:

`$vars = array('registration_ids' => $DeviceID, 'notification' => array("title" => "WARNING", "text" => "Drillpress Vent OVER-TEMP", "sound" => "FW_Alarm1.mp3", "badge" => "3", "color" => "#ff2d2d", "click_action" => "MY_INTENT"), 'data' => array("type" => "WARNING", "date" => "44", "values" => "var=test"), "priority" => "high");`

**Comment by myflashlab** [comment]
Well, your PHP code seems fine. you have the ```MY_INTENT``` activity in your manifest and you are targeting it correctly from PHP. If the raw data in ```Invoke``` listener is not including the data object, then the ANE can't parse it obviously. I can't think of a suggestion.

Have you tried to see what Android-studio logcat says when an FCM arrives? or when you open the notification?

Or, are you experiencing a similar thing when using **Advanced REST Client software** as described in the tutorial linked above?

And does the very same PHP code send the data correctly on the iOS side?
