### ISSUE TITLE
FCM -Unregister

### ISSUE THREAD

**Issue by aseemgarg321** [myflashlab/Firebase-ANE#120]
Hi, 

If we need to give functionality of "Logout" for the users. Guess, we need an unregistered function, so that new user who logs in can get new token and not gets linked to same token. 

👍 Requesting you to add following feature for same  - 

https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.html#deleteInstanceId

Thanks, 
Aseem

**Comment by myflashlab** [comment]
That's a very good point. We will surely add that. Thanks.

**Comment by myflashlab** [comment]
V5.1.0 is now released and this version includes everything related to FirebaseInstanceId. You can see how you can delete and regenerate the iid in this sample: https://github.com/myflashlab/Firebase-ANE/blob/master/AIR/src/Main.as#L193-L243

**Comment by myflashlab** [comment]
more infor also on the wiki: https://github.com/myflashlab/Firebase-ANE/wiki/A.6.-Managing-Firebase-iid
