### ISSUE TITLE
 Error importing Firebase Core

### ISSUE THREAD

**Issue by heliomarch** [myflashlab/Firebase-ANE#122]
I am now ready to activate FCM but before I already have an error in importing FirebaseCore. When inserting in the Manifesto the lines:
```
<! -
Required by the firebase_common.ane
Change "air.com.doitflash.firebaseCore" to your own app package name->
<Provider Android: name = "com.google.fire android:authorities="air.osadmin.firebaseinitprovider" 			android:exported="false" android:initOrder="100" />
```

The application closes. If I throw these lines it opens however if I call the function Faribase.init () the app closes.

I'm using Animate CC 2017.

I found in the documentation a video how to import ANES in Flash CC, however I did not find an example of .fla

**Comment by myflashlab** [comment]
Please post your complete manifest... it seems like your are missing some dependencies. make sure you have read this document https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

**Comment by heliomarch** [comment]
I was able to move forward. My problem now is that I can not get the token. It always comes empty.
Remember that taking that part that I mentioned above works by putting that tag "<Android Provider: name =" com.google.fire android: authorities = "air.osadmin.firebaseinitprovider" android: exported = "false" android: initOrder = "100 "/>" The application does not open. The message informs you that the App has stopped.
Below is the manifesto. Grateful.

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
  <id>osadmin</id>
  <versionNumber>1.1.7</versionNumber>
  <versionLabel>1.1.7</versionLabel>
  <filename>OS Admin</filename>
  <description/>
  <name>OS Admin</name>
  <copyright/>
  <initialWindow>
    <content>osadmin.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  
  
  <android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
<permission android:name="air.osadmin.permission.C2D_MESSAGE" android:protectionLevel="signature" />
<uses-permission android:name="air.osadmin.permission.C2D_MESSAGE" />

 <application>
	     <activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				<data android:scheme="air.osadmin" />
			</intent-filter>
		</activity>
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		
				 
			 <receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.osadmin" />
            </intent-filter>
        </receiver>
			 
			 <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
			 
			 <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>
				  
				  
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT"/>
			</intent-filter>
		</service>
		<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
			<intent-filter>
				<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
			</intent-filter>
		</service>
		
		<activity 
			android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
			android:theme="@style/Theme.Transparent"
			android:exported="false"
			android:noHistory="true"
			android:clearTaskOnLaunch="true"
			android:hardwareAccelerated="false"
			android:stateNotNeeded="true">
			<intent-filter>
			<action android:name="MY_INTENT" />
			<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
				  
				  
 </application>
			 
</manifest>]]></manifestAdditions>
  </android>
  <supportedLanguages>pt</supportedLanguages>  
     
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.inspector</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
	<extensionID>com.turbidwater.geocapabilities</extensionID>
    <extensionID>com.doitflash.air.extensions.toast</extensionID>
  </extensions>
</application>

**Comment by heliomarch** [comment]
`<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
  <id>osadmin</id>
  <versionNumber>1.1.7</versionNumber>
  <versionLabel>1.1.7</versionLabel>
  <filename>OS Admin</filename>
  <description/>
  <name>OS Admin</name>
  <copyright/>
  <initialWindow>
    <content>osadmin.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  
  
  <android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
<permission android:name="air.osadmin.permission.C2D_MESSAGE" android:protectionLevel="signature" />
<uses-permission android:name="air.osadmin.permission.C2D_MESSAGE" />

 <application>
	     <activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				<data android:scheme="air.osadmin" />
			</intent-filter>
		</activity>
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		
				 
			 <receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.osadmin" />
            </intent-filter>
        </receiver>
			 
			 <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
			 
			 <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>
				  
				  
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT"/>
			</intent-filter>
		</service>
		<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
			<intent-filter>
				<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
			</intent-filter>
		</service>
		
		<activity 
			android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
			android:theme="@style/Theme.Transparent"
			android:exported="false"
			android:noHistory="true"
			android:clearTaskOnLaunch="true"
			android:hardwareAccelerated="false"
			android:stateNotNeeded="true">
			<intent-filter>
			<action android:name="MY_INTENT" />
			<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
				  
				  
 </application>
			 
</manifest>]]></manifestAdditions>
  </android>
  <supportedLanguages>pt</supportedLanguages>  
     
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.inspector</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
	<extensionID>com.turbidwater.geocapabilities</extensionID>
    <extensionID>com.doitflash.air.extensions.toast</extensionID>
  </extensions>
</application>`

**Comment by heliomarch** [comment]
`<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
  <id>osadmin</id>
  <versionNumber>1.1.7</versionNumber>
  <versionLabel>1.1.7</versionLabel>
  <filename>OS Admin</filename>
  <description/>
  <name>OS Admin</name>
  <copyright/>
  <initialWindow>
    <content>osadmin.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
 <application>
	     <activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				<data android:scheme="air.osadmin" />
			</intent-filter>
		</activity>
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />`
<receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.osadmin" />
            </intent-filter>
        </receiver>
			 
			 <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
			 
			 <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>				  
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT"/>
			</intent-filter>
		</service>
		<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
			<intent-filter>
				<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
			</intent-filter>
		</service>
		
		<activity 
			android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
			android:theme="@style/Theme.Transparent"
			android:exported="false"
			android:noHistory="true"
			android:clearTaskOnLaunch="true"
			android:hardwareAccelerated="false"
			android:stateNotNeeded="true">
			<intent-filter>
			<action android:name="MY_INTENT" />
			<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
` </application>
			 
</manifest>]]></manifestAdditions>
  </android>
  <supportedLanguages>pt</supportedLanguages>  
     
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.inspector</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
	<extensionID>com.turbidwater.geocapabilities</extensionID>
    <extensionID>com.doitflash.air.extensions.toast</extensionID>
  </extensions>
</application>`

**Comment by heliomarch** [comment]
![image](https://user-images.githubusercontent.com/29484131/27300489-43e5bf14-5506-11e7-9de2-b6ade67f309b.png)
