### ISSUE TITLE
I can not get the token - FCM

### ISSUE THREAD

**Issue by heliomarch** [myflashlab/Firebase-ANE#123]
I was able to move forward. My problem now is that I can not get the token. It always comes empty.
Remember that this site I mentioned above does not work by putting this tag "<Android provider: name =" com.google.fire android: authorities = "air.osadmin.firebaseinitprovider" android: exported = "false" android: initOrder = "The application does not open." The message informs that the application has stopped, to get to where I came from, it was necessary to remove this part of Manifest, the onTokenRefresh function returns nothing as well.
I put the image because when I put the code is somewhat illegible.

Below is the manifesto. Grateful.
![image](https://user-images.githubusercontent.com/29484131/27300796-57592742-5507-11e7-91f2-9fd80b1d3cb9.png)
![image](https://user-images.githubusercontent.com/29484131/27300801-60089ba2-5507-11e7-85ee-02e1d3919adf.png)

![image](https://user-images.githubusercontent.com/29484131/27301515-d21980a6-5509-11e7-8503-503c84e438b9.png)

**Comment by myflashlab** [comment]
the ```provider``` tag must be present in your manifest. you may want to watch these videos https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

and to share your code, please use the [markdown](https://guides.github.com/features/mastering-markdown/) as watching the screenshots like that is too tiny to read!

**Comment by heliomarch** [comment]
Good Morning. I was interested in downloading ANE Required by the firebase_common.ane. This one was in trouble and then this tag worked. The manifest does not see an error but has not yet received TOKEN. What can it be? I recreated the project in firebase google. I do not know what it can be. Follows the manifest now complete and the APP opening normally without tying the token

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
  <id>osadmin</id>
  <versionNumber>1.1.7</versionNumber>
  <versionLabel>1.1.7</versionLabel>
  <filename>OS Admin</filename>
  <description/>
  <name>OS Admin</name>
  <copyright/>
  <initialWindow>
    <content>osadmin.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon>
    <image36x36>AppIconsForPublish/base1.png</image36x36>
    <image48x48>AppIconsForPublish/base2.png</image48x48>
    <image72x72>AppIconsForPublish/base3.png</image72x72>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  
  
  <android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>

<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
<permission android:name="air.osadmin.permission.C2D_MESSAGE" android:protectionLevel="signature" />
<uses-permission android:name="air.osadmin.permission.C2D_MESSAGE" />

 <application>
	     <activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				<data android:scheme="air.osadmin" />
			</intent-filter>
		</activity>

         <provider
            android:name="com.google.firebase.provider.FirebaseInitProvider"
            android:authorities="air.osadmin.firebaseinitprovider"
            android:exported="false"
            android:initOrder="100" />
	
         <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		
		 <receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.osadmin" />
            </intent-filter>
        </receiver>
		
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
			
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
	        <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
		
		 <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
         android:theme="@android:style/Theme.Translucent.NoTitleBar"
         android:exported="false"/>
						  
				  
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT"/>
			</intent-filter>
		</service>
		
		
		<activity 
			android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
			android:theme="@style/Theme.Transparent"
			android:exported="false"
			android:noHistory="true"
			android:clearTaskOnLaunch="true"
			android:hardwareAccelerated="false"
			android:stateNotNeeded="true">
			<intent-filter>
			<action android:name="MY_INTENT" />
			<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
				  
				  
 </application>
			 
</manifest>]]></manifestAdditions>
  </android>
  <supportedLanguages>pt</supportedLanguages>   
  
  
  
  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
    <extensionID>com.turbidwater.geocapabilities</extensionID>
    <extensionID>com.doitflash.air.extensions.toast</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.inspector</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
  </extensions>
</application>

**Comment by myflashlab** [comment]
you are missing the following service!

```xml
<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
	<intent-filter>
		<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
	</intent-filter>
</service>
```

Please take your time and read the documentations more carefully. I know, setting up Firebase settings in manifest is a tedious work but these settings must be placed and there's no other way around it. just take your time and make sure you are adding everything correctly. Let us know how you go.

**Comment by heliomarch** [comment]
Good afternoon.
I put this service that was missing but the Token has not come yet. What could it be?
I'll put the Manifesto as it is at this moment below ...

'<'?xml version="1.0" encoding="utf-8" standalone="no" ?>
'<'application xmlns="http://ns.adobe.com/air/application/26.0">
 '<'id>osadmin</id>
  '<'versionNumber>1.1.7</versionNumber>
  '<'versionLabel>1.1.7</versionLabel>
  '<'filename>OS Admin</filename>
  '<'description/>
  '<'name>OS Admin</name>
  '<'copyright/>
  '<'initialWindow>
    '<'content>osadmin.swf</content>
    '<'systemChrome>standard</systemChrome>
    '<'transparent>false</transparent>
    '<'visible>true</visible>
    '<'fullScreen>true</fullScreen>
    '<'aspectRatio>landscape</aspectRatio>
    '<'renderMode>cpu</renderMode>
    '<'autoOrients>false</autoOrients></initialWindow>
  '<'icon>
    '<'image36x36>AppIconsForPublish/base1.png</image36x36>
    '<'image48x48>AppIconsForPublish/base2.png</image48x48>
    '<'image72x72>AppIconsForPublish/base3.png</image72x72>
  '<'/icon>
  '<'customUpdateUI>false</customUpdateUI>
  '<'allowBrowserInvocation>false</allowBrowserInvocation>
  
 '<'android'>'
    '<'manifestAdditions>'<![CDATA[<manifest android:installLocation="auto"'>'
      '<'uses-permission android:name="android.permission.INTERNET"/'>'
      '<''uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/'>'
      '<'uses-permission android:name="android.permission.READ_PHONE_STATE"/'>'
      '<'uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/'>'
      '<'uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/'>'
      '<'uses-permission android:name="android.permission.DISABLE_KEYGUARD"/'>'
      '<'uses-permission android:name="android.permission.WAKE_LOCK"/'>'
      '<'uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/'>'
      '<'uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/'>'
'<'uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" /'>'
'<'permission android:name="air.osadmin.permission.C2D_MESSAGE" android:protectionLevel="signature" /'>'
'<'uses-permission android:name="air.osadmin.permission.C2D_MESSAGE" /'>'

'<'provider
            android:name="com.google.firebase.provider.FirebaseInitProvider"
            android:authorities="air.osadmin.firebaseinitprovider"
            android:exported="false"
            android:initOrder="100" />


'<'application>
	     '<'activity>
			'<'intent-filter>
				'<'action android:name="android.intent.action.MAIN" />
				'<'category android:name="android.intent.category.LAUNCHER" />
			'<'/intent-filter>
			'<'intent-filter>
				'<'action android:name="android.intent.action.VIEW" />
				'<'category android:name="android.intent.category.BROWSABLE" />
				'<'category android:name="android.intent.category.DEFAULT" />
				'<'data android:scheme="air.osadmin" />
			'<'/intent-filter>
		'</activity>   
	
         <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		
		<receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.osadmin" />
            </intent-filter>
        </receiver>
		
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
			
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
	        <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
		
		<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT"/>
			</intent-filter>
		</service>
		
		 <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
         android:theme="@android:style/Theme.Translucent.NoTitleBar"
         android:exported="false"/>
		
		<activity 
			android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
			android:theme="@style/Theme.Transparent"
			android:exported="false"
			android:noHistory="true"
			android:clearTaskOnLaunch="true"
			android:hardwareAccelerated="false"
			android:stateNotNeeded="true">
			<intent-filter>
			<action android:name="MY_INTENT" />
			<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
				  
				  
' <'/application>
  ' <'/manifest>]]></manifestAddition'>'
 '<'/android>
  '<'supportedLanguages>pt</supportedLanguages'> '   
  '<'extensions'>'
    '<'extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID'>'
    '<'extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID'>'
    '<'extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID'>'
    '<'extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID'>'
    '<'extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID'>'
    '<'extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID'>'
    '<'extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID'>'
    '<'extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID'>'
    '<'extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID'>'
   '<'extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>'
    '<'extensionID>com.myflashlab.air.extensions.inspector</extensionID'>'
    '<'extensionID>com.doitflash.air.extensions.toast</extensionID'>'
    '<'extensionID>com.turbidwater.geocapabilities</extensionID'>'
    '<'extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID'>'
 '<'/extensions'>'
'<'/application'>'

**Comment by heliomarch** [comment]
End as you recommended. By doing so the application closes as soon as it is started.
Great, I learned how to do the marking.
I do not know what it can be. Can it be on Google?
Follows the current manifesto

```xml  
  <android>
     <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
      <uses-permission android:name="android.permission.INTERNET"/>
      <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
      <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
      <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
      <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
      <uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
      <uses-permission android:name="android.permission.WAKE_LOCK"/>
      <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
      <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
<permission android:name="air.osadmin.permission.C2D_MESSAGE" android:protectionLevel="signature" />
<uses-permission android:name="air.osadmin.permission.C2D_MESSAGE" />


 <application>
		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				<data android:scheme="air.osadmin" />
			</intent-filter>
		</activity>   
		
		 <provider
            android:name="com.google.firebase.provider.FirebaseInitProvider"
            android:authorities="air.osadmin.firebaseinitprovider"
            android:exported="false"
            android:initOrder="100" />
	
         <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		
		<receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.osadmin" />
            </intent-filter>
        </receiver>
		
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
			
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
	        <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
	<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
	<intent-filter>
		<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
	</intent-filter>
</service>
		<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT"/>
			</intent-filter>
		</service>
		
		 <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
         android:theme="@android:style/Theme.Translucent.NoTitleBar"
         android:exported="false"/>
		
		<activity 
			android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
			android:theme="@style/Theme.Transparent"
			android:exported="false"
			android:noHistory="true"
			android:clearTaskOnLaunch="true"
			android:hardwareAccelerated="false"
			android:stateNotNeeded="true">
			<intent-filter>
			<action android:name="MY_INTENT" />
			<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
				  
```

**Comment by myflashlab** [comment]
this part of the manifest seems fine now but you still have the problem... We are hoping that you can provide us some more information so we can help you fix the problem.

You say the app closes when it launches, will you send us the error logs? Run logcat in AndroidStudio while your device is connected to your PC. Send us those logs and they will tell what is wrong.

**Comment by heliomarch** [comment]
Please, is there a tutorial for this? I'll try but I thought if there is any tutorial to pass me by.

**Comment by heliomarch** [comment]
good afternoon. Would be this data. They were collected by the form you requested.

06-27 13:23:06.411: E/jdwp(13380): Failed sending reply to debugger: Broken pipe
06-27 13:23:06.521: E/AndroidRuntime(13380): FATAL EXCEPTION: main
06-27 13:23:06.521: E/AndroidRuntime(13380): java.lang.NoSuchMethodError: android.support.v4.content.ContextCompat.isDeviceProtectedStorage
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at com.google.firebase.FirebaseApp.zza(Unknown Source)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1058)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4660)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4290)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4232)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at android.app.ActivityThread.access$1400(ActivityThread.java:140)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at android.os.Looper.loop(Looper.java:137)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at android.app.ActivityThread.main(ActivityThread.java:4921)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at java.lang.reflect.Method.invoke(Method.java:511)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
06-27 13:23:06.521: E/AndroidRuntime(13380): 	at dalvik.system.NativeStart.main(Native Method)
06-27 13:23:06.546: E/android.os.Debug(2229): !@Dumpstate > dumpstate -k -t -z -d -o /data/log/dumpstate_app_error
06-27 13:23:15.566: E/Launcher(2998): Error finding setting, default accessibility to not found: accessibility_enabled
06-27 13:23:22.246: E/Watchdog(2229): !@Sync 395
06-27 13:23:52.251: E/Watchdog(2229): !@Sync 396

**Comment by myflashlab** [comment]
Did some search on the web and while reading similar issues, it seems like this could happen sometimes because of mismatched Firebase dependencies. Are you sure you are using all V4.0.0 and ane dependencies [V10.2.0](https://github.com/myflashlab/common-dependencies-ANE)?

**Comment by heliomarch** [comment]
Good Morning. Everything worked out now. All working. Thanks and I noticed in the documentation that still does not support res / raw. Let's wait for updates. Thank you for your attention.
