### ISSUE TITLE
is there any example on how implement the FCM ane in Flash CC (Animate CC)?

### ISSUE THREAD

**Issue by alvarengakenneth** [myflashlab/Firebase-ANE#128]
Hi, I need help, is there any example on how implement the FCM ane in Flash CC (Animate CC)?, I have the core Ane too.

Please help me, I tried a lot with all the guides but still not working :(

**Comment by myflashlab** [comment]
Adding the ANE on any of the IDEs is just similar to each other. The only cache that sometimes devs miss are:

1. run on a real device not the simulator.
2. keep your AIR SDK updated.
3. make sure your manifest is correctly setup and your project can read the ANEs

If you have a specific question, do ask, we're here to help.

**Comment by alvarengakenneth** [comment]
Still Not Working, here my manifest:

`<?xml version="1.0" encoding="utf-8" standalone="no" ?>


		
		
<application xmlns="http://ns.adobe.com/air/application/26.0">
  <id>com.lnfphn.LNFPHN</id>
  <versionNumber>1.3</versionNumber>
  <versionLabel></versionLabel>
  <filename>LNFPHN</filename>
  <description/>
  <name>LNFPHN</name>
  <copyright/>
  <initialWindow>
    <content>lnfp.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>false</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon/>
   <icon>
    <image36x36>nuevos%20icos/android/mipmap-ldpi/ic_launcher.png</image36x36>
    <image48x48>nuevos%20icos/android/mipmap-mdpi/ic_launcher.png</image48x48>
    <image72x72>nuevos%20icos/android/mipmap-hdpi/ic_launcher.png</image72x72>
    <image96x96>nuevos%20icos/android/mipmap-xhdpi/ic_launcher.png</image96x96>
  </icon>

 <android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
 
<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
	
	
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<permission android:name="air.com.lnfphn.LNFPHN.permission.C2D_MESSAGE" android:protectionLevel="signature" />
	<uses-permission android:name="air.com.lnfphn.LNFPHN.permission.C2D_MESSAGE" />
	
	
	
	
	<application>
		
		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				
				
				<data android:scheme="air.com.lnfphn.LNFPHN.firebaseCore" />
			</intent-filter>
		</activity>
		
		
		<provider
			android:name="com.google.firebase.provider.FirebaseInitProvider"
			android:authorities="air.com.lnfphn.LNFPHN.firebaseCore.firebaseinitprovider"
			android:exported="false"
			android:initOrder="100" />
		
		
		<meta-data 
			android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		
		
		<receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.com.lnfphn.LNFPHN.firebaseCore" />
            </intent-filter>
        </receiver>
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
		
		
		<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>
		
	
	
	
	
  	</application>	
	 </manifest>]]></manifestAdditions>
</android>





  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  
  
  
  	
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
					<intent-filter>
						<action android:name="com.google.firebase.MESSAGING_EVENT"/>
					</intent-filter>
				</service>
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
					<intent-filter>
						<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
					</intent-filter>
				</service>
				<activity 
					android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
					android:theme="@style/Theme.Transparent"
					android:exported="false"
					android:noHistory="true"
					android:clearTaskOnLaunch="true"
					android:hardwareAccelerated="false"
					android:stateNotNeeded="true">
					<intent-filter>
						<action android:name="MY_INTENT" />
						<category android:name="android.intent.category.DEFAULT" />
					</intent-filter>
				</activity>
    
	

	
	
	  <supportedLanguages>es</supportedLanguages>
  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>

	
	
	 
	
	<extensionID>com.myflashlab.air.extensions.inspector</extensionID>
	
	
	
	
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID> 
	
	
	
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
	
	
	
  </extensions>
  
 
  
</application>


`
  
the image of the error:
![error-fcm](https://user-images.githubusercontent.com/6536168/28248950-7d3b1b7e-6a0a-11e7-9de5-86ed878d6150.png)

**Comment by alvarengakenneth** [comment]
I buy the core ane and the FCM ane, download and create the core for this app, import the .json from google, but still doesn't work.

**Comment by myflashlab** [comment]
The error message is very clear. Your manifest is wrong and cannot be parsed. I was wondering why you didn't try to copy/paste your manifest code here. it could have been a lot easier than taking screenshots. Please read [markdown](https://guides.github.com/features/mastering-markdown/) to know how to use it.

Anyway, back to the problem, I tried to look through your screenshots and I can see that you have closed the ```android``` tag but then after that, you have added an activity and services! This is not correct. try to take the [sample manifest .xml file](https://github.com/myflashlab/Firebase-ANE/blob/master/FD/application.xml) as your reference. no matter what IDE you use, the demo manifest is your guide.

**Comment by alvarengakenneth** [comment]
Thank, now copy, paste and edit the manifest, 

now i having this error:

![nproblem](https://user-images.githubusercontent.com/6536168/28251611-705522ae-6a3e-11e7-96b2-eb029b751d6a.png)

**Comment by alvarengakenneth** [comment]
I feel a little discouraged :(    you buy a solution to make it easy to solve a problem, but doing all the steps, it still does not work, it feels the same as a free solutions where you have to try a lot to make it work.

If you have any examples of how to implement the FCM in a .fla please share it.

I till have the same error, and dont know how to fix it.

**Comment by myflashlab** [comment]
The sample files in Github should be enough to get you going as many devs are already using it. Maybe a sample project in CC could be better for users whom are less familiar with embedding ANEs. So, I will prepare a sample FLA project for you. hold on while I do that. FYI: We are releasing V5.0.0 of Firebase collection in a couple of days and when we release that, we will also include FLA samples. check back soon. Thanks.

**Comment by alvarengakenneth** [comment]
Hi, I guess you may have some problems creating the .fla example  using FCM and CORE, I hope you can fix it, please let me know when you have it, I really need it soon,  help me please.

**Comment by myflashlab** [comment]
Yes! the problem is that we do not use FLAs! Anyway, I created a sample FLA project including Android and iOS setups. This is a sample just like the current intelliJ and FlashDevelop samples. You should be able to feel at home now.
If you feel like you need more help, you may considring buying a live support chat over Skype/Teamviewer.

**Comment by alvarengakenneth** [comment]
I will try with that!! 

Thanks a lot!!!!

**Comment by alvarengakenneth** [comment]
Hello, look very near to finally work,

could you tell me how to fix this error please:

![error2](https://user-images.githubusercontent.com/6536168/28500803-50226660-6f8c-11e7-96dc-1b6da371a26e.png)


Thanks!

**Comment by myflashlab** [comment]
1. use the latest AIR SDK, AIR 26 for example.
2. Use captive not the shared mode when compiling your project.
3. again, make sure you have set all the manifest details correctly.

**Comment by alvarengakenneth** [comment]
1,2,3 are ok,

everything is okay, but does not work.  are you shure that this ANEs works on flash CC or Animate?

**Comment by myflashlab** [comment]
Of course we are sure! 😱 some our clients are using AnimateCC and they are fine. anyway, please try these solutions:

1. These videos might help you https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O
2. if you still have a problem, send us your manifest in full. (No screenshots please, use the [markdown](https://guides.github.com/features/mastering-markdown/) to know how you should paste codes here.

**Comment by alvarengakenneth** [comment]
`<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
    <id>com.lnfphn.LNFPHN</id>
    <versionNumber>1.3</versionNumber>
    <supportedProfiles>mobileDevice</supportedProfiles>
    <filename>LNFPHN</filename>
    <name>LNFPHN</name>
    <initialWindow>
        <content>lnfp.swf</content>
        <systemChrome>standard</systemChrome>
        <transparent>false</transparent>
        <visible>true</visible>
        <fullScreen>true</fullScreen>
        <autoOrients>true</autoOrients>
        <aspectRatio>portrait</aspectRatio>
        <renderMode>gpu</renderMode>
    </initialWindow>
    <icon>
    <image36x36>nuevos%20icos/android/mipmap-ldpi/ic_launcher.png</image36x36>
    <image48x48>nuevos%20icos/android/mipmap-mdpi/ic_launcher.png</image48x48>
    <image72x72>nuevos%20icos/android/mipmap-hdpi/ic_launcher.png</image72x72>
    <image96x96>nuevos%20icos/android/mipmap-xhdpi/ic_launcher.png</image96x96>
    </icon>
    <customUpdateUI>false</customUpdateUI>
    <allowBrowserInvocation>false</allowBrowserInvocation>
    <versionLabel></versionLabel>
    <android>
        <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
            
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
            <uses-permission android:name="android.permission.WAKE_LOCK"/>
            
            
            <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
            <permission android:name="air.com.lnfphn.LNFPHN.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
            <uses-permission android:name="air.com.lnfphn.LNFPHN.permission.C2D_MESSAGE"/>
            
            <application>
            
                <activity>
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN"/>
                        <category android:name="android.intent.category.LAUNCHER"/>
                    </intent-filter>
                    <intent-filter>
                        <action android:name="android.intent.action.VIEW"/>
                        <category android:name="android.intent.category.BROWSABLE"/>
                        <category android:name="android.intent.category.DEFAULT"/>
                        <data android:scheme="air.com.lnfphn.LNFPHN" />
				
				        
				        
                    </intent-filter>
                </activity>
            
                
                <provider
                    android:name="com.google.firebase.provider.FirebaseInitProvider"
                    android:authorities="air.com.lnfphn.LNFPHN.firebaseinitprovider"
                    android:exported="false"
                    android:initOrder="100"/>
            
                
                <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
            
                
                <receiver
                    android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
                    android:exported="true"
                    android:permission="com.google.android.c2dm.permission.SEND">
                    <intent-filter>
                        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                        <category android:name="air.com.lnfphn.LNFPHN"/>
                    </intent-filter>
                </receiver>
                <receiver
                    android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver"
                    android:exported="false"/>
                <service
                    android:name="com.google.firebase.iid.FirebaseInstanceIdService"
                    android:exported="true">
                    <intent-filter android:priority="-500">
                        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
                    </intent-filter>
                </service>
            
                
                <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                    android:theme="@android:style/Theme.Translucent.NoTitleBar" 
                    android:exported="false"/>
            
                
             <service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
                    <intent-filter>
                        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                    </intent-filter>
                </service>
                <service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
                    <intent-filter>
                        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
                    </intent-filter>
                </service>
                <activity 
                    android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
                    android:theme="@style/Theme.Transparent"
                    android:exported="false"
                    android:noHistory="true"
                    android:clearTaskOnLaunch="true"
                    android:hardwareAccelerated="false"
                    android:stateNotNeeded="true">
                    <intent-filter>
                        <action android:name="MY_INTENT" />
                        <category android:name="android.intent.category.DEFAULT" />
                    </intent-filter>
                </activity>


                
                
                    
            </application>
            </manifest>]]></manifestAdditions>
    </android>
      <extensions>
	
	
	<extensionID>com.myflashlab.air.extensions.inspector</extensionID>
	
	
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
	
	
	<extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
	
	
	
  </extensions>
</application>
`

**Comment by alvarengakenneth** [comment]
```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
    <id>com.lnfphn.LNFPHN</id>
    <versionNumber>1.3</versionNumber>
    <supportedProfiles>mobileDevice</supportedProfiles>
    <filename>LNFPHN</filename>
    <name>LNFPHN</name>
    <initialWindow>
        <content>lnfp.swf</content>
        <systemChrome>standard</systemChrome>
        <transparent>false</transparent>
        <visible>true</visible>
        <fullScreen>true</fullScreen>
        <autoOrients>true</autoOrients>
        <aspectRatio>portrait</aspectRatio>
        <renderMode>gpu</renderMode>
    </initialWindow>
    <icon>
    <image36x36>nuevos%20icos/android/mipmap-ldpi/ic_launcher.png</image36x36>
    <image48x48>nuevos%20icos/android/mipmap-mdpi/ic_launcher.png</image48x48>
    <image72x72>nuevos%20icos/android/mipmap-hdpi/ic_launcher.png</image72x72>
    <image96x96>nuevos%20icos/android/mipmap-xhdpi/ic_launcher.png</image96x96>
    </icon>
    <customUpdateUI>false</customUpdateUI>
    <allowBrowserInvocation>false</allowBrowserInvocation>
    <versionLabel></versionLabel>
    <android>
        <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
            
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
            <uses-permission android:name="android.permission.WAKE_LOCK"/>
            
            <!--
                Required by firebase_iid.ane
                Change "air.com.lnfphn.LNFPHN" to your own app package name
            -->
            <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
            <permission android:name="air.com.lnfphn.LNFPHN.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
            <uses-permission android:name="air.com.lnfphn.LNFPHN.permission.C2D_MESSAGE"/>
            
            <application>
            
                <activity>
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN"/>
                        <category android:name="android.intent.category.LAUNCHER"/>
                    </intent-filter>
                    <intent-filter>
                        <action android:name="android.intent.action.VIEW"/>
                        <category android:name="android.intent.category.BROWSABLE"/>
                        <category android:name="android.intent.category.DEFAULT"/>
                        <data android:scheme="air.com.lnfphn.LNFPHN" />
				
				        <!-- Required by firebaseDynamicLinks.ane -->
				        <!--<data android:scheme="http" android:host="www.myflashlabs.com" />
				        <data android:scheme="https" android:host="www.myflashlabs.com" />-->
                    </intent-filter>
                </activity>
            
                <!--
                    Required by the firebase_common.ane
                    Change "air.com.lnfphn.LNFPHN" to your own app package name
                -->
                <provider
                    android:name="com.google.firebase.provider.FirebaseInitProvider"
                    android:authorities="air.com.lnfphn.LNFPHN.firebaseinitprovider"
                    android:exported="false"
                    android:initOrder="100"/>
            
                <!-- Required by googlePlayServices_basement.ane -->
                <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
            
                <!--
                    Required by firebase_iid.ane
                    Change "air.com.lnfphn.LNFPHN" to your own app package name
                -->
                <receiver
                    android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
                    android:exported="true"
                    android:permission="com.google.android.c2dm.permission.SEND">
                    <intent-filter>
                        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                        <category android:name="air.com.lnfphn.LNFPHN"/>
                    </intent-filter>
                </receiver>
                <receiver
                    android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver"
                    android:exported="false"/>
                <service
                    android:name="com.google.firebase.iid.FirebaseInstanceIdService"
                    android:exported="true">
                    <intent-filter android:priority="-500">
                        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
                    </intent-filter>
                </service>
            
                <!-- Required by googlePlayServices_base.ane -->
                <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                    android:theme="@android:style/Theme.Translucent.NoTitleBar" 
                    android:exported="false"/>
            
                <!-- Required by firebase_messaging.ane -->
             <service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
                    <intent-filter>
                        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                    </intent-filter>
                </service>
                <service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
                    <intent-filter>
                        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
                    </intent-filter>
                </service>
                <activity 
                    android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
                    android:theme="@style/Theme.Transparent"
                    android:exported="false"
                    android:noHistory="true"
                    android:clearTaskOnLaunch="true"
                    android:hardwareAccelerated="false"
                    android:stateNotNeeded="true">
                    <intent-filter>
                        <action android:name="MY_INTENT" />
                        <category android:name="android.intent.category.DEFAULT" />
                    </intent-filter>
                </activity>


                <!-- Required by firebase_analyticsImpl.ane and firebase-analytics.ane -->
                <!-- <receiver
                    android:name="com.google.android.gms.measurement.AppMeasurementReceiver"
                    android:enabled="true" 
                    android:exported="false">
                </receiver>
                <receiver 
                    android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" 
                    android:permission="android.permission.INSTALL_PACKAGES" 
                    android:enabled="true">
                    <intent-filter>
                        <action android:name="com.android.vending.INSTALL_REFERRER"/>
                    </intent-filter>
                </receiver>
                <service
                    android:name="com.google.android.gms.measurement.AppMeasurementService"
                    android:enabled="true"
                    android:exported="false"/> 
                <service
                    android:name="com.google.android.gms.measurement.AppMeasurementJobService"
                    android:permission="android.permission.BIND_JOB_SERVICE"
                    android:enabled="true"
                    android:exported="false"/> -->
                    
            </application>
            </manifest>]]></manifestAdditions>
    </android>
      <extensions>
	
	<!-- Use the inspector ANE tool to check if you have correctly added all the dependencies or not -->
	<extensionID>com.myflashlab.air.extensions.inspector</extensionID>
	
	<!-- download the dependency ANEs from https://github.com/myflashlab/common-dependencies-ANE -->
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
	
	<!-- And finally embed the Firebase core ANE -->
	<extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
	
	<!-- 
		When adding other Firebase Child ANEs, make sure to study the following page carefully to know
		which other ANEs/dependencies must be included to your project. 
		https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md
	-->
	
  </extensions>
</application>

```

**Comment by myflashlab** [comment]
Ok, it's clear that you are missing the fcm ANEs! Have you read this document? https://github.com/myflashlab/Firebase-ANE/wiki/G.1-Add-FCM please take your time and study the document carefully. I know, adding Firebase ANEs is really a pain. it has many dependencies and manifest settings, but there's nothing we could do, that's how it is. Just take your time and study the page fully.

you are missing the following: but please just don't copy paste from here, study the page above first.
```xml
<extensions>
	
	<!-- 
		Required ANEs for the Firebase Core ANE comes here first.
		https://github.com/myflashlab/Firebase-ANE/wiki/A.4.-Initialize-Firebase-in-your-app
	-->
	
	<!-- To support Firebase FCM -->
	<extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
	
	<!-- 
		Download the dependency ANEs from https://github.com/myflashlab/common-dependencies-ANE
		These dependencies are not required on the iOS side.
	-->
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
	
</extensions>
```

**Comment by alvarengakenneth** [comment]
Hi, i try a lot with all the instructions, but still have this error:

![error](https://user-images.githubusercontent.com/6536168/29010116-45fedb0e-7ae6-11e7-94fd-7c65e74ec148.png)

please help me
