### ISSUE TITLE
(Analytics) ?

### ISSUE THREAD

**Issue by leossmith** [myflashlab/Firebase-ANE#13]
Will Analytics be released soon? Google Analytics dropped support on connecting Analytics to Play Store or AdMob, so we are a bit in the dark untill we add Firebase :)

**Comment by myflashlab** [comment]
We're almost there. There is a bug on the iOS side which Firebase team have to fix. We'll be releasing the Android version soon though... Working on it at the moment :)

**Comment by leossmith** [comment]
Great :) i cant wait.

**Comment by myflashlab** [comment]
Firebase has a known bug on the Analytic side of their SDK. We have reported the issue to them and as soon as they fix the problem, we will be able to release the ANE too. You can follow up our discussion about the bug here: https://github.com/firebase/quickstart-ios/issues/34

**Comment by leossmith** [comment]
Thank you for the update. So it seems from their comments that this is just a matter of days? If the iOS side is the problem, is it possible to get a beta only supporting Android?

**Comment by myflashlab** [comment]
Yeah, that we can do. We will release the ANE anyway while waiting for the iOS side to be fixed. At least users can start using the Android side for now.

**Comment by leossmith** [comment]
This would be great. Can't wait.

**Comment by leossmith** [comment]
Is Analytics released? I can see the documentation but can't find the ane.

**Comment by myflashlab** [comment]
Yep, it should be released in a couple of days, we're adding the final touches...

**Comment by mrgoonie** [comment]
Any updates with Firebase Analytics for iOS version, @myflashlab ?

**Comment by chrismarrin** [comment]
I noticed there's an iOS V3.9.0 in the firebase downloads, has this been tested to see if it resolves the blocker issue with Analytics?

**Comment by myflashlab** [comment]
We are upgrading the whole Firebase ANEs to the latest version and will let you know if the new release will have the problem solved or not for sure. However, we think the Firebase team has not yet fixed it because if they had, they would had let us know about it in the issue we created above.

**Comment by myflashlab** [comment]
The latest Firebase release a couple of days ago has finally fixed this problem. We made sure it works fine on AIR apps and we're happy to announce that it does :) We are working on releasing Firebase ANE V4 soon. So, I'm closing this issue now.

**Comment by leossmith** [comment]
Is there a date for V4?

**Comment by myflashlab** [comment]
It should be ready by tomorrow we hope... we're working on it.

**Comment by leossmith** [comment]
Awesome 👍
