### ISSUE TITLE
Cannot extract message from invoke or FcmEvents.Message

### ISSUE THREAD

**Issue by hengway1989** [myflashlab/Firebase-ANE#132]
Hi, as subject, can please help advice, detail as below:
Device: Samsung galaxy note 5
Android: 7.0
Rom: Stock rom
AndroidSupport.VERSION:25.3.1
OverrideAir.VERSION:4.1.0
Barcode.VERSION:3.3.0
Firebase.VERSION:5.0.0
Firebase_common.VERSION:11.0.2
Firebase_iid.VERSION:11.0.2
Firebase_messaging.VERSION:11.0.2
GooglePlayServices_appinvite.VERSION:11.0.2
GooglePlayServices_base.VERSION:11.0.2
GooglePlayServices_basement.VERSION:11.0.2
GooglePlayServices_tasks.VERSION:11.0.2

1. From FcmEvents.Message

```
**Payload:** 
{
  "notification": 
  {
    "title": "Title",
    "text": "Your Text",
    "sound": "default"
    "badge": "8",
   
    "color": "#FF9900",
    
    "click_action": "MY_INTENT"
  },
  "priority" : "high",
  "registration_ids" : 
  	[
      "cSInU4LzxBM:APA91bFcxbnUy04VsL9k_2ZMsIvs6OWK1P-r6hpjBJbBNVvYZgr0hYnCc_q0a1op-BBl_GQY8MRl6srIGZ2oBgsuaStJEADNoGlB6beolkXhW7NQBejKl94L8HdxZrHWT3cW2f9RoW4Y"
    ]
}
```
**From OverrideAir.enableDebugger:**

```
$ane = FirebaseFCM
$class = MyFirebaseMessagingService
$msg = remoteMessage.toString() = com.google.firebase.messaging.RemoteMessage@dc03ef3
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingService
$msg = remoteMessage.getFrom() = 809237243559
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingService
$msg = remoteMessage.getTo() = null
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingService
$msg = remoteMessage.getData() = {}
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingService
$msg = remoteMessage.getNotification().getBody() = Your Text
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingService
$msg = remoteMessage.getNotification().getClickAction() = MY_INTENT
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingService
$msg = remoteMessage.getNotification().getTitle() = Title
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingService
$msg = remoteMessage.getNotification().getSound() = default
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingService
$msg = MyExtension.AS3_CONTEXT != null so we can dispatch to AIR
------------------
```
But e.msg show "{}"
<img width="681" alt="screen shot 2017-08-03 at 22 18 48" src="https://user-images.githubusercontent.com/13148479/28929285-ca7b907e-7899-11e7-9d39-b4a742ca2225.png">

2. From Invoke 

Payload: same as above

**From OverrideAir.enableDebugger:**
```
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = onCreate
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = key = google.sent_time value = 1501773636427
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = key = from value = 809237243559
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = key = google.message_id value = 0:1501773636433058%5208c6525208c652
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = key = collapse_key value = air.com.xeersoft.testinapppurchase
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = build intent start...
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = build intent finished
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = startActivity started...
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = startActivity finished
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = onStart
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = onResume
------------------
------------------
$ane = FirebaseFCM
$class = MyFirebaseMessagingIntent
$msg = onPause
------------------
```
But e.arguments show: "air.com.xeersoft.testinapppurchase://%7B%22google.sent_time%22%3A1501773636427%2C%22from%22%3A%22809237243559%22%2C%22google.message_id%22%3A%220%3A1501773636433058%255208c6525208c652%22%2C%22collapse_key%22%3A%22air.com.xeersoft.testinapppurchase%22%7D"	
"android.intent.action.VIEW"	
<img width="671" alt="screen shot 2017-08-03 at 22 20 56" src="https://user-images.githubusercontent.com/13148479/28929521-53f428de-789a-11e7-87dc-222432ca7350.png">

**Comment by myflashlab** [comment]
From what you have said, you are sending notification messages only. With a notification FCM, you can't have a payload data. you need to send a mix or a data FCM. please read this article for more information: http://www.myflashlabs.com/send-fcm-messages-server/

**Comment by myflashlab** [comment]
Please let us know if you still have this problem?

**Comment by hengway1989** [comment]
yes, I still do not found a way to receive the massage from invoke or during user using the app, do you have sample code that I can refer to, thank you

**Comment by myflashlab** [comment]
@hengway1989 We have FD, IntelliJ and FLA samples. Let us know more information about the problem, we can't duplicate the problem just yet.

**Comment by hengway1989** [comment]
@myflashlab Thank you for advice, currently I need remove all fcm ane from my app, because I get report from some device, when on the app, it crash immediately, the issue same as the issue mention here: https://github.com/myflashlab/Firebase-ANE/issues/116
The issue happen on, 
1. Honor 3c
2. Huawei p9 mate
Please help solve this issue first, thank you

**Comment by myflashlab** [comment]
As you can see, we are waiting for Google to look into [issue 116](https://github.com/myflashlab/Firebase-ANE/issues/116) as it seems like this is originated from the SDK  directly.

**Comment by myflashlab** [comment]
@hengway1989 this might be the answer? https://github.com/myflashlab/Firebase-ANE/issues/169#issuecomment-351726370

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
