### ISSUE TITLE
FCM ANE: Getting error when iOS app packaging

### ISSUE THREAD

**Issue by mprabhu33** [myflashlab/Firebase-ANE#134]
Getting below error when iOS app packaging using Flash builder.

Error occurred while packaging the application
Id: framework not found FirebaseAnalytics
Compilation failed while executing: Id64

**Comment by myflashlab** [comment]
you are missing the iOS frameworks! please make sure you have studies the documentations more carefully. https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

**Comment by mprabhu33** [comment]
Thanks for your information.
Now i added all iOS dependencies frameworks. Not getting framework error now.
Still couldn't able to generate iOS ipa package using Flashbuilder4.6.
Waited more than 2 hours.
![image](https://user-images.githubusercontent.com/29938922/29018716-cad8e8cc-7b79-11e7-8928-f85721f95a3a.png)

Am able to generate android .apk package using Flashbuilder4.6.
Still anything am missing for IOS?

IDE: Flash builder 4.6
AIR: 27.0

 <iPhone>

        <InfoAdditions><![CDATA[
         		
	        <key>MinimumOSVersion</key>
	        <string>8.0</string>
	        <key>UIPrerenderedIcon</key>
        	<true/>
        
			<key>UIDeviceFamily</key>
				<array>
					<string>1</string>
					<string>2</string>
				</array>
			<key>UIStatusBarStyle</key>
            	<string>UIStatusBarStyleDefault</string>
            <key>UIFileSharingEnabled</key>
            	<true/>   
            <key>UIBackgroundModes</key> 
		        <array> 
		               <string>location</string> 
		               <string>remote-notification</string>
		         </array>                  
	         <key>UIRequiredDeviceCapabilities</key> 
				<array> 
				    <string>location-services</string> 
				   
				</array> 			          
        	<key>NSLocationWhenInUseUsageDescription</key> 
       			<string>Allow geolocation when application is in foreground</string>
       		<key>NSLocationAlwaysUsageDescription</key> 
       		 	<string>Allow geolocation always when application is in foreground or background</string>			  
			 <key>NSAppTransportSecurity</key> 
       		    <dict> <key>NSAllowsArbitraryLoads</key><true/> </dict>
       		    


			  
		]]></InfoAdditions>
		<Entitlements><![CDATA[
		    <key>get-task-allow</key>
		    <true/>
		    <key>aps-environment</key>
            <string>development</string>         
		    <key>application-identifier</key>
		    <string>XXXXXXXXX.com.symphonysummit.SummitServiceManagement51WS</string>
		    <key>com.apple.developer.team-identifier</key>
			<string>XXXXXXXXX</string>
		    <key>keychain-access-groups</key>
		    <array>
		   		 <string>XXXXXXXXX.*</string>
		    </array> 
		  ]]></Entitlements>
        <requestedDisplayResolution>high</requestedDisplayResolution>
    </iPhone>

   <extensions>        
    	
    	        
        
        
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
    </extensions>

**Comment by mprabhu33** [comment]
After added all iOS dependencies frameworks. Not getting framework error now.
Hence closing this issue.
Still couldn't able to generate iOS package using Flash Builder 4.6. with adobe air 27.0.
Log separate issue for the above issue
