### ISSUE TITLE
FCM CoreANE: Download latest Ane Maker V 5.0.0

### ISSUE THREAD

**Issue by mprabhu33** [myflashlab/Firebase-ANE#135]
Hi,

How to download latest AneMaker V5.0.0?
FirebaseCore.zip contains AneMaker V4.0.0 form myflashlabs download page.
http://www.myflashlabs.com/my-account/downloads/

**Comment by myflashlab** [comment]
thanks for your notice, it seems like the server guys had missed a bit :) please check back and re-download the packages. it should be fixed now.

**Comment by mprabhu33** [comment]
Able to download latest AneMaker now.
Thanks for quick action.
