### ISSUE TITLE
FCM: Foreground notification ok, Background not showing in tray?

### ISSUE THREAD

**Issue by Soshaapp** [myflashlab/Firebase-ANE#136]
Hi Guys, could you help me track down what's going on?

Setup:
Flashbuilder 4.7
AIR SDK 26
Latest MyFlashLabClub_ANEs_package ( 19 / 7 - 2017 )
Frameworks 4.0.3
IOS App

InfoAdditions:
```xmlx
<key>UIBackgroundModes</key>
<array>string>remote-notification</string></array>
```

Entitlements:
```xml
<key>keychain-access-groups</key>
<array><string>XXXXXXXXXX.*</string></array>
<key>get-task-allow</key>
<true/>
<key>application-identifier</key>
<string>XXXXXXXXXX.air.com.socialsosha.sosha</string>
<key>com.apple.developer.team-identifier</key>
<string>XXXXXXXXXX</string>
<key>aps-environment</key>
<string>development</string>
```

Code:
```actionscript
Firebase.init( true );
FCM.init();
FCM.listener.addEventListener( FcmEvents.TOKEN_REFRESH, fcmTokenRefresh );
FCM.listener.addEventListener( FcmEvents.MESSAGE, fcmMessage );
```

Problem:
I'm sending a message to a single device, using the token.

I'm not getting notifications when the App is in the background or killed.
fcmMessage() is triggered when the App is open and I send a message from FB Console.
fcmMessage() is triggered when the App is closed and then opened after a message has been sent.

So do you have any idea what could be wrong here, since everything is setup correctly and I recieve the message while in foreground but not background?

Thanx! :)

**Comment by mprabhu33** [comment]
Are you able to generate iOS adhoc package using Flash builder?
How are you testing iOS app using simulator?
Couldn't able to generate iOS package.

**Comment by mprabhu33** [comment]
Able to generate iOS package after update FirebaseCore.ane generated using AneMaker V5.0.0
Note: Used AneMaker V4.0.0, couldn't able to generate iOS Package.

**Comment by myflashlab** [comment]
Similar to #138, it feels like you guys are missing something in upgrading to V5. Please follow the steps here and see how it goes: https://github.com/myflashlab/Firebase-ANE/issues/137#issuecomment-322037016

**Comment by quantuan** [comment]
hi admin. 
i use FCM for Android and IOS by Flex framework.
On Android, FCM work nomarlly. But on IOS i also have  this problem.
i try fix this problem by update to firebase V5.1.1 but my application still have this problem.

Setup:
Flashbuilder 4.7
AIR SDK 27
Latest MyFlashLabClub_ANEs_package 
Frameworks 4.0.3
IOS 10.2 , Iphone 5s

I thinhk i config correctly. 
i hope you help me fix this problem.

**Comment by myflashlab** [comment]
We are not able to duplicate the problem but there's something else you may also consider. on iOS, sometimes it may take a while for the token to be propagated fully. If you are sure everything is set correctly, maybe all you have to do is to wait a little bit more for the token to be fully propagated. Yo may also find this post useful: http://www.myflashlabs.com/send-fcm-messages-server/

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
