### ISSUE TITLE
Auth: Dosn't remember FirebaseUser after upgrading to 5.0?

### ISSUE THREAD

**Issue by Soshaapp** [myflashlab/Firebase-ANE#137]
Setup:
Flashbuilder 4.7
AIR SDK 26
Latest MyFlashLabClub_ANEs_package ( 19 / 7 - 2017 )
Frameworks 4.0.3
IOS App
iPhone 5S

I have just upgraded from 4.0 to 5.0 and have not changed a line of code in the App.

Problem:
Auth forgets FirebaseUser after I've signed in and restarts the App?

First time App start in debugger:
```
FirebaseAuth BaseClassFirebaseAuth onAuthStateChanged > _user is null now
FirebaseAuth BaseClassFirebaseAuth onIdTokenChanged > _user is null now
```
Signing in:
```
FirebaseAuth BaseClassFirebaseAuth onAuthStateChanged > new _user data
FirebaseAuth BaseClassFirebaseAuth onIdTokenChanged > new _user data
```
After restart:
```
FirebaseAuth BaseClassFirebaseAuth onAuthStateChanged > _user is null now
FirebaseAuth BaseClassFirebaseAuth onIdTokenChanged > _user is null now
```

Thanx :)

**Comment by myflashlab** [comment]
Sorry for the short delay on getting back on this. I'm here to help you now. So, the first thing to look at is if you have correctly updated to V5 or not. It is very probable that you have missed to update ANEs correctly. The blame is not on you 😄 Firebase has a lot of settings/ANEs to be configured.

Follow the steps:
1. use the aneManker software V5 to regenerate the firebase core ANE.
2. make sure you are using the latest dependency ane files.
3. Make sure you have read the [changelog](https://github.com/myflashlab/Firebase-ANE#changelog) and have fixed the manifest settings.
4. If you are trying on iOS, make sure to delete the old .framework files first and then copy the new ones. do NOT try to overwrite them. 

let me know if you still have this problem and we'll try another thing.

**Comment by Soshaapp** [comment]
Ok, guys, I've figured it out, but it's really weird and I need you to confirm this.

I'm using FCM together with Auth.
In <Entitlements> I have what's required to make FCM to work:
`<key>keychain-access-groups</key>
			<array>
				<string>XXXXXXXXXX.*</string>		
			</array>
			<key>get-task-allow</key>
			<true/>
			<key>application-identifier</key>
			<string>XXXXXXXXXX.air.com.socialsosha.sosha</string>
			<key>com.apple.developer.team-identifier</key>
			<string>XXXXXXXXXX</string>
			<key>aps-environment</key>
			<string>development</string>`

This will cause Auth NOT remembering the FirebaseUser.

Removing:
`<key>keychain-access-groups</key>
			<array>
				<string>XXXXXXXXXX.*</string>		
			</array>`
Will have BOTH Auth AND FCM working!?

Could you please explain what's going on and have you guys tested that FCM AND Auth works together like this?

Thanx :)

**Comment by myflashlab** [comment]
We had tested this before but to be sure, we tested again and they are working fine together!

**Comment by quantuan** [comment]
hi admin.
I use firebase core version 4, everything is setup correctly for V4 and I recieve the message while in foreground but not background? 
I use firebase V4 recieve notification in mode background?

**Comment by myflashlab** [comment]
@quantuan Please first update to the latest version of the ANEs and second, please open a new issue when discussing a new topic unrelated to the current thread. Thanks.

**Comment by mikron123** [comment]
EXACTLY the same bug happens to me, and I did not upgrade from 4 to 5. I'm using v5.
And Soshaapp is right, removing the above FCM lines does make the problem to go away.

How do we solve it? Please provide an answer. Thank you.

**Comment by mikron123** [comment]
@Soshaapp please let me know how you solved it if you ever did, I couldn't find a workaround and it's a "project halting" bug. @myflashlab, please provide a solution as FCM right now seems unusable with Auth on iOS.

Thanks you.

**Comment by mikron123** [comment]
Another problem with FCM regarding Storage this time. Storage.getReference() throws null pointer exception if FCM was inited. After changing the order of the ANEs init so FCM will be last, it solved the Storage bug, but not the Auth. :\

**Comment by myflashlab** [comment]
@mikron123  We are pretty sure that there must be something wrong in your setup because no matter what we do, we are not able to duplicate the problem and Firebase children are all working fine with each other.

Please open a new issue and provide as much information as you can about this probable bug and will try to see and help you with anything that might be missing.

**Comment by myflashlab** [comment]
We have just released V6.0.0 of the Firebase. please let us know if this is still happening?

**Comment by mikron123** [comment]
How do I download the new version if I already purchased the last one within a year?

**Comment by myflashlab** [comment]
for non-tech questions, please use https://www.myflashlabs.com/contact/

**Comment by mikron123** [comment]
To be honest, I'm moving to React Native. Your Facebook login "hidden catch" for subscription after purchasing the Auth ANE, broke my patience.
Additionally, I barely got any reply from your support through the above link. Good luck.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
