### ISSUE TITLE
FCM: iOS app Notification messages are not displayed in Notification Tray

### ISSUE THREAD

**Issue by mprabhu33** [myflashlab/Firebase-ANE#138]
Hi,
Adobe AIR: 26.0 and 27.0 Beta
ANE Maker: V5.0.0
Tested iOS Device: iPad and iPhone
App Status: Background and Killed

Notification messages are not displayed in Notification tray and also no badge data.
Anyone tested on iOS device with latest FCM Core and Messaging ANE?

Able to see below messages in the app 
```
onMessage: {
  "from" : "315327601194",
  "collapse_key" : "com.xxx.xxxx",
  "notification" : {
    "body" : "iOS - FCM Message",
    "title" : "SUMMIT",
    "sound" : "default",
    "badge" : "1",
    "sound2" : "default",
    "e" : "1"
  }
}
```
```xml
<iPhone>

        <InfoAdditions><![CDATA[
			<key>UIDeviceFamily</key>
				<array>
					<string>1</string>
					<string>2</string>
				</array>
			<key>UIStatusBarStyle</key>
            	<string>UIStatusBarStyleDefault</string>
            <key>UIFileSharingEnabled</key>
            	<true/>   
            <key>UIBackgroundModes</key> 
		        <array> 
		               <string>location</string> 
		               <string>remote-notification</string>
		         </array>                  
	         <key>UIRequiredDeviceCapabilities</key> 
				<array> 
				    <string>location-services</string> 
				   
				</array> 			          
        	<key>NSLocationWhenInUseUsageDescription</key> 
       			<string>Allow geolocation when application is in foreground</string>
       		<key>NSLocationAlwaysUsageDescription</key> 
       		 	<string>Allow geolocation always when application is in foreground or background</string>			  
			 <key>NSAppTransportSecurity</key> 
       		    <dict> <key>NSAllowsArbitraryLoads</key><true/> </dict>
			  
		]]></InfoAdditions>
		<Entitlements><![CDATA[
		    <key>get-task-allow</key>
		    <true/>
		    <key>aps-environment</key>
            <string>development</string>         
		    <key>application-identifier</key>
		    <string>xxxxxxx.com.xxx.xxxxx</string>
		    <key>com.apple.developer.team-identifier</key>
			<string>xxxxxxx</string>
		    <key>keychain-access-groups</key>
		    <array>
		   		 <string>xxxxxxx.*</string>
		    </array> 
		  ]]></Entitlements>
        <requestedDisplayResolution>high</requestedDisplayResolution>
    </iPhone>
<extensions>
	<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
 	<extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
</extensions>
```
Code:
```actionscript
FCM.init();
			FCM.listener.addEventListener(FcmEvents.TOKEN_REFRESH, onTokenRefresh);
			FCM.listener.addEventListener(FcmEvents.MESSAGE, onMessage);
			
			var tokenID:String = FCM.getToken();

private function onMessage(e:FcmEvents):void
		{
			writeLog("onMessage: "+e.msg)
			var payload:Object = FCM.parsePayloadFromString(e.msg);
			
			if (payload)
			{
				for (var name:String in payload)
				{
					writeLog(name + " = " + payload[name]);
				}
			}
		}
```

**Comment by myflashlab** [comment]
Are you seeing this on iOS 10 or older?

Anyhow, considering that you are receiving the fcm while app is running, it seems that the ANE is catching the message. in iOS, when app is closed (in background or when killed) the iOS system will generate the notification automatically. This means that the ane won't be run at the time when fcm arrives. If the notification is not shown, it is very probable that there's something wrong with the certificates, entitlements or provision files.

The fcm is working just fine as we are testing it. 🤔

**Comment by hengway1989** [comment]
Hi, I have this issue as well, but not sure related to bundle Id? because for android, it is: air.com.XXX.XXX, but in IOS it is com.XXX.XXX.
I try the given tips, but look like not solving the issue, please advice

**Comment by myflashlab** [comment]
@hengway1989 please let us know if you are seeing this on iOS 10 or older versions?

**Comment by hengway1989** [comment]
I am using on iPad IOS 10.3.3
below are the ane and air version
AIR 26.0
Firebase.VERSION:5.0.0
Firebase_common.VERSION:11.0.2
Firebase_iid.VERSION:11.0.2
Firebase_messaging.VERSION:11.0.2
GooglePlayServices_appinvite.VERSION:11.0.2
GooglePlayServices_base.VERSION:11.0.2
GooglePlayServices_basement.VERSION:11.0.2
GooglePlayServices_tasks.VERSION:11.0.2

If I put in the debugger code, then the push notification will be able to receive in notification tray
OverrideAir.enableDebugger(myDebuggerDelegate);

So should I let above code appear in my production release?

**Comment by myflashlab** [comment]
> If I put in the debugger code, then the push notification will be able to receive in notification tray

This is getting very weird! having the debug enabled or disabled can't have anything to do with the fcm and besides that, when the app in iOS is closed or in background, the ANE code won't run till the next launch/activation. the iOS itself is supposed to show the notification in the tray.

I remember that when we were working with GCM on iOS few years ago, sometimes on the development builds, we had a similar problem. The problem never occurred again when we deleted the app and reinstalled again. Try that and let us know how it goes. 😕

**Comment by hengway1989** [comment]
One pattern I found is, if let say I debug 5 times, if I enable OverrideAir.enableDebugger(myDebuggerDelegate);
in one of the five time debug, then will be able to receive the push notification in tray, even last debug I remove that code, as long as I do not reinstall the app, it will be able keep receiving push notification in tray. I think should be when on the OverrideAir.enableDebugger(myDebuggerDelegate);
it enable something, and allow the app doing register with native IOS notification engine. Once registered, will be able to keep using. Hope this message help on investigation. Thank you

**Comment by mprabhu33** [comment]
Any update?
Removed keycahinaccessgroup as mentioned in issue#137.
Still not able to see the notification messages in iOS app.
Device:iPad2
OS: 9.3.2
Adobe AIR: 26.0 and 27.0 Beta
ANE Maker: V5.0.0
Tested iOS Device: iPad2 and iPhone5s
App Status: Background and Killed

**Comment by mprabhu33** [comment]
Working fine now.
Downloaded the latest ANE V5.1.0 and iOS app Notification messages are displayed in Notification Tray.
App Status: Background and Killed
Tested on iOS Device: iPad2 and iPhone5s
Adobe AIR: 26.0 
ANE Maker: V5.1.0

Note: Don't use ANE V5.0.0, it has some issue.

**Comment by myflashlab** [comment]
We are glad it worked for you BUT in V5.1.0 we did NOT touch anything related to FCM at all. Only the Core ANE was updated in V5.1.0 with some new APIs described in the [changelog](https://github.com/myflashlab/Firebase-ANE#changelog).
