### ISSUE TITLE
onDataChange retrieves the local snap instead of the realtime value

### ISSUE THREAD

**Issue by GV3** [myflashlab/Firebase-ANE#14]
Hi guys, 

I don't know if this is a bug or if it's by design. 

When I start listening for the onDataChange() event the handler receives a value, this value is the one previously saved locally, then it immediately calls the handler a second time and retrieves the correct updated value on the cloud.

The documentation says: 

> "You can use the function  to read a static snapshot of the contents at a given path, as they existed at the time of the event. This method is triggered once when the listener is attached and again every time the data, including children, changes."

I read 

> "as they existed at the time of the event"

 not 

> as it existed **LOCALLY** at the time of the event

I expect the method to trigger once when is added retrieving the real-time value and not the one saved locally, and then to trigger every time the value is changed.

So, in case this is the default behavior and is by design, could you add a flag in the DBEvent for us to know if the value is the last saved local value?

How to reproduce:

1) Load an existing object via:

`_myReference.child(childID).addEventListener(DBEvents.VALUE_CHANGED, onChildLoaded); // value = "Hello world"`

2) Kill the App and change the value via Firebase console to "Hello again World";

3) Load again the object via:

`_myReference.child(childID).addEventListener(DBEvents.VALUE_CHANGED, onChildLoaded); // value = "Hello world"`

4) Wait and the handler will be called again immediately after with the value: "Hello again World"

**Comment by GV3** [comment]
Guys, any thoughts on this?

**Comment by GV3** [comment]
It turns out it's the normal behavior of Firebase and there is no way to know whether the event came from the server or from the local cache:

http://stackoverflow.com/questions/39441908/ondatachange-retrieves-the-local-snap-instead-of-the-realtime-value?noredirect=1#comment66206176_39441908

**Comment by myflashlab** [comment]
Correct, this is how Firebase works at the moment and I do agree that it's a pain. We are waiting for them to fix this and we will also update the ANE when that happens of course. Nothing to be done on our side just yet.
