### ISSUE TITLE
Downgrading from 5.0 to 4.0, where can I download 4.0 ANE's?

### ISSUE THREAD

**Issue by Soshaapp** [myflashlab/Firebase-ANE#140]
Hi Guys.

There are some bugs in 5.0, so I have to downgrade to 4.0, that are no longer on my machine, so where can I download those again, since the Club package is not versionized?

Thanx

**Comment by myflashlab** [comment]
Downgrading the ANEs is not suggested and it will lead to many unpredicted problems. I've just replied back your other ticket #137 so we can walk through this problem and make sure your app is upgraded correctly with the latest release. Thanks.
