### ISSUE TITLE
FCM on ios Error ITMS-90034

### ISSUE THREAD

**Issue by alvarengakenneth** [myflashlab/Firebase-ANE#141]
Hi, I already try create a new provisional file, and .p12 with Push certificate enabled, etc..

always give me this error:

![apple error ultimo](https://user-images.githubusercontent.com/6536168/29304124-9c1c3748-814e-11e7-8415-7a7ae0e0e7db.png)

**Comment by myflashlab** [comment]
This does not seem to be related to the ane. check this out maybe: https://stackoverflow.com/questions/31711335/ios-missing-or-invalid-signature-the-bundle-is-not-signed-using-an-apple-submis
