### ISSUE TITLE
[DynamicLinks IOS], what do I have to set [dlscheme] value to?

### ISSUE THREAD

**Issue by Soshaapp** [myflashlab/Firebase-ANE#142]
Hi Guys.
I can't make DynamicLinks to open the App ( when installed ), directly from a Dynamic Link :)

Could you explain what the [dlscheme] String value should be, since the documentation is not clear on this?

`
        <key>com.myflashlabs.firebase.deepLinkURLScheme</key>
        <string>dlscheme</string>`

Thanx :)

**Comment by myflashlab** [comment]
you may find this information useful: https://stackoverflow.com/questions/43749819/what-is-customurlscheme-in-firebase-dynamic-links

And about dynamic links opening the app, are you sure you have enabled it when initializing the Firebase core? ```Firebase.init(true);```

Please give us more information... have you gone through the wiki? https://github.com/myflashlab/Firebase-ANE/wiki/I.1-Add-Dynamic-links

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
