### ISSUE TITLE
Firebase App Index and Performance

### ISSUE THREAD

**Issue by leossmith** [myflashlab/Firebase-ANE#144]
I can see that the Firebase App Index .ane is available in the Common dependencies repository. Does this mean that it can be used in the Apps (android and iOS)?

If not are there any plans to develop these two anes?

Thank you.

**Comment by leossmith** [comment]
Awesome. Thank you for the update. Performance will be a much needed tool once ready.

**Comment by leossmith** [comment]
Firebase Index seems like it plays a major role for ASO at the moment. Please consider adding it. Thank you.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
