### ISSUE TITLE
Weird issue with Analytics

### ISSUE THREAD

**Issue by Igazine** [myflashlab/Firebase-ANE#146]
Hi there,

I noticed a very weird issue with Firebase Analytics (FA) 5.0.

When I first created the app and added everything (XMLs, dependencies, ANEs), everything worked fine for like 3 minutes. Then after registering 5 events in FA StreamView (4 default events and 1 custom I sent) it stopped registering any further events, and nothing really happened after this point for like an hour. The app is currently sending screen view and search events. 

To figure out what's going on I've enabled [DebugView](https://support.google.com/firebase/answer/7201382?hl=en) on my test device and started logging Firebase events in the console as well.

After that I could see the events in FA DebugView, all the manually registered and the automatic events as well (AdMob ad impressions), but only in DebugView.

After disabling DebugView on my device, went back to see if there's still anything logged in StreamView, and since the original 5 events no event has been logged.

Notes:

- I've only tested this with Android so far, will update the issue with the result of iOS testing
- I've installed/reinstalled the app countless times, still nothing
- I've checked everything in the app descriptors, ANEs, everything looks to be working fine, Inspector does not throw an error, FirebaseConfig displays values, AdMob is working fine
- I've just started with FA today, so I can't see any events in FA's main Events view yet, it needs like 24 hours to show up, but StreamView supposed to be realtime
- AIR is latest 27 beta, target SDK is 27, SWF version is 38, Android targetSdkVersion is 21, Android is cooked v7.1.2

Does anyone have any idea what can be the issue?

Thank you

**Comment by myflashlab** [comment]
well, this is weird. maybe it's something temporary on the server side or your network because if the ANE worked first, then it means it's connecting correctly.

Anyway, I shared this with the team and we'll do some deep investigation on this a.s.a.p. In the meanwhile, that would be helpful if you share with us your manifest and some related AS codes.

Also, I wonder if you have searched for a similar issue on the native side? I mean if a similar issue has been ever reported by native developers of Firebase?

**Comment by Igazine** [comment]
Thank you for taking the time looking into it.

After 24 hours, every event showed up in FA, so it looks like either the StreamView is buggy, or it's not really realtime and totally works as intended (I doubt this is the reason events won's show up in StreamView but you never know with Big G)

I don't really know what's going on in the background with the services and all, but is it possible that after the first few events, the following consequent evens are being delayed/postponed/batched and sent in once at a later time and that is why I can't see anything in StreamView? But then again DebugView is fine, so I'm not sure

Please keep this issue open if possible, maybe the FB team can provide some explanation.

Thank you again!

**Comment by myflashlab** [comment]
Thanks for the update. maybe it would be a good idea if you are creating an issue in the firebase repository also while linking to here or vice versa?

https://github.com/firebase/quickstart-ios
https://github.com/firebase/quickstart-android

**Comment by Igazine** [comment]
Just tested it and everything looks to be fine in StreamView as well 👍 

Thank you for taking the time looking into it, must've been something on their end.
