### ISSUE TITLE
Auth event result values

### ISSUE THREAD

**Issue by 4malik** [myflashlab/Firebase-ANE#147]
I didn't find any event.result values in your documentation. 
So i got event.result  
-100 - default value
0 - success
1 - The sms verification code used to create the phone auth credential is invalid. (phone)
1 - The password is invalid or the user does not have a password. (email)
2 - There is no user record corresponding to this identifier. The user may have been deleted.
8 - We have blocked all requests from this device due to unusual activity. Try again later.

Can you give more answers that could be retrieved by auth in your lib.
I found your 35 string errors.

**Comment by myflashlab** [comment]
You should checkout the [asdoc](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/firebase/auth/Auth.html#ACTION_CODE_OPERATION_PASSWORD_RESET) for the full list. Thanks.

**Comment by 4malik** [comment]
ohhh, thanks. 
I saw this asdoc but didnt see that small digits. _)

**Comment by 4malik** [comment]
Why after getting success SIGN_IN_RESULT Im getting also PHONE_AUTO_RETRIEVAL_TIME_OUT ?
