### ISSUE TITLE
compilation failed while executing ld64

### ISSUE THREAD

**Issue by hugojclvaz** [myflashlab/Firebase-ANE#149]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Android API Version: 7.0
* iOS Version: 10
* AIR SDK Version: 27.0.0.116
* Ane version: 5.0

## Problem Description ##
My ploblem.

Error creating files

Id: framework not found FirebaseAnalytics
Id: framework not found FirebaseAnalytics
Compilation failed while executing: Id64

![bug](https://user-images.githubusercontent.com/29093320/29961938-237879ec-8ef9-11e7-8ef2-08994a9af8a8.png)

![bug2](https://user-images.githubusercontent.com/29093320/29961933-1f0346bc-8ef9-11e7-9d14-fe680903f5cd.png)

My manifest.
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!-- 
  Usage:

  To localize the description, use the following format for the description element.
  <description>
  <text xml:lang="en">English App description goes here</text>
  <text xml:lang="fr">French App description goes here</text>
  <text xml:lang="ja">Japanese App description goes here</text>
  </description>

  To localize the name, use the following format for the name element.
  <name>
  <text xml:lang="en">English App name goes here</text>
  <text xml:lang="fr">French App name goes here</text>
  <text xml:lang="ja">Japanese App name goes here</text>
  </name>
-->
<application xmlns="http://ns.adobe.com/air/application/27.0">
  <id>air.com.korridas.ios</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel/>
  <filename>korridas</filename>
  <description/>
  <name>korridas</name>
  <copyright/>
  <initialWindow>
    <content>korridas-apple-empty.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>false</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon>

    
    <image29x29>icones/icon_29.png</image29x29>
    <image57x57>icones/icon_57.png</image57x57>
    <image114x114>icones/icon_114.png</image114x114>
    <image512x512>icones/icon_512.png</image512x512>
    <image48x48>icones/icon_48.png</image48x48>
    <image72x72>icones/icon_72.png</image72x72>
    <image50x50>icones/icon_50.png</image50x50>
    <image58x58>icones/icon_58.png</image58x58>
    <image100x100>icones/icon_100.png</image100x100>
    <image144x144>icones/icon_144.png</image144x144>
    <image1024x1024>icones/icon_1024.png</image1024x1024>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
 
  <supportedLanguages>en pt es</supportedLanguages>
  <iPhone>
     <InfoAdditions><![CDATA[
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>
  <key>MinimumOSVersion</key>
  <string>8.0</string>
  <key>UIPrerenderedIcon</key>
  <true/>
  <key>UIStatusBarStyle</key>
  <string>UIStatusBarStyleBlackOpaque</string>
  <key>UIRequiresPersistentWiFi</key>
  <string>NO</string>
  <key>UIDeviceFamily</key>
  <array>
    <string>1</string>
    <string>2</string>
  </array>
  <!-- 
      Required by firebaseInvites.ane
      Change google client id to your own. Find it in GoogleService-Info.plist
    -->
  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleTypeRole</key>
      <string>Editor</string>
      <key>CFBundleURLName</key>
      <string>google</string>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>com.googleusercontent.apps.619592626433-6nsit149hmab8duf0eq6tddhgnirejs5</string>
      </array>
    </dict>
  </array>
  <!-- Required by firebase_messaging.ane -->
  <!--<key>UIBackgroundModes</key><array><string>remote-notification</string></array>-->
  <!-- Required by firebaseDynamicLinks.ane -->
  <!--<key>com.myflashlabs.firebase.deepLinkURLScheme</key><string>dlscheme</string>-->
]]></InfoAdditions>
  
    <requestedDisplayResolution>high</requestedDisplayResolution>
  </iPhone>
  
  
  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
  </extensions>
</application>
```

## Steps to Reproduce ##
My project file is empty, the only thing i'm doing import ANE folders to my project, as shown in bug2.jpq image, attatch is the manifest.xml file.

## Known Workarounds ##
In Android version is running perfectly

**Comment by myflashlab** [comment]
Well, any error message similar to ```Id: framework not found FirebaseAnalytics``` is very self explanatory. It is saying that you are missing ```FirebaseAnalytics.framework```. When looking at your screenshot, I don't see the framework being addresses neither. you must include that also. [This page](https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md) is telling you what frameworks are needed.

**Comment by myflashlab** [comment]
Another thing you should remember is to make sure you are copying the frameworks to a folder which is really used when compiling your app iOS side. In some cases, users use the ```–platformsdk``` command in their ```adt``` to use the latest xcode ios sdk instead of what is available in AIR SDK. In that case, copying the Firebase frameworks to the ```AIR/lib/aot/stub``` is useless and instead, you should copy them to your xcode ios sdk: https://developer.apple.com/library/content/documentation/Miscellaneous/Conceptual/iPhoneOSTechOverview/iPhoneOSFrameworks/iPhoneOSFrameworks.html

>> Table A-1 describes the frameworks available in iOS-based devices. You can find these frameworks in the <Xcode.app>Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/<iOS_SDK>/System/Library/Frameworks directory, where <Xcode.app> is the path to your Xcode app and <iOS_SDK> is the specific SDK version you are targeting. The "First available” column lists the iOS version in which the framework first appeared

**Comment by hugojclvaz** [comment]
how i include framworks in my project?

"framework being addresses neither"?


![2](https://user-images.githubusercontent.com/29093320/30433317-1491c600-995c-11e7-84b7-722f4a631a9e.JPG)
![1](https://user-images.githubusercontent.com/29093320/30433316-148e6cda-995c-11e7-8ff4-e00c46282e5f.JPG)

the address to library is /lib/aot/stub ?

**Comment by hugojclvaz** [comment]
Now i have this error on compile, but the apple id is the same everywere 

![3](https://user-images.githubusercontent.com/29093320/30433807-57c005da-995d-11e7-8865-c39f51957ba3.JPG)

**Comment by myflashlab** [comment]
you had mentioned in your environment: ```Android API Version: 7.0``` so, I actually meant the dependency ANEs. But it seems like you are targetting iOS only at the moment. Sorry for the little confusion.

Anyhow, about the ```.framework``` files. You must NOT include them inside your app. you just need to copy them to your AIR SDK at ```/lib/aot/stub``` If you can find that folder, you will see that Adobe has placed all other default iOS frameworks in there. you just need to add the firebase frameworks to that folder. Do you have problem finding that folder?

**Comment by hugojclvaz** [comment]
thanks,is running perfectly in iOS to.

I already have the open post I have just one more question

in ios versio I have this code to work perfectly when invoke the app

`NativeApplication.nativeApplication.addEventListener(InvokeEvent.INVOKE, invoked);

private function invoked(e:InvokeEvent):void
{
    if (e.reason == InvokeEventReason.NOTIFICATION)
    {
        var payload:Object = Object(e.arguments[0]);
        ...
    }
}`

but this "InvokeEventReason.NOTIFICATION" doesn t wor in Android.

Is there any way to make it work on Android?

best regards

**Comment by myflashlab** [comment]
If you are doing everthing correctly on setting up the fcm ane on Android, you must make sure you are sending the ```"click_action": "MY_INTENT"``` param from your server side.

```json
{
  "notification": 
  {
    "title": "Your Title",
    "text": "Your Text",
    "sound": "default",
    "badge": "8",
    
    "color": "#FF9900",
    
    "click_action": "MY_INTENT"
  },
  "data": 
  {
    "obj": 
    {
      "Variable1":"value1",
      "Variable2":"value2"
    }
  },
  "priority" : "high",
  "registration_ids" : 
  	[
      "cKXE9N6gZ_M:APA91bH04p4ZUFdyzqqKYUySPH3fTPYUWQGkYuT-yBGcpBcv_a",
      "cNAk9En1QfM:APA91bFWJ0YbgnsVfuJE2BxUDMmpnt6CeWQA0isZBTAxPHikxK",
      "cAMxajJxy2Y:APA91bHkJiRUhzsowbeHtFbsEAPv-ppaSgKpzeH08f12gppv9E",
      "dgNU5axXqfo:APA91bGgwGcVtDZKI81qMepH49oDUhphdwtqeyf-5TTSoktQ2AE",
      "dSCy3H0D99I:APA91bEmylmTU9HJzPej4R1SChVjd5FskD61nX2wT8p4bwdzVpg"
    ]
}

read here for more details: http://www.myflashlabs.com/send-fcm-messages-server/
```

**Comment by myflashlab** [comment]
please let us know if you need more assistance on this?

**Comment by hugojclvaz** [comment]
Hi,

No, everything is ok, thanks

2017-12-18 6:07 GMT+00:00 MyFlashLabs <notifications@github.com>:
