### ISSUE TITLE
(DB) The ChildEvents (surely under development) are essential in the Firebase Database

### ISSUE THREAD

**Issue by GV3** [myflashlab/Firebase-ANE#15]
Hi guys, 

I'm sure you already noticed this, but working with the ChildEventListeners is really the KEY to properly work with Firebase Database.

Listening only for CHANGE events is a ref is really troublesome and forces to create immense amounts of code otherwise unnecessary if the Child events would be available. 

For the others devs reading, I mean the:

`onChildAdded()`
Retrieve lists of items or listen for additions to a list of items. Suggested use with onChildChanged() and onChildRemoved() 
to monitor changes to lists.

`onChildChanged()`
Listen for changes to the items in a list. Use with onChildAdded() and onChildRemoved() to monitor changes to lists.

`onChildRemoved()`
Listen for items being removed from a list. Use with onChildAdded() and onChildChanged() to monitor changes to lists.

`onChildMoved()`
Listen for changes to the order of items in an ordered list. onChildMoved() events always follow the onChildChanged() event that caused the item's order to change (based on your current order-by method).

Do you have any idea (even if you say Xmas) when these events could be implemented?

Best regards

**Comment by myflashlab** [comment]
@GV3 We will have them ready in October. Yes, they are really helpful and we will add them

**Comment by GV3** [comment]
This feat is becoming urgent; It's incredibly troublesome to add code that tries to replicate and test the Child Events... Especially the onChildChanged()... to the point that we have to stop altogether development of essential and even basic App features until you add support for this.

Adding a Value listener change on every child of a collection with thousands of children is not an option, and reloading the whole collection to iterate through the children testing which one changed or has a child with a different value is also not acceptable.

I know you have tons to do, but these events are the CORE and fundamental to anyone developing with Firebase DB.

Please consider giving it a higher priority, October is too far away if we considering that the integration of any basic DB will be incomplete until these events are available.

Thanks

**Comment by myflashlab** [comment]
Alright, we are applying an urgent upgrade to the Database ANE. Will get back to you a.s.a.p.

**Comment by myflashlab** [comment]
@GV3 This feature is now also added. While we are writing the documentation and preparing for the next release, will you please test this demo ANE and see if everything works correctly? [firebaseDatabase-demo-V1.2.0.zip](https://github.com/myflashlab/Firebase-ANE/files/485229/firebaseDatabase-demo-V1.2.0.zip)

Please test the following 3 upgrades:

* There is a new class named ```DBServerValue``` which you can use to set server timestamp in any ```setValue``` and ```updateChildren``` methods in ```DBQuery``` or ```DBReference``` like below: [issue #10](https://github.com/myflashlab/Firebase-ANE/issues/10)
```actionscript
var refTests:DBReference = DB.getReference("branch1");
refTests.setValue(DBServerValue.TIMESTAMP);
```
* The ```endAt``` method should also work correctly. [issue #16](https://github.com/myflashlab/Firebase-ANE/issues/16)
* The ```DBEvents``` class is also updated with the following events. The **bold** events below return a new String variable ```$previousChildName``` which you can have access to them when these events happen. [issue #15](https://github.com/myflashlab/Firebase-ANE/issues/15)
  - **CHILD_ADDED**
  - **CHILD_CHANGE**
  - CHILD_REMOVED
  - **CHILD_MOVED**
  - CHILD_FAILED
  - SINGLE_VALUE_CHANGED
  - SINGLE_VALUE_CHANGE_FAILED

**Comment by GV3** [comment]
@myflashlab Great!
I'll test it today and tomorrow and report. 

You're on a DB-bug-solving spree today! ;D
Good job!

**Comment by GV3** [comment]
Hi guys, 

I just replaced the ANE in my project, and although I do get the code completion and it compiles properly, it breaks the app when I try to use the new methods.

For example:

`_query.limitToLast(100).addEventListener(DBEvents.VALUE_CHANGED, onLastHundred);`

The last line breaks the App, no error on the console.

Am I missing to add anything else than the ANE file? 
Do I need to update anything else?

**Comment by myflashlab** [comment]
I should add that it's a very good idea to add listeners to reference instances directly not to the chained ones. So you can remove the listeners later. Using them like the sample line above, will keep the listener active through the app life time which is not good.

**Comment by GV3** [comment]
> I should add that it's a very good idea to add listeners to reference instances directly not to the chained ones. 

Came to realize that while testing the beta :)

The example above is really just to test. But thank you for pointing out!

**Comment by myflashlab** [comment]
The new events are working fine in all our tests on both Android and iOS!

Maybe you are considering changes to the reference to be dispatched by these events? If so, then that's wrong. Here's what you should actually try: (remember that you are listening to the children of a certain reference not the reference itself)

First create a reference to a db location and add the listeners for example ```DBEvents.CHILD_CHANGE```
```actionscript
var refTests:DBReference = DB.getReference("branch1");
refTests.addEventListener(DBEvents.CHILD_CHANGE, onChildChanged);
```
If the ```branch1``` looks like below in your Firebase console, try to change the child values from the console and you will see the events working on the app side.

```json
"branch1" : {
    "child0" : "value",
    "child1" : "value",
    "child2" : "value",
    "child3" : "value"
  }
```

**Comment by GV3** [comment]
Yes, I was pretty sure it works on yours, I guessed you would not send me to test a DEMO if it would not work on your end :)

That's why I ask if the I only needed to replace the old ANE file with the one I downloaded abve, or if something else is needed.

This is the collection I have:

```
"room1" : {
    "chair1" : "true",
    "chair1" : "true",
    "chair2" : "true",
    "chair3" : "true"
  }
```

And this is the reference:

`var _roomReference:DBReference = DB.getReference().child('house').child('room1');`

I add the following listeners:
```
_roomReference.addEventListener(DBEvents.VALUE_CHANGED, onListChildChange);
_roomReference.addEventListener(DBEvents.SINGLE_VALUE_CHANGED, onListChildChange);
_roomReference.addEventListener(DBEvents.SINGLE_VALUE_CHANGE_FAILED, onListChildChange);
_roomReference.addEventListener(DBEvents.CHILD_ADDED, onListChildChange);
_roomReference.addEventListener(DBEvents.CHILD_CHANGE, onListChildChange);
_roomReference.addEventListener(DBEvents.CHILD_MOVED, onListChildChange);
_roomReference.addEventListener(DBEvents.CHILD_FAILED, onListChildChange);
_roomReference.addEventListener(DBEvents.CHILD_REMOVED, onListChildChange);

```

The handler successfully triggers once for the DBEvents.VALUE_CHANGED and retrieves the expected object as a value and the name of the room as a key:

```
key: "room1" 
value: {
    "chair1" : "true",
    "chair1" : "true",
    "chair2" : "true",
    "chair3" : "true"
  }
```

Then I go to the Firebase console and change "chair1" to false, or add a "chair4" or even create a chair1.niceChair: true, delete any chair, all chairs, and even the room, and the only event that keeps dispatching correctly is DBEvents.VALUE_CHANGED

I'm guessing that my Project is somehow still using the old version even if I'm getting the code completion of the new ANE, that's why I ask the only step I needed to do was to swipe the "firebaseDatabase.ane" file, or if more was needed for the new version to work properly.

Because I just changed that one file, and that's it!

Hope you can help me get this working

**Comment by myflashlab** [comment]
hmm, that's totally wired. The test version I sent to you should have worked with just replacing the ANE. Anyhow, please download V1.2.0 from your myflashlabs account and replace the ANEs while you are also updating your dependency ANEs for Android and the .framework files for the iOS thing. *Information on [this page](https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md) should tell you what dependencies/frameworks are required for each child ANE.

This way we can be sure that we are both using the latest version. After you updated everything, run your app and tell us how things went. Thanks. 

And make sure to generate a new firebaseCore.ane using the new software for the core. Everything should be V1.2.0 / iOS frameworks V3.6.0 / Android dependencies V9.6.1

**Comment by GV3** [comment]
All Events are working fine and dandy!

Used the new version of the Firebase ANE's, built the new CORE ANE and replaced the iOS framework files with the ones from the link of the new version.

Thanks, guys! :) 👍
