### ISSUE TITLE
Auth with Facebook

### ISSUE THREAD

**Issue by 4malik** [myflashlab/Firebase-ANE#150]
I signed by email. After that i tried to sign by facebook.
With Facebook Ane  I got user data, got token.
With that token I tried to sign in firebase with 
```
var authProvider:AuthProvider = new AuthProvider();
authProvider.setFacebookAuthProvider(FB.auth.token);
Auth.signIn(authProvider.getCredential());
```
But got an error
```
result = 4
msg = "An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address."
```
Yes i was logged with same email which is used in facebook.
Cant understand what to do in such situations? By the way i tried to log out first, but got the same error.

After removing email user from firebase console i successfully logged on firebase.
Then I tried to log with email. But i couldn't. Im always getting errors with
```
result = 1
msg = "The password is invalid or the user does not have a password."
```
But password is correct. I tried to enter it 5 times.

**Comment by myflashlab** [comment]
you are probably looking for the [linkWithCredential](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/firebase/auth/FirebaseUser.html#linkWithCredential()) method. Read the documentation there and that might help you with that.

**Comment by myflashlab** [comment]
please let us know if the problem is fixed? or you have more questions?

**Comment by 4malik** [comment]
I will try it. But I think its already bad solution. There are some situations when that is bad decision.
I will try these situations and describe you my results.
