### ISSUE TITLE
Firebase ANE version is newer than the Inspector!

### ISSUE THREAD

**Issue by Igazine** [myflashlab/Firebase-ANE#151]
I've just updated the core ANE to 5.1.1, now Inspector.check() produces errors for all the included Firebase extensions:

> Inspector.lastError Firebase ANE version is newer than the Inspector! You need to update the Inspector ANE. It's free to download! https://github.com/myflashlab/ANE-Inspector-Tool

> Inspector.lastError Crash ANE version is newer than the Inspector! You need to update the Inspector ANE. It's free to download! https://github.com/myflashlab/ANE-Inspector-Tool

Notes: 

*  `Inspector.check( ane_class, true, false )`
Produces error only for the core firebase, while

*  `Inspector.check( ane_class, true, true )`
produces the error for every single included extension (remoteconfig, crash, analytics)

*  Inspector.check() returns false, so my code treats Firebase as not initialised

*  Everything is working fine with 5.1.0.

*  Inspector ANE is 19 days old (latest on GitHub)

## Known Workarounds ##
Rolling back to 5.1.0 works fine

**Comment by myflashlab** [comment]
please update to [V1.0.26](https://github.com/myflashlab/ANE-Inspector-Tool). And thanks for pointing that out.
