### ISSUE TITLE
LinkWithFacebook receives JSONException and eror doesnt return to AIR

### ISSUE THREAD

**Issue by tfnsyl** [myflashlab/Firebase-ANE#154]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Android API Version: 5.0
* iOS Version: 9
* AIR SDK Version: 26

## Problem Description ##

When trying to link an already linked facebook user, Firebase returns a problem as it should be, and this could be seen in OverrideAir logs, But the result doesnt return to the application. Because of never giving error, we can't proceed on the application with linkWithResult.

You can see result see the logs below.

```actionscript
[OverrideAir] ------------------
[OverrideAir] $ane = FirebaseAuth
[OverrideAir] $class = AirCommand
[OverrideAir] $msg = linkWithCredential started...
[OverrideAir] ------------------
[OverrideAir] ------------------
[OverrideAir] $ane = FirebaseAuth
[OverrideAir] $class = AirCommand
[OverrideAir] $msg = linkWithCredential json error = org.json.JSONException: Value EAA... of type java.lang.String cannot be converted to JSONObject
[OverrideAir] ------------------
[OverrideAir] ------------------
```
* Copy your Actionscript code.
```actionscript
		FirebaseUser.listener.addEventListener(FirebaseUserEvents.LINK_WITH_RESULT, onLink);
		FirebaseUser.linkWithCredential(accessToken);

		function onLink(e:FirebaseUserEvents):void
		{
			FirebaseUser.listener.removeEventListener(FirebaseUserEvents.LINK_WITH_RESULT, onLink);
			trace("onLink result=" + e.result, "     msg=" + e.msg);
		}
```

## Steps to Reproduce ##
Have a facebook account logged to app. Login to application as anonymous or with an email id. Try to link the already linked facebook account. Problem will show.

## Known Workarounds ##
Facebook account ids may be saved to firebase and when linking account, ids can be checked if already linked.

**Comment by myflashlab** [comment]
Do not attempt to send facebook accesstoken to the ```linkkWithCredential``` method. read [here for more information](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/firebase/auth/FirebaseUser.html#linkWithCredential())

You must first create a AuthProvider instance, ```var authProvider:AuthProvider = new AuthProvider();``` and then use the [setFacebookAuthProvider](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/firebase/auth/AuthProvider.html#setFacebookAuthProvider()) method to set the facebook accesstoken.

Finally use  ```authProvider.getCredential()``` method to pass the credential to linkWithCredential.

**You need to be a club member to be able to use that method.**
