### ISSUE TITLE
deeplink facebook

### ISSUE THREAD

**Issue by vietpv** [myflashlab/Firebase-ANE#156]
@myflashlab  : please tell me  how to get deeplink from facebook, i cant fint function in example, thanks

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
