### ISSUE TITLE
Firebase ANE interferes with Milkman's Go Viral ANE

### ISSUE THREAD

**Issue by joonfromla** [myflashlab/Firebase-ANE#163]
I have successfully implemented the Firebase Core ANE in an app, and I have successfully implemented Milkman's Go Viral ANE in a separate app.  For people not familiar, the Go Viral ANE allows an air app to call Facebook's authentication API along with other social media apis.

However, when I try to initialize your Firebase Core and the Go Viral ANEs in the AS3 Document class constructor, I encounter a variety of errors.

For example, after my app uses Go Viral to launch the Facebook app for authentication, I enter my username/password successfully, then I return to my app, instead of receiving a successful
GVFacebookEvent.FB_LOGGED_IN event as I would expect, I am receiving a GVFacebookEvent.FB_LOGIN_CANCELED event.

This only happens when I include the Firebase Core ANEs in the app and the Go Viral ANE simultaneously.  I have already tried to initialize both ANEs in various orders, but I still receive errors.  I have already reached out to Milkman Plugins, and they say that the problem is most likely caused by the Firebase Core ANE intercepting all native iOS callback events and not passing them to other extensions.

Base on my understanding of the functionality of your OverrideAir.ane, that sounds like what is happening.  Do you have any suggested workarounds?

By the way, the problem only occurs on iOS, Android appears to work fine so far.

## Environment ##
* iOS Version: 11
* AIR SDK Version:26

**Comment by myflashlab** [comment]
This is a conflict between ANEs and your findings are all valid. The best we could do when it comes to such conflicts between ANEs has been to invite other ANE developers to use the OverrideANE. We have written a very detailed explanation on how any ANE developer can implement that. https://www.myflashlabs.com/efficiently-override-native-methods-air-native-extensions/

**Comment by joonfromla** [comment]
Ok, thanks for the reply.  It's too bad I have to find this out the hard way.
