### ISSUE TITLE
Conflicting AuthEvents Game Services and Firebase Authentication

### ISSUE THREAD

**Issue by jennycxu** [myflashlab/Firebase-ANE#165]
It looks like com.myflashlab.air.extensions.dependency.firebase.auth and com.myflashlab.air.extensions.dependency.googlePlayServices.auth both have AuthEvents and importing both will cause conflicts in AuthEvents events and cause compile time errors. Is there a way to resolve this easily or a way to specify which AuthEvent I want to reference (either Game Services or Firebase).  Thanks!

**Comment by myflashlab** [comment]
in AS3, in such cases, you can easily use the full class name in your code instead of importing them. This way there will be no conflict. for example instead of saying:

```actionscript
new ClassName();
```
you should say:
```actionscript
new com.site.package.ClassName();
```
