### ISSUE TITLE
DBEvents not firing

### ISSUE THREAD

**Issue by fyrcyning** [myflashlab/Firebase-ANE#166]
DBEvents not firing.  When I run the app for the first time on a device the events fire and everything behaves as it should.  The next time I run the app the DBEvents fail to fire at all.

Totally confused, has now happened on three devices Samsung S6, S7 and S8.  Have tried everything I can think of with no success.

**Comment by fyrcyning** [comment]
More info....
AIR Version 27
Latest ANE's

<manifest android:installLocation="auto">
	
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<permission android:name="air.nz.emres.OnCall.permission.C2D_MESSAGE" android:protectionLevel="signature" />
	<uses-permission android:name="air.nz.emres.OnCall.permission.C2D_MESSAGE" />
	
	<application>
		
		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				
				
				<data android:scheme="air.nz.emres.OnCall" />
			</intent-filter>
		</activity>
		
		<provider
			android:name="com.google.firebase.provider.FirebaseInitProvider"
			android:authorities="air.nz.emres.OnCall.firebaseinitprovider"
			android:exported="false"
			android:initOrder="100" />
			
		<service
			android:name="com.myflashlab.firebase.core.MyFirebaseInstanceIdService"
			android:exported="true">
			<intent-filter>
				<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
			</intent-filter>
		</service>
		
		<meta-data 
			android:name="com.google.android.gms.version" 
			android:value="@integer/google_play_services_version" />
		
		<receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="air.nz.emres.OnCall" />
            </intent-filter>
        </receiver>
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
		
		<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>
		
		<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
					<intent-filter>
						<action android:name="com.google.firebase.MESSAGING_EVENT"/>
					</intent-filter>
				</service>
				<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
					<intent-filter>
						<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
					</intent-filter>
				</service>
				<activity 
					android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
					android:theme="@style/Theme.Transparent"
					android:exported="false"
					android:noHistory="true"
					android:clearTaskOnLaunch="true"
					android:hardwareAccelerated="false"
					android:stateNotNeeded="true">
					<intent-filter>
						<action android:name="MY_INTENT" />
						<category android:name="android.intent.category.DEFAULT" />
					</intent-filter>
				</activity>
	</application>
</manifest>

**Extensions in manafest:**

  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.database</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.database.connection</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.realtimeDB</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
  </extensions>
</application>

**AS Code:**

**Main Class:**

public function OnCall()
{
	this.stage.scaleMode = StageScaleMode.NO_SCALE;
	this.stage.align = StageAlign.TOP_LEFT;
	
	// Initialise Firebase Core
	trace("Firebase Initialised: " + Firebase.init());
	
	// Initialise Login Class
	login.init(stage.stageWidth, stage.stageHeight)
	login.addEventListener("SUCCESS", onLogin);
	
	// Initialise Database Class
	Database.init();
	
	// Initialise Cloud Messaging
	CloudMessaging.init();
	
	goToLogin();
}

private function onLogin(event:Event):void
{
	goToMenu();
	Database.getData();
	CloudMessaging.getToken();
}

**Database Class:**

public static function init():void
{
	DB.init();
        getUserData();	
}

public static function getUserData():void
{
	trace("Database: Retrieving User Data for UID " + FirebaseUser.userId);
	userRef = DB.getReference("users").child(FirebaseUser.userId);
	userRef.addEventListener(DBEvents.VALUE_CHANGED, onUserChanged);
	userRef.addEventListener(DBEvents.VALUE_CHANGE_FAILED, onUserFailed);
}

private static function onUserChanged(event:DBEvents):void
{
        trace("Database: User Data Changed");
        if (e.dataSnapshot.exists)
        {
                user = event.dataSnapshot.value;
	{
}

private static function onUserFailed(event:DBEvents):void
{
	trace("User Ref Failed:" + event.msg);
}

When I run for the first time on a device it works perfectly and returns the user data, the second and subsequent times it gets as far as tracing out 

_Database: Retrieving User Data for UID + FirebaseUser.userId_

After that no further trace statements are output leading me to believe that it never fires the DBEvents to trigger the onUserChanged function or the onUserFailed function.

I used much of this same code in a previous development and it worked fine, it appears it is only since the change to AIR 27 and with the latest android OS updates that it became a problem.  In light of that I downloaded the latest ANE's and remade the core ANE with a fresh download of the google-services.json file but still not working. 

Auth and FCM work as they should, problem only seems to be with Realtime Database.  Any ideas would be appreciated, I'm hopeful that it is something simple that I have overlooked.

**Comment by myflashlab** [comment]
is this happening on iOS or Android or both? Do you mean if you roll back to AIR 26, everything would work normally?

**Comment by fyrcyning** [comment]
Have only tested on Android at this stage, rollback to AIR25 and 26 doesnt help but after digging to the bottom of my crappy old device box and pulling out an old tablet with Android API version 19 still installed it all works fine.  

Possibly a problem with latest update to Android OS as all other devices tried are kept up to date with latest release.

**Comment by myflashlab** [comment]
we will be releasing new updates to all our ANEs soon... please stay alert.

**Comment by myflashlab** [comment]
Update: Although we couldn't duplicate this problem, we tested the new version we're working on (V6.0.0) and it's all working fine. We will be releasing Firebase collection ANEs V6.0.0 soon. The new **Firestore** ANE will be also available with this release.

**Comment by fyrcyning** [comment]
Have downloaded the V6.0 ANE's and created a new firebaseCore.ane using AneMaker v6.0 with a fresh download of the common dependencies.

Unfortunately I am still having the exact same problem, functions perfectly fine on Samsung Tab 3 running older version of android SDK but DBEvents don't seem to fire on Samsung S6, S7 or S8 running latest Android Version.

Have confirmed version -
trace("Version: " + Firebase.VERSION) 
Result = "Version: 6.0.0"

Where to from here???

**Comment by myflashlab** [comment]
This is weird. We can't duplicate this and no one else seems to have a similar problem. This indicates that something might have gone wrong in your project. Let me take a wild guess. Would it be possible that your variable ```userRef``` is garbage collected? maybe try to make it a class variable rather than a function variable and see what happens.

**Comment by fyrcyning** [comment]
Already attempted that one and still no luck.

I have also tried:
- Creating a new fla and 'main' class to remove any possible complications resulting from other code.
- Changing Firebase project database rules to public
- Using a different firebase project

Still I am having the same problem.  The code I am working with at the moment to try and debug this is as follows.

**Manifest**

```xml
  <android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
	
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
	
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<permission android:name="air.nz.emres.airops.permission.C2D_MESSAGE" android:protectionLevel="signature" />
	<uses-permission android:name="air.nz.emres.airops.permission.C2D_MESSAGE" />
	
	<application>
		
		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />

				<data android:scheme="air.nz.emres.airops" />
			</intent-filter>
		</activity>
		
		<provider
			android:name="com.google.firebase.provider.FirebaseInitProvider"
			android:authorities="air.nz.emres.airops.firebaseinitprovider"
			android:exported="false"
			android:initOrder="100" />
			
		<service
			android:name="com.myflashlab.firebase.core.MyFirebaseInstanceIdService"
			android:exported="true">
			<intent-filter>
				<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
			</intent-filter>
		</service>
		
		<meta-data 
			android:name="com.google.android.gms.version" 
			android:value="@integer/google_play_services_version" />
		
		<receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="air.nz.emres.airops" />
            </intent-filter>
        </receiver>
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
		
		<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>
		
	</application>
</manifest>]]>
</manifestAdditions>
  </android>

  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.database</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.database.connection</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.realtimeDB</extensionID>
  </extensions>
```

**Main Class**

```actionscript
package
{
	import flash.display.MovieClip;
	import com.myflashlab.air.extensions.firebase.core.Firebase;
	import com.myflashlab.air.extensions.firebase.db.*;

	public class AirOps extends MovieClip
	{
	
		public function AirOps()
		{
			trace("Initialise Firebase");
			Firebase.init();
			trace("Initialise Database");
			DB.init();
			trace("Instantiate Reference");
			var ref:DBReference = DB.getReference();
			trace("Add Listeners");
			ref.addEventListener(DBEvents.VALUE_CHANGED, onChanged);
			ref.addEventListener(DBEvents.VALUE_CHANGE_FAILED, onFailed);
		}
		
		private function onChanged(event:DBEvents):void
		{
			trace("CHANGED");
			if(event.dataSnapshot.exists)
			{
				trace(event.dataSnapshot.value);
			}
		}
		
		private function onFailed(event:DBEvents):void
		{
			trace("FAILED");
			trace(event.msg);
		}
		

	}

}

Trace Output

Waiting for Player to connect...
[SWF] AirOps.swf - 1137 bytes after decompression
Initialise Firebase
Initialise Database
Instantiate Reference
Add Listeners

**Comment by fyrcyning** [comment]
Resolved now. Using ANE Lab seems to have fixed the problem, whatever it was.
