### ISSUE TITLE
[Fault] exception, information=Error: Grrr after Auth.signIn(authProvider.getCredential()

### ISSUE THREAD

**Issue by denisgl777** [myflashlab/Firebase-ANE#170]
Firebase V5.1.1
* iOS Version: 11
```
      var authProvider:AuthProvider = new AuthProvider();
	authProvider.setPhoneAuthProvider(verificationId, smsInput.text);
	Auth.signIn(authProvider.getCredential());
```
all necessary libraries are connected and working. Аnonymous registration also works(Auth.signIn(null)) Sms code comes. And then I get this error

[Fault] exception, information=Error: Grrr! This feature is only available to MyFlashLabs Club members. If you haven't checked out our Club yet, it's time to do so. read here: http://www.myflashlabs.com/product/myflashlabs-club-membership/

**Comment by myflashlab** [comment]
Are you a club member and see this? Anyhow, please update to the latest version of the ANEs which is V6.0.0

Besides, if you are not a club member, this limitation is normal to be available as described in the [product page](https://www.myflashlabs.com/product/authentication-firebase-air-native-extension/) under "**Pro features available to club members only**"

I'm closing the issue as Github tickets are supposed to be related to tech issues only. If you have any more question, please feel free to let us know through https://www.myflashlabs.com/contact/
