### ISSUE TITLE
Database events child_added and child_change after removing

### ISSUE THREAD

**Issue by 4malik** [myflashlab/Firebase-ANE#173]
Hi.
I removed all data i pushed and changed in database. I removed user record from Authentication and removed app. 
Then installed again and signed up with new ID. But I still got child_added and child_change events from old user ID.

Any ideas and advices?

**Comment by myflashlab** [comment]
Are you seeing the same user when tracing the logged in user information? https://github.com/myflashlab/Firebase-ANE/wiki/D.3-Manage-Users

**Comment by 4malik** [comment]
Yes, Firebase IDs by FirebaseUser were different.
Today i cant reproduce that error.
Please don't close this issue. I'll try to reproduce it in the coming days

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
