### ISSUE TITLE
 Firebase authentication with Google Id

### ISSUE THREAD

**Issue by SaleemEM** [myflashlab/Firebase-ANE#174]
Hi Team,

Could you please share a sample AS3 code to enable app users to login using Google Id  in the App, we have done using Facebook ane.
  
I found a package "GoogleSignIn " in AsDoc but I don't know which ANE contains this package.

GoogleSignIn | com.myflashlab.air.extensions.googleSignin |  
-- | -- | --
  | GoogleSignInEvents | com.myflashlab.air.extensions.googleSignin
  | GoogleUser | com.myflashlab.air.extensions.googleSignin
  | GoogleUserAuth | com.myflashlab.air.extensions.googleSignin
  | GoogleUserProfile | com.myflashlab.air.extensions.googleSignin

I am trying to enable user to login using Google Id 

function signIn(): void {
	log("Entered into signIn");
	try {
		var authProvider: AuthProvider = new AuthProvider();
		authProvider.setGoogleAuthProvider(             ????????????           /*here we need help, which ANE will be utilized*/ );
		Auth.listener.addEventListener(AuthEvents.SIGN_IN_RESULT, onSignInResult);
		Auth.signIn(authProvider.getCredential());
	} catch (err: Error) {
		log("Exception into signIn:" + err.message);
	}
}

**Comment by 4malik** [comment]
As I know Myflashlabs still doesn't have Google SIgnIn ANE. So we have to use other providers to enable this opportunity.

**Comment by myflashlab** [comment]
GoogleSignin ANE will be ready in a couple of days. We've been working on it and It's being developed right now. cheers

**Comment by myflashlab** [comment]
GoogleSignIn is now available for individual purchases, in the club package, and also through the ANELAB channel. If you are using ANELAB, make sure to update to at least **V1.0.1**
