### ISSUE TITLE
Auth link / unlink error

### ISSUE THREAD

**Issue by 4malik** [myflashlab/Firebase-ANE#175]
Hi.
I have next 2 errors

**error 1**
I logged in by phone. 
![1](https://user-images.githubusercontent.com/30479942/35276949-92965c3c-005e-11e8-8846-505d8ab6837b.PNG)

Than linked 
![2](https://user-images.githubusercontent.com/30479942/35276964-a06b61fe-005e-11e8-9c08-b5062476fab2.PNG)
with facebook. 

Than unlinked facebook
![3](https://user-images.githubusercontent.com/30479942/35276970-a50c606e-005e-11e8-945c-26606a18dbaa.PNG)

Than i Signed Out and tried to Sing In with the same facebook acc. But got an error
![4](https://user-images.githubusercontent.com/30479942/35277022-c8659fc6-005e-11e8-9eb9-cb83a077df43.png)

Than I saw on auth record in Firebase console my email from facebook record and i didn't link with email. So i tried to sign in with that email and my password but got next error
![5](https://user-images.githubusercontent.com/30479942/35277285-aec3998c-005f-11e8-9447-e64199d61e3c.png)

The question is why my email appeared in firebase console under phone, and why i cant signIn with Facebook and that email. And what i have to do?

I tried unlink email
![6](https://user-images.githubusercontent.com/30479942/35279448-8b822a40-0066-11e8-9c77-20e6c4ceb20c.png)
But email didn't linked

I tried to call _FirebaseUser.updateEmail("");_ - no result.

**error 2**
step1. I signed in with phone.
step2. I signed out. 
step3. I signed up with email.
step4.I tried to link account with phone from step1 (got pin code for phone) .  

In tracelog I got:
_linkWithCredential started..._
And after a long time in addition I got
_FirebaseAuth(AirCommand) onCodeAutoRetrievalTimeOut_
But no error, no message about phone is used, etc... The same situation with facebook instead of email signin.

What it can be? And how to link 2 accounts in such situation? 
Do I have to use FirebaseUser.deleteUser() and this is the only one way to link user. How to be with unlink than? I can't sign in with unlinked account

**Comment by myflashlab** [comment]
hmm, probably when you linked with facebook, the email address used with your facebook account has been saved on Firebase console. Anyway, I really think this question must be asked on the official Firebase repository. They should be able to help you better in such scenarios.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
