### ISSUE TITLE
"This is a DEMO" Dialog shows, if package name is like "air.air.com.site.app"

### ISSUE THREAD

**Issue by Soshaapp** [myflashlab/Firebase-ANE#177]
## Environment ##
* Android API Version: 5.1.1
* AIR SDK Version: 27

## Problem Description ##
I'm using the latest ANE LAB and Firebase ANEs.
I'm logged into ANE LAB.
I have iOS and Android project.
When starting iOS, everything is fine, but on Android I get:

"This is a DEMO You are using the demo license of MyFlashLabs.com Products"

In the Manifest I have:
`<meta-data android:name="com.myflashlabs.aneLab.id" android:value="[Same ID as on iOS here]"/>`

Please advice, I can't get rid of the Dialog :(

Thanx!  :)

**Comment by myflashlab** [comment]
hmm, this is a wild guess but does your Android package name start with **air.** or you are omitting that? in either case, it should be fine. but I'm trying to understand what could be the problem. :thinking:

**Comment by Soshaapp** [comment]
I have air.***.***.*** as package name, why would that be a possible issue?

**Comment by myflashlab** [comment]
It shouldn't matter. we have included support for those AIR android apps that manually omit the initial "air." I thought maybe that could be a problem. but it shouldn't.

Anyway, I don't know what to suggest, please provide more information.

**Comment by Soshaapp** [comment]
Thanks for the fast reply :)

What exactly causes the DEMO popup to appear, I guess it's the:

`<key>com.myflashlabs.aneLab.id</key><string>****</string>`

right, or is there something else, that the ANE is searching for that == false?

**Comment by Soshaapp** [comment]
Ups, that was for iOS, Android is like this:

`<meta-data android:name="com.myflashlabs.aneLab.id" android:value="***"/>`

**Comment by myflashlab** [comment]
That's just all! if the value is available and correct, the dialog should not show! It's working fine with all other users and you are the only one seeing this problem. we can't even duplicate it. Try to give us more information, like posting your manifest .xml file. Maybe we can find some reasons for that.

**Comment by Soshaapp** [comment]
Manifest:

`<?xml version="1.0" encoding="utf-8" ?> 
<application xmlns="http://ns.adobe.com/air/application/27.0">
  <id>air.com.socialsosha.sosha</id>
  <filename>SoshaAndroid</filename>
  <name>SoshaAndroid</name>
  <versionNumber>1.7.0</versionNumber>
  <description>Sosha, help friends share and discover great experiences.</description>
  <copyright>Sosha Aps</copyright>
  <initialWindow>
    <content>[This value will be overwritten by Flash Builder in the output app.xml]</content>
    <title>Sosha</title>
    <renderMode>direct</renderMode>
    <depthAndStencil>true</depthAndStencil>
    <autoOrients>false</autoOrients>
    <fullScreen>false</fullScreen>
    <visible>true</visible>
    <softKeyboardBehavior>none</softKeyboardBehavior>
  </initialWindow>
  <icon>
    <image29x29>icons/icon29.png</image29x29>
    <image40x40>icons/icon40.png</image40x40>
    <image50x50>icons/icon50.png</image50x50>
    <image57x57>icons/icon57.png</image57x57>
    <image58x58>icons/icon58.png</image58x58>
    <image60x60>icons/icon60.png</image60x60>
    <image75x75>icons/icon75.png</image75x75>
    <image76x76>icons/icon76.png</image76x76>
    <image80x80>icons/icon80.png</image80x80>
    <image87x87>icons/icon87.png</image87x87>
    <image100x100>icons/icon100.png</image100x100>
    <image114x114>icons/icon114.png</image114x114>
    <image120x120>icons/icon120.png</image120x120>
    <image144x144>icons/icon144.png</image144x144>
    <image152x152>icons/icon152.png</image152x152>
    <image167x167>icons/icon167.png</image167x167>
    <image180x180>icons/icon180.png</image180x180>
    <image512x512>icons/icon512.png</image512x512>
    <image1024x1024>icons/icon1024.png</image1024x1024>
  </icon>
  <android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto" >
  <uses-sdk android:minSdkVersion="15" android:targetSdkVersion="23"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
  <uses-permission android:name="android.permission.WAKE_LOCK"/>
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
  <uses-permission android:name="air.air.com.socialsosha.sosha.permission.C2D_MESSAGE"/>
  <application>
    <activity>
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <data android:scheme="air.com.socialsosha.sosha"/>
        <data android:scheme="http" android:host="www.soshasocial.com"/>
        <data android:scheme="https" android:host="www.soshasocial.com"/>
      </intent-filter>
    </activity>
    <provider android:name="com.google.firebase.provider.FirebaseInitProvider" android:authorities="air.air.com.socialsosha.sosha.firebaseinitprovider" android:exported="false" android:initOrder="100"/>
    <service android:name="com.myflashlab.firebase.core.MyFirebaseInstanceIdService" android:exported="true">
      <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
      </intent-filter>
    </service>
    <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
        <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>
        <category android:name="air.air.com.socialsosha.sosha"/>
      </intent-filter>
    </receiver>
    <service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
      <intent-filter android:priority="-500">
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
      </intent-filter>
    </service>
    <activity android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:exported="false"/>
    <receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true" android:exported="false"/>
    <receiver android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" android:permission="android.permission.INSTALL_PACKAGES" android:enabled="true">
      <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER"/>
      </intent-filter>
    </receiver>
    <service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false"/>
    <service android:name="com.google.android.gms.measurement.AppMeasurementJobService" android:permission="android.permission.BIND_JOB_SERVICE" android:enabled="true" android:exported="false"/>
    <service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
      </intent-filter>
    </service>
    <service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
      <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
      </intent-filter>
    </service>
    <activity android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" android:theme="@style/Theme.Transparent" android:exported="false" android:noHistory="true" android:clearTaskOnLaunch="true" android:hardwareAccelerated="false" android:stateNotNeeded="true">
      <intent-filter>
        <action android:name="MY_INTENT"/>
        <category android:name="android.intent.category.DEFAULT"/>
      </intent-filter>
    </activity>
    <meta-data android:name="com.myflashlabs.aneLab.id" android:value="***"/>
  </application>
  <uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
</manifest>]]></manifestAdditions>
  </android>
  <extensions>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.analytics</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics.impl</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.crash</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.crash</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.realtimeDB</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.database</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.database.connection</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.dynamicLinks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.dynamicLinks</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
    <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.storage</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.storage</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.storage.common</extensionID>
  </extensions>
</application>`

**Comment by Soshaapp** [comment]
Hope you can spot something there! :)

**Comment by myflashlab** [comment]
Which version of ```permissionCheck``` are you using? have you installed it through ANELAB?

**Comment by myflashlab** [comment]
Ok, it did ring the bell! I've added this to our [to-do list](https://github.com/myflashlab/ANE-LAB/projects/1#card-7596819).

The problem is that you are starting your app package name with "air." and AIR ads another "air." to it on the Android side. In result, the final package name would be something like: ```air.air.com.site.app``` And that's the problem.

As a quick workaround, try to omit the initial "air." and build your project again. Of course you would need to create a new Firebase project with the new package name.

Thanks for bringing this to our attention. we will be fixing this in future releases.

**Comment by Soshaapp** [comment]
That's awesome I could help with this problem, now I know what to do to fix the Dialog showing up :)

Thanks guys, just awesome work you've done to help us all use Firebase! :)

**Comment by myflashlab** [comment]
Ok, this is fixed now. The overrideAIR ANE is now updated to V5.1.1 Simply run ANELAB, go to updates window and make sure everything is updated. Then open your project and click on "re-setup" of one of the ANEs. Considering that the overrideAIR ANE is a dependnecy for ALL our ANEs, it will be automatically updated to the latest version. Now, run your project and it should be fine.

**Notice:** You cannot update a dependency ANE through ANELAB project page. This must happen automatically when you re-setup other ANEs.
