### ISSUE TITLE
Error compiling Android App - Conflict between different ANE'S

### ISSUE THREAD

**Issue by bilicio** [myflashlab/Firebase-ANE#178]
## Environment ##
* Android API Version: 2.5
* iOS Version: 11
* AIR SDK Version: 27

## Problem Description ##

Hey guys,

Im using lot of your extensions however, myflashlabs wont have a native dialogs extension, so i needed use the distriqt extension.  the problem is that is a conflict between a function founded in both extension and even i try to remove one of the android support extension it still gives me the same error plus another one. the function im talking about is:

java.lang.IllegalArgumentException: already added: Lcom/adobe/air/ActivityResultCallback;

The problem occurs only on android phone, IOS is fine.

I think this function is on distriqt core and myflashlabs android.

is that it?

it give's you any hint?

thank you!!

```xml
<my><extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics.impl</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.database</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.database.connection</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.storage</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.storage.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.location</extensionID>
    
    <extensionID>com.sbhave.nativeExtensions.zbar</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.analytics</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.realtimeDB</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.storage</extensionID>

<extensionID>com.distriqt.Dialog</extensionID>
<extensionID>com.distriqt.Core</extensionID>
<extensionID>com.distriqt.androidsupport.V4</extensionID>

<extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>
<extensionID>com.distriqt.androidsupport.CardViewV7</extensionID>
<extensionID>com.distriqt.androidsupport.CustomTabs</extensionID></my>
```

## Steps to Reproduce ##
Tell us how this issue can be reproduced.

## Known Workarounds ##
Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

**Comment by myflashlab** [comment]
The problem starts in ```com.myflashlab.air.extensions.dependency.overrideAir```. read this thread for more information: https://forum.starling-framework.org/topic/using-myflashlabs-firebase-ane-together-with-milkmans-go-viral-ane

Nonetheless, we may consider developing a native dialog ANE. let us know in more details about what are your requirements and maybe we can just develop that ANE. Dialogs are easy :)
