### ISSUE TITLE
SWC for firebaseCore.ane

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/Firebase-ANE#180]
I created firebaseCore.ane using AneMaker.air.
I cannot find SWC libraries as for other anes. Those are useful for IDEs when developing.
Is it stored anywhere?
Thank you

**Comment by myflashlab** [comment]
SWC files used to be helpful in old times. What good usage have you found with them? Considering that the core ANE is being generated based on your data I'm not sure how you can have the swc file but I'll ask my colleagues if it is really necessary for you.

**Comment by PippoApps** [comment]
Just for compile time checks and ease of development in IDE. Not really necessary, just asked if I had missed it somewhere. Thank you :)
