### ISSUE TITLE
Wrong example in wiki

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/Firebase-ANE#186]
Hi,
in DynamicLinks wiki there is a mistake in example:

"Before you can gerenare a dynamic link using the ANE, you need to set projectID and webApiKey."
if (isConfigFound)
{
	Firebase.getConfig().projectID = "fir-proj";
	Firebase.getConfig().webApiKey = "AIzbSyDvWwo5ATJ3pPl3YG1MHlQsikuodVzdehQ";
}

While in Example AS it only sets webApiKey. Infact, setting projectID it triggers a "059: Property is read-only." error.

Just to let you know.

**Comment by myflashlab** [comment]
Noted and fixed. Thanks for pointing that out.
https://github.com/myflashlab/Firebase-ANE/wiki/I.3-Create-Dynamic-Links#using-the-ane-built-in-deeplink-generator
