### ISSUE TITLE
Realtime Database child data problem on Android 4.x

### ISSUE THREAD

**Issue by arcreature7** [myflashlab/Firebase-ANE#188]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Firebase Core Version: V6.0.1
* Firebase Realtime DB Version: V6.0.0
* AIR SDK Version: 28

## Problem Description ##
Hello.
I have a problem with the realtime database.

The first issue was a crash issue with Android 4.x.
I solved this problem by referring to the closed issue.

* I modified my application.xml to look like this:
```xml
<application android:name="android.support.multidex.MultiDexApplication" android:hardwareAccelerated="true" android:allowBackup="true">
```
After that, crash was resolved, but another problem occurred.
If server data is loaded, the child data is loaded as a String.
In android 5.0 and above, the child data is normally loaded as Object type, but in 4.x the child data is loaded as String.

ex : Firebase database structure
fb/users/profile : { id:1234, name:"UserName", gender:"Male" }
fb/users/ownedItems : { item1:0, item2:5, item3:10 }

* Assuming this structure in database, the data is loaded in the following form.
```actionscript
var userDbRef:DBReference = DB.getReference("fb/users/");
userDbRef.addEventListener(DBEvents.VALUE_CHANGED, onValueChangedUserData);

function onValueChangedUserData(e:DBEvents):void
{
   if (e.dataSnapshot.exists == true)
   {
      // [Child data type is wrong]
      // e.dataSnapshot.value.profile : "{ id=1234, name=UserName, gender=Male }" (String)
      // e.dataSnapshot.value.ownedItems : "{ item1=0, item2=5, item3=10 }" (String)
   }
}
```
Because the child data is loaded with this String, parsing is not possible with the JSON.parse () Method.
Why is this happening? How can I solve it?
Thank you for your efforts.

## Steps to Reproduce ##
In Android 4.x, if you load data with an Object type of child data.

**Comment by myflashlab** [comment]
Are you saying that the very same application returns value as String in Android 4.* and Object in other Android versions?! Are you sure you have not saved those values as String in the first place? 

to confirm this, you should check the database from the Firebase console and see if the saved values are Strings or objects.

**Comment by arcreature7** [comment]
Yes. This is a problem with the same application and the data type is Object.
When I check in Android 5.x or later, the data is loaded into Object type.
However, when loading data from version 4.0.4, it will be loaded as a String.

e.dataSnapshot.value.profile = **"{ id = 1234, name = UserName, gender = Male }"** (String type)
If try to load only the child object profile with this problem, it will load normally.

ex)
Load -> var userDbRef: DBReference = DB.getReference ("fb / users / profile");
Result -> e.dataSnapshot.value = **{ id:1234, name:"UserName", gender:"Male" }**; (Object type)

As a result of the test, if the child data is Object it is loaded as a String and conversion to JSON.parse () is not possible.

**Comment by myflashlab** [comment]
This seems to be something happening in this specific Android Version. Lets do some tests to see what is happening there. Please run the [Override debugger](https://www.myflashlabs.com/debug-air-native-extensions/) and look at your AIR TRACE logs and send me everything that starts from ```convertDataSnapshotToJson BEGIN``` to ```convertDataSnapshotToJson END```

Replace your ANE with this test version: [firebaseDatabase.ane.zip](https://github.com/myflashlab/Firebase-ANE/files/1754241/firebaseDatabase.ane.zip)

**Comment by arcreature7** [comment]
The log is output as follows:

**FirebaseDB(AirCommand) convertDataSnapshotToJson BEGIN**
FirebaseDB(AirCommand) convertDataSnapshotToJson .getClass(): class java.util.HashMap
FirebaseDB(AirCommand) convertDataSnapshotToJson .getName(): java.util.HashMap
FirebaseDB(AirCommand) convertDataSnapshotToJson .getSimpleName(): HashMap
FirebaseDB(AirCommand) convertDataSnapshotToJson cast to Map
**FirebaseDB(AirCommand) convertDataSnapshotToJson END**

Is it possible to trace issues with this information?

**Comment by myflashlab** [comment]
Thanks for the logs. we have also ordered an old Android device with Android 4.0.3, as soon as we get that, we'll do tests on it and let you know...

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
