### ISSUE TITLE
AndroidSupport ANE V26.0.2 -  Error: Duplicate platform Android-ARM found for extension...

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/Firebase-ANE#192]
## Problem Description ##
ANEs setup with AneLab 1.1.11, for cross-platform project, AndroidSupport V26.0.2 triggers this error when testing locally:
_The content cannot be loaded because there was a problem loading an extension: Error: Duplicate platform Android-ARM found for extension com.myflashlab.air.extensions.dependency.androidSupport_

This slows down GUI development having to go always through device. Error does not happen using ANE **not generated by AneLab**

**Comment by PippoApps** [comment]
Removing AndroidSupport ANE it keeps triggering the same message with other ANEs.
keep removing anes and get errors in sequence:

- Error: Duplicate platform Android-ARM found for extension com.myflashlab.air.extensions.facebook
- Error: Duplicate platform Android-ARM found for extension com.myflashlab.air.extensions.firebase.invites
- Error: Duplicate platform Android-ARM found for extension com.myflashlab.air.extensions.dependency.firebase.analytics.impl
- Error: Duplicate platform Android-ARM found for extension com.myflashlab.air.extensions.dependency.firebase.common

etc.
Could it be related to newer versions of ANEs?

**Comment by PippoApps** [comment]
For future reference, this is from a StackOverflow comment:
"Solved by removing the extension from temp directory in windows. Just search the temp directory for that ANE and delete the folder.
In my case the link was: C:\Users[USER]\AppData\Local\Temp\Tmp_ANE_File_Unzipped_Packages"

**Comment by PippoApps** [comment]
Yes it's definitely something related to new ANE. 
Using older version of AndroidSupport.ane fixes the problem.

I initially had the same error, until I removed ANE cache as described here: https://stackoverflow.com/questions/34694061/native-extension-removed-from-air-but-still-getting-error-related-to-it-duplic

Changing
**dependency.androidSupport-V26.0.2.ane**
_Saved in folder by AneLab_
With 
**androidSupport-full.ane**
_Taken from last downloaded club archive_
solves the error.

**Comment by myflashlab** [comment]
Hmm, the lates androidSupport-full.ane and the other one from ANELAB are identical. Maybe you’ve had two of this ANE wrongly linked in your project? The error message is strongly suggesting something like that.

**Comment by PippoApps** [comment]
In case others occur in this problem using Animate CC. ANEs are temporarily unpackaged in "C:\Users[USER]\AppData\Local\Temp\Tmp_ANE_File_Unzipped_Packages" folder. When upgrding an ANE with a file with another name (i.e. 6.0.0 to 6.0.1), previously unpackaged folder is not deleted. Therefore you have to go there and manually delete folder. This is an example, you can see the double firebase.invites at the bottom:
![image](https://user-images.githubusercontent.com/29799572/37147239-355abbce-2301-11e8-916d-05d4967ba825.png)
