### ISSUE TITLE
firebase auth error on ios

### ISSUE THREAD

**Issue by 4malik** [myflashlab/Firebase-ANE#196]
Hi. Found next problem.
On Development its working fine. When I switched to production and launched AdHoc I got errors.

``` javascript
static private function getUserInfo():void {
	var userInfoOnProviders:UserInfo;
	var i:int;
	var _length:int = FirebaseUser.providersData.length;
	Main.addRecord("FirebaseAuthManager getUserInfo 5 " + _length);
	Main.addRecord("FirebaseAuthManager getUserInfo 5.1 " + JSON.stringify(_profiles));
	for (i = 0; i < _length; i++) {
		try {
			Main.addRecord("FirebaseAuthManager getUserInfo 6.0 " + JSON.stringify(FirebaseUser.providersData[i]));
			Main.addRecord("FirebaseAuthManager getUserInfo isUserIno: 6.1 " + (FirebaseUser.providersData[i] is UserInfo ? "true" : "false"));
			userInfoOnProviders = FirebaseUser.providersData[i];
			Main.addRecord("FirebaseAuthManager getUserInfo 6.2");
			_profiles[userInfoOnProviders.providerId] = {
				displayName	: userInfoOnProviders.displayName, 
				email		: userInfoOnProviders.email, 
				picture		: userInfoOnProviders.photoUrl,
				phone		: userInfoOnProviders.phoneNumber,
				providerId	: userInfoOnProviders.providerId,
				userId		: userInfoOnProviders.userId
			}
		}
		catch(e:Error) {
			Main.addRecord("FirebaseAuthManager getUserInfo 6.3 error" + e.message + " " + e.getStackTrace());
		}
	}
	Main.addRecord("FirebaseAuthManager getUserInfo 7 dispatchEvent");
}
```

Main.addRecord - my debugger trace

So.
On Development I got ok
![img-0867](https://user-images.githubusercontent.com/30479942/36894436-c1a131ee-1e24-11e8-9360-222a7423361f.JPG)

Then i switched to production and got 
![img-0868](https://user-images.githubusercontent.com/30479942/36894449-cb5e483e-1e24-11e8-9c68-cf5de8685e99.JPG)

But on development no error 1034
Then I changed 
var userInfoOnProviders:UserInfo; to var userInfoOnProviders:Object;
![img-0869](https://user-images.githubusercontent.com/30479942/36894484-ebc56cec-1e24-11e8-91c0-c2ea506771d8.JPG)

And no error.

So please can you explain what is that.

ps. air 27
updated libs from you to the last versions.
used ANE LAB 
ios 11.2.6

**Comment by myflashlab** [comment]
We have just updated to V6.5.0 (If you are using ANELAB, please install V1.1.14 BEFORE updating the ANEs). Unfortunately we have not been able to reproduce the problem yet! it's still working fine. I recall that you have similar trouble with FB ANE when building in adhoc: https://github.com/myflashlab/facebook-ANE/issues/124 I really think there's something wrong elsewhere. However, if you can share more info with us about this problems, please do, we'd be happy to figure this out.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
