### ISSUE TITLE
Apple reports Facebook SDK in ANE outdated on iOS app.

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/Firebase-ANE#198]
We have received this communication from Apple:
"Your Facebook SDK for iOS is out of date and missing important iOS 11 fixes that make it easier for people to log into your app"... etc.
Do you plan an update on Facebook ANE with new SDK?
Since App Invites have been already deprecated by Facebook, will you implement new Game Requests or App Requests?
Thank you!

**Comment by myflashlab** [comment]
Yes, we know. We are currently working on a big update on many of our ANEs, facebook included also. We’re already on it...

**Comment by PippoApps** [comment]
Great news, thank you.
