### ISSUE TITLE
VAPT - FCM ANE - No Code Obfuscation

### ISSUE THREAD

**Issue by mprabhu33** [myflashlab/Firebase-ANE#199]
We are using FCM ANE for Push notification in the mobile app. Our mobile app given to VAPT (Vulnerability Assessment and Penetration Testing) review.

They found the No Code Obfuscation in the below jar files,
1. firebase-messaging.jar
2. firebase-common.jar
3. firebase-iid.jar
4. google-play-services-tasks.jar
5. google-play-services-basement.jar
6. google-play-services-base.jar
7. google-play-services-appinvite.jar

Could you please provide the below ANE's with Code Obfuscation?

<extensions>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
        
  <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    
    </extensions>

OR

Is there any tool to convert the ANE with Code Obfuscation?

**Comment by mprabhu33** [comment]
Any update? Is it possible for Code Obfuscation for ANE's?

**Comment by myflashlab** [comment]
We haven't tried that before. We will try to gather more information about this and update you. Thanks.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
