### ISSUE TITLE
AneLab, help hotspot is blank for Firebase core

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/Firebase-ANE#202]
![image](https://user-images.githubusercontent.com/29799572/37214515-49767ef0-23f0-11e8-8754-7da6ac5cb512.png)

**Comment by myflashlab** [comment]
Yes, we have spotted that ourselves too :) when releasing the new version of Firebase collection we will add the tooltip content. but the field is easy to be guessed. Thanks for reporting that already.

**Comment by PippoApps** [comment]
No problem :) I don't mean to be annoying eheh just love your product and
try to help improve it ;)

**Comment by myflashlab** [comment]
not at all, we love your feedback. keep it coming and we'll keep on fixing :)
