### ISSUE TITLE
Dynamic Link invitation on Android, invite id is reported in Firebase Log but not in event.

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/Firebase-ANE#204]
Opening App from an invite with generated link, reports the invitation ID in Firebase Log, but on Android event property invitationId is null. On iOS all works fine. 

Opening the app with the same invitation link:

**Here the iOS Output:**
(OverrideAir does not trace output for iOS)
35 [MainApp]		Received a deep link? e.link = (null)
36 [MainApp]		Received an invitation? e.invitationId = 865990491833-68db3851-5b6e-4e97-8a4c-60e28d23da0b

**Here's the Android output:**
FirebaseDynamicLinks> checkDynamicLinks deepLink = https://w322p.app.goo.gl/?isi=1079965882&link=https%3A%2F%2Fwww%2Eplaybuncoonline%2Ecom&apn=air%2Ecom%2Eyappingmoose%2Ebuncobonko&ibi=com%2Eyappingmoose%2Ebuncobonko
FirebaseDynamicLinks> checkDynamicLinks invitationId = 865990491833-68db3851-5b6e-4e97-8a4c-60e28d23da0b
37 [MainApp]		Received a deep link? e.link = https://www.playbuncoonline.com
38 [MainApp]		Received an invitation? e.invitationId = null

_On Android somehow invitation ID is not brought from internal listener to AS3 event_

## Environment ##
* Android API Version: 23
* AIR SDK Version: 28.0.0.125

**Comment by PippoApps** [comment]
Any news on this?
This is 100% an ANE bug. 
thanks

**Comment by myflashlab** [comment]
we'll have news about this soon...

**Comment by PippoApps** [comment]
Looking forward!

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
