### ISSUE TITLE
Firebase SDK New Version Update

### ISSUE THREAD

**Issue by kryrnrj** [myflashlab/Firebase-ANE#207]
We waiting for new firebase sdk updates. Because FCM token not working below Android 4.4.2. Google updated firebase and google services. It's urgent for us. Thanks.

**Comment by cheninson** [comment]
Android 4.4.4 also Fail

**Comment by myflashlab** [comment]
@kryrnrj V6.5.0 is now released. read the changlog to know what should be changed on your project. OR if you are using the [ANELAB](https://github.com/myflashlab/ANE-LAB/) software, first update to V1.1.14 and then update the firebase ANEs. then open your project and update the ANEs there. all settings will be done for you automatically.

@cheninson fail on Android 4.x.x has nothing to do with updating the ANEs. You just need to add the following attribute to your ```application``` tag: ```android:name="android.support.multidex.MultiDexApplication"```

Check this out: https://github.com/myflashlab/Firebase-ANE/blob/master/AIR/Main-app.xml#L23
