### ISSUE TITLE
Any news on new ANEs? We are holding on standby an expensive project since a while waiting for this...

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/Firebase-ANE#208]

**Comment by myflashlab** [comment]
We have just released Facebook/GameServices/GoogleSignIn. They are available through ANELAB and direct ANE club package from your Myflashlabs Panel.

NOTICE: the wiki and usage documentation of the Facebook ANE is still not updated. it should be ready by tomorrow.

The Firebase updates and GoogleVR plus the AR ANE are also completing. working on them right now. The whole team is on them to finish soon :)

**Comment by PippoApps** [comment]
Thank you, great news

**Comment by PippoApps** [comment]
I'll be waiting for updated wiki to implement new facebook ANE

**Comment by myflashlab** [comment]
Yeah, this new set of updates have been like crazy.. just imagine, we have iOS 11 new Facebook and Firebase SDKs plus how Google changed GoogleSignIn and made it an dependency for GoogleGames! WOW. we will definitely need a long vacation when all updates are finished! :D

**Comment by PippoApps** [comment]
:) will this work ok with air 29?

**Comment by myflashlab** [comment]
hahahaha, good one :)
