### ISSUE TITLE
How do I access the new database to expand and use it?

### ISSUE THREAD

**Issue by arcreature7** [myflashlab/Firebase-ANE#209]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Android API Version: firebase.core-V6.0.1, firebase.realtimeDB-V6.0.0
* AIR SDK Version: 28

## Problem Description ##
[Question about Firebase Real-time database]
I want to use multiple databases to improve performance of the database.
But I don't know how to get a new instance of the database.

Firebase guide documents.
https://firebase.google.com/docs/database/usage/sharding

If you look at the example code in Firebases
mDatabase = FirebaseDatabase.getInstance("https://testapp-1234.firebaseio.com").getReference();
In this way, I can get the "DatabaseReference" by setting the Instance to a different database.
When I look at the document of the ANE in my flash lab, I don't know how to create a new instance.

How do I access the new database to expand and use it?

**Comment by myflashlab** [comment]
The ANE does not support multiple instance of Firebase database. However, we are supporting [Firestore](https://firebase.google.com/docs/firestore/). You may use that to accomplish even more.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
