### ISSUE TITLE
Core ANE requires analytics?

### ISSUE THREAD

**Issue by mrfrasier** [myflashlab/Firebase-ANE#210]
## Environment ##
* Adobe Animate CC
* AIR SDK Version: 28 - iOS

## Problem Description ##
Just purchased the Firebase Core ANE to get our feet wet in preparation for the transition to FCM from GCM. After jumping through the required hoops to get the ANE, we popped it into our project, added the call to init and launched.

That failed, because for some reason the ANE doesn't include an isSupported or similar method to disable while on desktop/simulator.

Trying to deploy to a device instead to see if things work, compilation fails:

![image](https://user-images.githubusercontent.com/4335972/38756087-3fdcce10-3f36-11e8-922b-30d42074acf2.png)

So the Analytics ANE is required? There's no mention of that in the pre-requisites here
https://github.com/myflashlab/Firebase-ANE/wiki/A.1.-Prerequisites

## Steps to Reproduce ##
Generate ANE, add to project, try to build.

**Comment by mrfrasier** [comment]
Reading around, I see that OverrideAir is mentioned as a required ANE for all projects (wasn't mentioned in the Firebase docs that I could see). In any case, I added it and the same happens on export.

**Comment by myflashlab** [comment]
The exact dependencies are explained in this page https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

The error message shows that you have missed copying the iOS frameworks to your AIR SDK. You can see which frameworks are required for each Firebase child. And where/how to copy them, is explained here: https://github.com/myflashlab/Firebase-ANE/wiki/A.3.-Add-the-SDK

If you are a club member, I suggest you to use [ANELAB](https://github.com/myflashlab/ANE-LAB/). This software will copy all the dependencies and frameworks automatically. it also setups the manifest .xml file for you on the fly.

If not a club member, read through the wiki pages and the information there is good enough for setting things up and running manually.

If you have more questions, do ask us, we'd be happy to help.
