### ISSUE TITLE
adding a collection to an existing document does not return an event

### ISSUE THREAD

**Issue by robertflesch** [myflashlab/Firebase-ANE#211]
## Environment ##
* Android API Version: - Not tested
* iOS Version: 11.3
* AIR SDK Version: 29

## Problem Description ##
When adding a collection and a document to an existing document, no catchable event is generated
I am trying to catch every event possible. But no event is generated. The database updates correctly with the collection and document added. But I need to capture the document ID in order to add another sub collection.

Manifest Not needed - works fine for all other functions

private function addSeason():void {
        var dr:DocumentReference = Firestore.collection("teams").document(_teamData.teamGuid);
        dr.addEventListener( FirestoreEvents.COLLECTION_ADD_SUCCESS, onCollectionAddSuccess );
        dr.addEventListener( FirestoreEvents.COLLECTION_ADD_FAILURE, onCollectionAddFailure );
        dr.addEventListener( FirestoreEvents.DOCUMENT_SET_SUCCESS, onDocumentSetSuccess );
        dr.addEventListener( FirestoreEvents.DOCUMENT_SET_FAILURE, onDocumentSetFailure );
        dr.addEventListener( FirestoreEvents.DOCUMENT_UPDATE_SUCCESS, onDocumentUpdateSuccess );
        dr.addEventListener( FirestoreEvents.DOCUMENT_UPDATE_FAILURE, onDocumentUpdateFailure );
        dr.addEventListener( FirestoreEvents.DOCUMENT_GET_SUCCESS, onDocumentGetSuccess );
        dr.addEventListener( FirestoreEvents.DOCUMENT_GET_FAILURE, onDocumentGetFailure );
        dr.collection("Seasons").add( { name: "Season 1", created: FieldValue.TIMESTAMP } );
        function onCollectionAddSuccess(e:FirestoreEvents):void {
            trace("season added, get id");
        }
        function onCollectionAddFailure(e:FirestoreEvents):void {
            trace("season added, get id");
        }
        function onDocumentSetSuccess(e:FirestoreEvents):void {
            trace("season added, get id");
        }
        function onDocumentSetFailure(e:FirestoreEvents):void {
            trace("season added, get id");
        }
        function onDocumentUpdateSuccess(e:FirestoreEvents):void {
            trace("season added, get id");
        }
        function onDocumentUpdateFailure(e:FirestoreEvents):void {
            trace("season added, get id");
        }
        function onDocumentGetSuccess(e:FirestoreEvents):void {
            trace("season added, get id");
        }
        function onDocumentGetFailure(e:FirestoreEvents):void {
            trace("season added, get id");
        }
    }

## Steps to Reproduce ##
On firestore add a collection and document with a value to an existing document.

## Known Workarounds ##
Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
