### ISSUE TITLE
AneLab configured manifest triggers AppStore error: <key>get-task-allow</key><true/>

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/Firebase-ANE#212]
Hi,
manifest configured by AneLab generates an error uploading to AppStore:
ERROR ITMS-90164: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: 'true' for the key 'get-task-allow' in 'Payload/...'

Will setting this to false prevent any ane working?
<key>get-task-allow</key><true/>
<key>get-task-allow</key><false/>

thank you

**Comment by myflashlab** [comment]
When using ANELAB, you are hitting the big blue button which says "Export to modify the manifest", right? ok, a window opens which lets you select which iOS build you like to perform. options are shown in the screenshot below. Choose production and the manifest will be set automatically for you. including the ```<key>get-task-allow</key>``` value

<img width="750" alt="screen shot 2018-05-03 at 3 37 27 pm" src="https://user-images.githubusercontent.com/1692948/39574414-31e6c754-4ee8-11e8-8fdc-3956712ddde5.png">

**Comment by myflashlab** [comment]
AdobeAnimate is doing that? Well, that make sense, a tweeter poll we launch in early 2017 showed that most AIR devs are using the intelliJ IDE more than any other ANE. since then we have been using intelliJ and we have been happy with that. no strange cache problems.

**Comment by PippoApps** [comment]
True, much better. I use that for source code too. But working on certain projects though, requiring constant updates in vector assets, compiling with the IntelliJ IDE would kill productivity. 
Since you mention Animate CC in your posts, if you want a list of possible pitfalls I'd be happy to help.
I'll let you know how it goes after next upload.

**Comment by myflashlab** [comment]
> if you want a list of possible pitfalls

yes, we would look forward to it, I'm sure other devs working with AdobeAnimate would find it useful.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
