### ISSUE TITLE
Test Movie fails because cannot find extension

### ISSUE THREAD

**Issue by LeapingSwan** [myflashlab/Firebase-ANE#216]
Hi,

I am trying to put firebaseCore.ane in my project for the first time and hitting an early problem.

I am using Animate CC with AIR 30.0.  Creating a build for iOS.

I have created and added the firebaseCore.ane to the project.

I have also added the various dependencies to the AIR30\lib\aot\stub directory along with all the other frameworks.  My xml includes the following:

    <extensions>
        <extensionID>com.myflashlab.air.extensions.dependency.FirebaseAnalytics</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.FirebaseCore</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.FirebaseCoreDiagnostics</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.FirebaseInstanceID</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.FirebaseNanoPB</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.GoogleToolboxForMac</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.nanopb</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    </extensions>

On launching a test movie I get the following error message:

Test Movie terminated.
The content cannot be loaded because there was a problem loading an extension: Error: Requested extension com.myflashlab.air.extensions.dependency.FirebaseAnalytics could not be found.

If I remove the FirebaseAnalytics then it simply shows that the next dependency (FirebaseCore) is not found.

How can I make the main ANE or Animate find these dependencies?

Thanks for your help.

Stephen

**Comment by myflashlab** [comment]
@LeapingSwan Well, your setup is VERY wrong. The frameworks should be copied to the ```AIR30\lib\aot\stub``` directory, but dependency ANE files are needed to be implemented into your app and they all can be found [here](https://github.com/myflashlab/common-dependencies-ANE).

In your message, I saw that you are using ```<extensionID>com.myflashlab.air.extensions.dependency.FirebaseCoreDiagnostics</extensionID>``` well, such dependency does not exist! That's a framework needed to be copied to ```AIR30\lib\aot\stub```. it is not a dependency ANE.

on the other hand, only having the FirebaseCore is not enough, The core ANE is the main thing that all othe Firebase children can be installed on. If you want to use Firebase Analytics for example, you need to first setup the FirebaseCore and then add the Firebase Analytics.

Setting up the Firebase ANEs can overwhelming and confusing. we all know that :) but please take your time and read through the setup progress [here on our wiki docs](https://github.com/myflashlab/Firebase-ANE/wiki). try to do the steps all one after the other and you will be fine.

However, we strongly recommend to you to join the club and use the [ANELAB](https://github.com/myflashlab/ANE-LAB/) software. This software will take care of all the setup process for you automatically.

**Comment by LeapingSwan** [comment]
Ok, thanks for the info.  I have now understood some of the problem which was a confusion on my part between the ANEs needed and the frameworks (this info is spread round the wiki making it hard to be clear - if you can lay this out in a one stop walk through it would be easier).  In the end I had everything in the right place but was just confused about how to add the frameworks which I had mistakenly thought to have to be in the xml along with the ANEs.  I now know better.

I am considering ANE-LAB but wanted to see how ads work in the game before committing fully.

Anyway, Firebase core is now in and I can trace info such as version etc.

I am now trying to add in AdMob.  I have the ANE installed and, I believe, the right frameworks, on the same principle as above but when I try to call AdMob.init or even test for AdMob.os I get an error reference (obtained through Scout on a device, not a simulator):

ReferenceError: Error #1065

I believe this is a name clash but I can't find what.  Any idea what might cause this?  This shows the ANEs I have installed.

<img width="210" alt="screen shot 2018-06-14 at 17 03 57" src="https://user-images.githubusercontent.com/39804662/41424114-11eebdca-6ff5-11e8-8bb6-933cff38ab86.png">

My xml includes:

  	<key>MinimumOSVersion</key>
		<string>8.0</string>
		<key>NSAppTransportSecurity</key>
		<dict>
			<key>NSAllowsArbitraryLoads</key>
			<true/>
		</dict>

 and further on:

    <extensions>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
<extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    </extensions>

I believe I have followed the instructions for putting AdMob but obviously something is wrong.

Thanks

Stephen

**Comment by LeapingSwan** [comment]
Hi thanks for that which you are right I has missed.  It's now in and AdMob seems to be in the project but still not working fully.

I have been working through that installation guide but something is still not quite right.  As in the example given I have tested for AdMob.os to use that to determine which AdUnit to initiate.  However AdMob.os is coming back as null.  If I bypass that test and try to initiate the iOS one (which is what I am testing) that fails.  I have copied below the code I am using, the traces I am getting back via Adobe Scout (I am testing on a device) and, for completeness the updated xml manifest.

As you will see from the traces I am seeing AdMob and and can get version numbers etc but not the os property.

I am using the demo version of the AdMob ane at the moment (I'll upgrade when I have it all working) and I do get the pop up on device telling me that I am using the demo version so it seems to be working to a level.

Thanks for your help.

Stephen

CODE:

		private function setUpAds() 
		{
			
			trace("setUpAds started ");
			trace("AdMob.ANDROID " + AdMob.ANDROID);
			trace("AdMob.IOS_SDK_VERSION " + AdMob.IOS_SDK_VERSION);
			trace("AdMob.IOS " + AdMob.IOS);
			trace("AdMob.ANDROID_SDK_VERSION " + AdMob.ANDROID_SDK_VERSION);
			trace("AdMob.ERROR_CODE_INTERNAL_ERROR " + AdMob.ERROR_CODE_INTERNAL_ERROR); 
			trace("AdMob.os " + AdMob.os);
			trace("AdMob.VERSION " + AdMob.VERSION);
			
			// initialize AdMob and pass in the Adobe AIR Stage and your AdmMob ApplicationCode
			if(AdMob.os == AdMob.ANDROID) 
			{
				trace("Initiate Android");
				AdMob.init(stage, "ca-app-pub-XXXXXXXXXXXXXXXXX")
				
				// Add general listeners for the Ads
				AdMob.api.addEventListener(AdMobEvents.AD_CLOSED, onAdClosed);
				AdMob.api.addEventListener(AdMobEvents.AD_FAILED, onAdFailed);
				AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP, onAdLeftApp);
				AdMob.api.addEventListener(AdMobEvents.AD_LOADED, onAdLoaded);
				AdMob.api.addEventListener(AdMobEvents.AD_OPENED, onAdOpened);

				// listen to the banner Ad to get its final width/height in pixels so you can place it anywhere you like in your Air app
				AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED, onBannerAdSizeReceived);

				// to create a banner Ad, first you need to initialize a new banner with your unitId and prefered banner size
				AdMob.api.banner.init("ca-app-pub-XXXXXXXXXXXXXXXXX", ApiBannerAds.BANNER);
			
				adRequest = new AdRequest();
			
				AdMob.api.banner.loadAd(adRequest);

	//		} else if(AdMob.os == AdMob.IOS) 
			} else if(!Constants.isAndroid) 
			{
			
				trace("Initiate iOS");
				
				AdMob.init(stage, "ca-app-pub-XXXXXXXXXXXXXXXXX");
				
				// Add general listeners for the Ads
				AdMob.api.addEventListener(AdMobEvents.AD_CLOSED, onAdClosed);
				AdMob.api.addEventListener(AdMobEvents.AD_FAILED, onAdFailed);
				AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP, onAdLeftApp);
				AdMob.api.addEventListener(AdMobEvents.AD_LOADED, onAdLoaded);
				AdMob.api.addEventListener(AdMobEvents.AD_OPENED, onAdOpened);

				// listen to the banner Ad to get its final width/height in pixels so you can place it anywhere you like in your Air app
				AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED, onBannerAdSizeReceived);

				// to create a banner Ad, first you need to initialize a new banner with your unitId and prefered banner size
				AdMob.api.banner.init("ca-app-pub-XXXXXXXXXXXXXXXXXX", ApiBannerAds.BANNER);
			
				adRequest = new AdRequest();
			
				AdMob.api.banner.loadAd(adRequest);
			
			}
			
			trace("setUpAds completed");

		}

TRACES RETURNED:

firebaseIsAvailable true
firebaseSDK 4.11.0
firebaseIOS ios
firebaseVersion 6.5.0
setUpAds started 
AdMob.ANDROID android
AdMob.IOS_SDK_VERSION 7.29.0
AdMob.IOS ios
AdMob.ANDROID_SDK_VERSION 12.0.1
AdMob.ERROR_CODE_INTERNAL_ERROR 0
AdMob.os null
AdMob.VERSION 3.0.0
Initiate iOS
setUpAds completed
onBannerAdSizeReceived
onAdFailed
startBanner
showBanner
onAdFailed

XML Extract:

    <iPhone>
        <requestedDisplayResolution>high</requestedDisplayResolution>
        <InfoAdditions><![CDATA[
  			<key>MinimumOSVersion</key>
				<string>8.0</string>
				<key>NSAppTransportSecurity</key>
				<dict>
					<key>NSAllowsArbitraryLoads</key>
					<true/>
				</dict>

        
    		 <key>CFBundleURLTypes</key>
			<array>
    			<dict>
        			<key>CFBundleURLSchemes</key>
        			<array>
            			<string>air.com.XXXXXXXXXXXX</string>
        			</array>
    			</dict>
			</array>   
        
    		<key>UIDeviceFamily</key>
    		<array><string>1</string><string>2</string></array>
		]]></InfoAdditions>
    </iPhone>
    <supportedLanguages>en</supportedLanguages>
    <android>
        <manifestAdditions><![CDATA[<manifest>
         
        	<uses-permission android:name="android.permission.INTERNET"/>
        	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
	
			
			<uses-sdk android:targetSdkVersion="23"/>
	
			<application>
		
				<activity>
					<intent-filter>
						<action android:name="android.intent.action.MAIN" />
						<category android:name="android.intent.category.LAUNCHER" />
					</intent-filter>
					<intent-filter>
						<action android:name="android.intent.action.VIEW" />
						<category android:name="android.intent.category.BROWSABLE" />
						<category android:name="android.intent.category.DEFAULT" />
					</intent-filter>
				</activity>
		
			
        		<activity
            		android:name="com.google.android.gms.ads.AdActivity"
            		android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            		android:theme="@android:style/Theme.Translucent" />
			
				<meta-data
            		android:name="com.google.android.gms.version"
            		android:value="@integer/google_play_services_version" />
		
			</application>
        
        </manifest>]]></manifestAdditions>
        
    </android>
    <versionLabel></versionLabel>
    <extensions>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.admob</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    </extensions>
</application>

**Comment by myflashlab** [comment]
> If I bypass that test and try to initiate the iOS one (which is what I am testing) that fails

Will you please explain about this more?

in your traces, you said you are seeing ```onAdFailed```, will you tell me what error code you are also seeing?

```actionscript
private function onAdFailed(e:AdMobEvents):void
{
	trace("onAdFailed adType > " + e.adType); // AdMob.AD_TYPE_*
	trace("onAdFailed errorCode > " + e.errorCode); // AdMob.ERROR_CODE_*
	trace("onAdFailed msg > " + e.msg);
}
```

Finally about ```AdMob.os``` being null, thanks for reporting that! That is our mistake and will shortly release an update to have that fixed. Thanks again.

**Comment by myflashlab** [comment]
Ok, fixed the documentation to:
```actionscript
if(OverrideAir.os == OverrideAir.ANDROID) AdMob.init(stage, "ca-app-pub-9002001127208746~3709582175");
else if(OverrideAir.os == OverrideAir.IOS) AdMob.init(stage, "ca-app-pub-9002001127208746~3709582176");
```

**Comment by LeapingSwan** [comment]
Ok, thanks on the .os.  I have traced the OverrideAir.os and it correctly comes back as "iOS" so I can use that for the test ok.

I had assumed that this was suggesting a cause for the problem loading and Ad so had not looked at the error messages for the onAddFailed object.  Done that now and my traces are:

firebaseIsAvailable true
firebaseSDK 4.11.0
firebaseIOS ios
firebaseVersion 6.5.0
setUpAds started 
AdMob.ANDROID android
AdMob.IOS_SDK_VERSION 7.29.0
AdMob.IOS ios
AdMob.ANDROID_SDK_VERSION 12.0.1
AdMob.ERROR_CODE_INTERNAL_ERROR 0
AdMob.os null
OverrideAir.os ios
AdMob.VERSION 3.0.0
Initiate iOS
setUpAds completed
onBannerAdSizeReceived
onAdFailed
onAdFailed adType > banner
onAdFailed errorCode > 3
onAdFailed msg > Error Domain=com.google.ads Code=1 "Request Error: No ad to show." UserInfo={NSLocalizedDescription=Request Error: No ad to show., NSLocalizedFailureReason=Request Error: No ad to show.}
startBanner
showBanner
onAdFailed
onAdFailed adType > banner
onAdFailed errorCode > 3
onAdFailed msg > Error Domain=com.google.ads Code=1 "Request Error: No ad to show." UserInfo={NSLocalizedDescription=Request Error: No ad to show., NSLocalizedFailureReason=Request Error: No ad to show.}

So it looks like there is no ad to show.  I'm not sure what the cause is of that though - is that a common situation?  

To be clear I am currently experimenting on the demo version of your AdMob ane and my Admob account is fairly new (a few weeks) and I just added payment info this morning so not sure if that can be a cause.  

Also I do load an ad on launching the game but then only run the code to show it when the user presses a button, so a few moments later.

Thanks

Stephen

**Comment by myflashlab** [comment]
Aha, the ```no Ad to show``` thing! :) This means your setup is all ready and fine actually. You need to read this thread here https://github.com/myflashlab/Admob-ANE/issues/35
I'm closing the issue here anyhow as this is more related to Admob part rather than Firebase.
