### ISSUE TITLE
Please add setScreen on Firebase Analytics

### ISSUE THREAD

**Issue by leossmith** [myflashlab/Firebase-ANE#217]
Please add the Track Screens option in Firebase Analytics.

https://firebase.google.com/docs/analytics/screenviews?authuser=0

Thank you.

**Comment by myflashlab** [comment]
Checkout this demo version V6.5.1 [firebaseAnalytics.ane.zip](https://github.com/myflashlab/Firebase-ANE/files/2087903/firebaseAnalytics.ane.zip)

If you are using ANELAB, just install the current available one and finally, replace the ANE with this version and you will have access to the new ```setScreen``` method. Read method usage here: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/firebase/analytics/FirebaseAnalytics.html#setScreen()

We will be releasing the new version soon, but this will get you going for now if you are using ANELAB. If not, you will see the "demo dialog" when using the ANE. 

If any trouble using the new feature, please let us know. 

Thanks for bringing this feature to our attention.
