### ISSUE TITLE
FirebaseInstanceIdInternalReceiver

### ISSUE THREAD

**Issue by ikuprin** [myflashlab/Firebase-ANE#223]
Documentation for Firebase Core initialization contains this string in manifest:

`              <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false"/>
`

But ANE LAB does not insert this in manifest. Where is right behaviour?

**Comment by myflashlab** [comment]
good catch! the ANELAB setup is the correct one. And in the [changelog](https://github.com/myflashlab/Firebase-ANE#changelog) we have mentioned that this tag should be removed.
> (Core) Remove the following receiver from your manifest: ```<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false"/>```

Could you tell me where in the docs we have this mistake? so we can update it? Thanks.

**Comment by ikuprin** [comment]
Here is:
https://github.com/myflashlab/Firebase-ANE/wiki/A.4.-Initialize-Firebase-in-your-app

**Comment by myflashlab** [comment]
Fixed the docs. Thank. However, it was not a stopping problem if it were still available in the manifest. But thanks for noticing that :)
