### ISSUE TITLE
Android crashes

### ISSUE THREAD

**Issue by ikuprin** [myflashlab/Firebase-ANE#225]
Android dashboard reports about this crash:

```
java.lang.IllegalArgumentException: 
  at com.adobe.fre.FREContext.dispatchStatusEventAsync (Native Method)
  at com.myflashlab.firebase.core.AirCommand.onConnected (AirCommand.java:554)
  at com.google.android.gms.common.internal.zzae.zzl (Unknown Source:108)
  at com.google.android.gms.common.api.internal.zzba.zzk (Unknown Source:22)
  at com.google.android.gms.common.api.internal.zzao.zzajm (Unknown Source:89)
  at com.google.android.gms.common.api.internal.zzao.onConnected (Unknown Source:21)
  at com.google.android.gms.common.api.internal.zzbi.onConnected (Unknown Source:7)
  at com.google.android.gms.common.api.internal.zzt.onConnected (Unknown Source:5)
  at com.google.android.gms.common.internal.zzac.onConnected (Unknown Source:2)
  at com.google.android.gms.common.internal.zzn.zzama (Unknown Source:143)
  at com.google.android.gms.common.internal.zze.zzw (Unknown Source:47)
  at com.google.android.gms.common.internal.zzi.zzamc (Unknown Source:54)
  at com.google.android.gms.common.internal.zzh.handleMessage (Unknown Source:275)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6938)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```

Just for yesterday 21 identical crash...

Devices:
Samsung Galaxy A8(2018) (jackpotlte), Android 7.1
Motorola Moto Z (2) Play (albus), Android 8.0
Huawei P20 lite (HWANE), Android 8.0
Samsung Galaxy A5(2017) (a5y17lte), Android 7.0
Motorola Moto G (5S) Plus (sanders_n), Android 7.1
Samsung Galaxy Tab E 9.6 (gtelwifiue), Android 7.1
etc...

**Comment by myflashlab** [comment]
This one is interesting! :thinking: in the ```onConnected``` method, we have only a simple dispatch method like below: 

```java
MyExtension.AS3_CONTEXT.dispatchStatusEventAsync(ExConsts.GOOGLE_API_CONNECTION_SUCCESS, "");
```

All it does, dispatches back to your AIR app. The only reason that could happen, I think, is that the AIR context is lost. But that's not very logical because the AIR context has initiated the ANE to init FirebaseCore... 

Can you send us your app or link to it? or for privacy concerns, email its link directly to us? so we can also have a look?

**Comment by myflashlab** [comment]
> the AIR context is lost.

And that happens **SOMETIMES** if user send the app to the background! If the app is too heavy, when it is sent to background, the OS will kill it. And if the Native side is still in the middle of the work, it will try to dispatch to AIR but no AIR is around! and boom the crash happens.

I think this is the most reasonable explanation.

**Comment by ikuprin** [comment]
I'v sent message with app link throw contact form on your website.

**Comment by ikuprin** [comment]
Yeap, I understand reasons for this crash, but this does not make me happier. Owner look into dashboard and see "crash!". Moreover, some time ago Google began to count crashes in apps and because of this, can drop applications in the Google Play catalogue.

Can you somehow suppress dispatching if context is lost? Or some another... but without crash...

**Comment by myflashlab** [comment]
yes, may a try/catch around that line. we'll be updating you a.s.a.p.... we are in the progress of upgrading the Firebase ANEs again. we will include this fix also. but it may take some time. But if you are using the ANELAB software, you can use the revised ANE sooner. Let me know if you are using ANELAB?

**Comment by ikuprin** [comment]
Of course i'm use ANELAB - this is a great!

**Comment by myflashlab** [comment]
Glad that you are using that :) we will be adding a try/catch wrapper for that in a day or two which you can update using ANELAB quickly

**Comment by myflashlab** [comment]
Firebase Core V6.5.1 is now available through ANELAB. update your project to this version and see how it goes.

**Comment by ikuprin** [comment]
Look like works good. Awaiting for not demo release for club.

**Comment by ikuprin** [comment]
Oh, looks I missed something... Yes, I use ANELAB for testing and creating manifests, but can not use it for compiling by several reasons, e.g. release builds I compile by Jenkins (CI). Can I retrieve not demo ane on email?

Sincerly, ILLIA
info@playcus.com

**Comment by ikuprin** [comment]
One more crash..

```
java.lang.IllegalArgumentException: 
  at com.adobe.fre.FREContext.dispatchStatusEventAsync (Native Method)
  at com.myflashlab.firebase.fcm.MyFirebaseMessagingService.onMessageReceived (MyFirebaseMessagingService.java:75)
  at com.google.firebase.messaging.FirebaseMessagingService.handleIntent (Unknown Source:320)
  at com.google.firebase.iid.zzg.run (Unknown Source:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)

```

Sorry for spamming in different anes repositories with the same ane behaviour (

**Comment by myflashlab** [comment]
No, not at all, we'd be happy to track these down and fix them all one by one. The bad thing about them is that we can't duplicate them! Ok, let's start with this one. however, this one is super weird! 

on that line we have:
```java
if (MyExtension.AS3_CONTEXT != null)
{
	toTrace("MyExtension.AS3_CONTEXT != null so we can dispatch to AIR");
	MyExtension.AS3_CONTEXT.dispatchStatusEventAsync(ON_MESSAGE, new JSONObject(remoteMessage.getData()).toString());
}
``` 

We are already checking if AIR is still available or not. So throwing an error here is not normal. :thinking: and besides, ```remoteMessage.getData()``` can't be null because this method has been called because of that to begin with.

Tell me what is the error rate in your crashlytics dashboard?

**Comment by ikuprin** [comment]
As you mentioned in second post of this thread:

```
java.lang.IllegalArgumentException: 
  at com.adobe.fre.FREContext.dispatchStatusEventAsync (Native Method)

```
is that the AIR context is lost.

You created Firebase Core V6.5.1 - but I can't use it, because it is a demo version, so I'm still using 6.5.0. 
As I understand 6.5.0 hasn't checking for AS3 context.

Can I retrieve not demo ane on email?

Sincerly, ILLIA
info@playcus.com

**Comment by myflashlab** [comment]
> is that the AIR context is lost.

on the second logs you sent, we are already checking if AIR is lost or not. So, this error shouldn't have happened.

Firebase Core V6.5.1 is already released through ANELAB channel. please use that.

**Comment by ikuprin** [comment]
I'm confused... Maybe I'm doing something wrong...

1. I'm creating new project in Idea.
2. I'm creating new project in ANELAB and link it with created Idea project.
3. I'm setting up all
4. Tap "install Firebase Core v.6.5.1" in ANELAB and writing application id. ANELAB some time installing needed anes.
5. I'm going to Firebase Core v.6.5.1 ane and see into 
`static native internal const DEMO_ANE:Boolean = true;`

So, it's demo ane...

**Comment by myflashlab** [comment]
it's the **internal** constant, you can ignore that! When using ANELAB, and hiting the big blue button which reads ```EXPORT TO MODIFY THE MANIFEST FILE```, that will remove the demo dialog from all ANEs.

**Comment by ikuprin** [comment]
Maybe I'm doing smth wrong but hitting Export button do not modify any file in my project except manifest... So, after copying anes in main project I see demo dialog (

**Comment by myflashlab** [comment]
I should have been more clear maybe. the ```EXPORT TO MODIFY THE MANIFEST FILE``` button will modify the manifest file and injects an encrypted key to your manifest file and that will automatically remove the dialog from all ANEs.

If the encrypted key is inserted into your manifest, you must not see the demo dialog anymore. 

Side note: in FlashBuilder IDE, when debugging AIR apps, the IDE ads a ```.debug``` suffix to the app package name. you must make sure this is not the case for you. because the encrypted key is linked to your application package name.

**Comment by ikuprin** [comment]
Aha. Finally understand! Thank you for patience.

**Comment by ikuprin** [comment]
So... With 6.5.1 crash, that described in first post of this thread, is gone. No one at least at week.

We do not use now FCM, so I don't know state of at `com.myflashlab.firebase.fcm.MyFirebaseMessagingService.onMessageReceived (MyFirebaseMessagingService.java:75)
`

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
