### ISSUE TITLE
i have this problem when i add core 6.5.1 using anelabe to create realtime app

### ISSUE THREAD

**Issue by moazatiani** [myflashlab/Firebase-ANE#226]
hi , i have this problem 

the message shown below:

"The specified Firebase configuration files does not seem to be correct. This is the missing part: "No matching client found for package name"

so now can i insert the related ane's without anelab or what you suggest me to dislocate this problem

**Comment by myflashlab** [comment]
you see this error message when your app package name does not match your firebase setting json/plist files please verify that you have the correct firebase setting files for your app.

**Comment by moazatiani** [comment]
thank you very much
