### ISSUE TITLE
Firebase Core V6.5.1 another erorr 

### ISSUE THREAD

**Issue by moazatiani** [myflashlab/Firebase-ANE#227]
recently i tested real time database in real  android device  with using Firebase Core V6.5.1 and after i using this statement Firebase.init() the program show me this is demo version is this problem , on the other side i am sliver member from 4 months ago

**Comment by myflashlab** [comment]
Are you using the ANELAB software? if so, all you need to do is to hit the big blue button which reads "Export to modify the manifest file". That will remove the demo dialog from all ANEs.

if you are not using the ANELAB software, you must use ANEs from the package you downloaded from your myflashlabs panel. Using ANEs from our github will always have the demo dialog thing.

**Comment by moazatiani** [comment]
hi thank you about you reply me for any problem.
 now after i used  the step "Export to modfiy the manifest file " by using anelab to remove the demo dialog the demo dialog is still founded and not disappeared , so help me man

**Comment by myflashlab** [comment]
Can you post your manifest here?

**Comment by moazatiani** [comment]
thank you very much and  i am very sorry now the problems was finished   and demo dialog disappeared correctly
