### ISSUE TITLE
please please i need help 

### ISSUE THREAD

**Issue by moazatiani** [myflashlab/Firebase-ANE#228]
hi  
i need help to  connect with real database firebase using ane's  bz i am very tired i dissipated my power to make that , but without any results , so i wish you give the tutorial like videos to do that without any problems 

best regards

**Comment by myflashlab** [comment]
of course, we'd be happy to help, please let us know what error message you are facing and we'd be able to guide you through the process.

usually, the first thing you should do to use any of the Firebase children is to first make sure the FirebaseCore is working correctly in your project. So, first setup your app in the [firebase console](https://console.firebase.google.com) and then download the json/plist setting files from there. always remember that AIR apps on Android adds ```air.``` at the beginning of your app name. So, in firebase console you must introduce your app package name with the ```air.``` prefix. if everything about the FirebaseCore is setup correctly, the following method must return true.

```actionscript
var isConfigFound:Boolean = Firebase.init();
```

Check out our repository again, we have sample projects in the following IDEs: [IntelliJ](https://github.com/myflashlab/Firebase-ANE/tree/master/AIR), [FlashDevelop](https://github.com/myflashlab/Firebase-ANE/tree/master/FD) and [AdobeAnimate](https://github.com/myflashlab/Firebase-ANE/tree/master/FLA)

Also, our step by step wiki docs can help you setup firebase children easily. https://github.com/myflashlab/Firebase-ANE/wiki/A.-Get-Started

if you have checked all these information and still have questions, please share your question with us. On extreme cases, we can provide live Skype/Teamviewer help sessions which you must [contact us](http://www.myflashlabs.com/contact/) first and schedule a time for that.

**Comment by moazatiani** [comment]
thank you all things are running correctly as you told me
