### ISSUE TITLE
(Auth) signIn with email and password

### ISSUE THREAD

**Issue by jasonJamEther** [myflashlab/Firebase-ANE#23]
I am using the Auth ane to manage user authentication with email and password. I can use the ane to create users successfully. The problem that I have is logging in with email and password. The signIn method takes a single parameter: 	$credential:Object (default = null); I don't see any specifics as to what this object is. I tried creating and new object with the email and password but this did not work and in fact crashes the application. 

```actionscript
var userSignIn:Object = new Object();
userSignIn.email = email;
userSignIn.password = password;
	
Auth.listener.addEventListener(AuthEvents.SIGN_IN_RESULT, onSignIn);
Auth.signIn(userSignIn);
```
If I try Auth.signIn() , leaving the parameter null, then it works correctly at signing in anonymously.

My questions:
How should the $credential:Object (default = null); parameter be defined?
Does the signIn with email and password even work or will it just crash the app even if I define the credential object correctly?

**Comment by myflashlab** [comment]
You've got the idea correctly, you need to pass in the credential into the ```Auth.signIn``` method. But the point is that you should not create the ```Object``` yourself. You should let the ANE do that for you. Check the [sample code here](https://github.com/myflashlab/Firebase-ANE/blob/master/FD/src/MainAuth.as#L232-L242)

```actionscript
// create a new authProvider object first
var authProvider:AuthProvider = new AuthProvider();

// decide what kind of credential this authProvider instance will hold
authProvider.setEmailAuthProvider("email@myflashlabs.com", "123456");

// and finally feed in the Auth.signIn method with the parsed credential info.
Auth.signIn(authProvider.getCredential());
```

**Comment by myflashlab** [comment]
would you update us if the problem is now solved?

**Comment by jasonJamEther** [comment]
I haven't had a chance to test yet. I will test today or tomorrow. Your clarification on how to properly define the parameter object seems likely to resolve the problem.
