### ISSUE TITLE
Track FCM push notification opening

### ISSUE THREAD

**Issue by JokerDen** [myflashlab/Firebase-ANE#231]
Is there a way to track in AIR client (**Android**) when user opened the app by interaction with push notification?

**Comment by myflashlab** [comment]
Have you checked Firebase Analytics?

**Comment by JokerDen** [comment]
1. I don't use Firebase Analytics.
2. Firebase Analytics has only automatic tracking of `notification_open` event. But I need manual handling of this event for getting `notification_id` for inner needs.

**Comment by myflashlab** [comment]
You're right. For that reason, you may need to log an analytic event manually. maybe we can add some code in fcm so it checks if Firebase Analytics is available and if it is, it will hand over the information to it so analytics can send the log manually. on the AS3 side, you can decide on the log label.

Considering that this functionality is not in the official library and is considered as a custom change, I'll be closing the issue but if you are interested to go ahead with this, you can contact us [here](http://www.myflashlabs.com/contact/) while linking to this ticket. And we'll discuss the details.
