### ISSUE TITLE
can i connect to firebase and read or write data using desktop air app  

### ISSUE THREAD

**Issue by moazatiani** [myflashlab/Firebase-ANE#232]
in the beginning i want to say thank you about you made every things good about anes , i want now something very hard respect to me  the case is can i make desktop air app with firebase like read or write data to realtime database if not can i get all data from firebase database and put it in xml file and insert it on air desktop app 

thanks

**Comment by myflashlab** [comment]
Sure you can. Firebase Database and Auth can be accessed via REST API. Although limited compared to the mobile Android/iOS sides, but for accessing the database, you can use REST API, read more about it here https://firebase.google.com/docs/reference/rest/database/
You do not need an ANE on the desktop side to have access to the Firebase DB/Auth.

**Comment by myflashlab** [comment]
And here's another example of how to access Firebase through pure AS3 https://fabricemontfort.com/firebase-and-as3-ep-1-init-the-project/ credit for the link goes to [fabrice](https://twitter.com/fabriceMONTFORT)

this approach is limited compared to ANEs, but might be a good solution for the desktop side.
