### ISSUE TITLE
Incorrect Firebase Configuration Error Message

### ISSUE THREAD

**Issue by garymich** [myflashlab/Firebase-ANE#235]
## Environment ##
* Android API Version: 30
* iOS Version: N/A
* AIR SDK Version: 30

## Problem Description ##
I am trying to reuse a test project I am finished with and wanted to add the Firebase Authentication ANE to my existing project. When I try to add it I get an error telling me that there is a dependency for the Firebase Core ANE and that I need to add it first. When I try to add the Firebase Core ANE I get this error message popup:

![image](https://user-images.githubusercontent.com/41267475/43542685-b2611692-959b-11e8-95b3-fd3f54f85eb5.png)

Please let me know if you require any further information as I need to validate a test project with this ANE before we can continue developing

## Steps to Reproduce ##
Go into ANELAB, select the project and try to add the ANE.

**Comment by myflashlab** [comment]
the error message is pretty self-explaintory and this error is coming from ```google-services.jar``` directly.

Let me explain it more though: it says that the Firebase setting files, ```google-services.json``` or ```GoogleService-Info.plist``` don't match your project package name.

For firebase to work correctly, you must first create these setting files for your Android and iOS sides using the same app package name of your project. If they don't match, this error will be shown.

**Comment by myflashlab** [comment]
What is your app package name? check if you have created the firebase json file correctly in Firebase console. **NOTE:** AIR adds ```air.``` at the beginning of your package name in Android builds.

**Comment by garymich** [comment]
The name off the app package is: GoogleSignInTest. This was created in the Firebase consol a few weeks ago and I have been testing ti for a while now. My testing with the GoogleSignIn ANE is now completed and in order to save time I had just planned to use the same project. In my google-services.json file is the existing entry: "package_name": "air.com.GoogleSignInTest", within the oauth_client node. So... none of this has changed!

**Comment by garymich** [comment]
Hello, I really need help in this regard as our development is halted until I resolve this issue and hopefully validate the ANE. I would appreciate any help you can offer and please let me know if you require any further information.

**Comment by myflashlab** [comment]
well, you're saying your package name is ```GoogleSignInTest```. considering that AIR adds the prefix, your actual package name will be ```air.GoogleSignInTest```. 

Then, you said you have set Firebase config json file to ```air.com.GoogleSignInTest```! well, this is wrong. they should be the same.

**Comment by garymich** [comment]
Seems we are having a communication issue on this bug so I am going to hope the ANE works as expected and will close this issue.
