### ISSUE TITLE
firebaseIsAvailable is false - common causes

### ISSUE THREAD

**Issue by LeapingSwan** [myflashlab/Firebase-ANE#239]
iOS is minimum 8
AIR SDK is 30

I have firebase working in a test project I have made.  I am now trying to incorporate it into a larger project along with your adMob one.  Admob is working fine.  In my test I do a trace and have firebase available as true but can't seem to get it working in the main project.

I believe I have been through the set up correctly and everything looks like in the test project but clearly something is missing so wondered if there is a list of the top things to check.

I have already made sure that the project is added to Firebase and generated new google-services.json and new GoogleService-Info.plist and remade the firebase core ANE.

One possibility I have been exploring is that the bundle name for the Android and iOS version is different (it happened to be the same on the test project but is different here).

All the dependencies should be in place (as my test project would have needed those) and I believe I have added all the ANEs to the project.

Thanks

Stephen

The code is very simple:
```actionscript
	import com.myflashlab.air.extensions.dependency.OverrideAir;
	import com.myflashlab.air.extensions.firebase.core.*;
	import com.myflashlab.air.extensions.admob.*;
	

var firebaseIsAvailable:Boolean = Firebase.init();
			
trace("firebaseIsAvailable " + firebaseIsAvailable);
```

Extract from my xml is:
```xml
  </array>
	<key>MinimumOSVersion</key>
		<string>8.0</string>
  <key>NSAppTransportSecurity</key>
```

and

```xml	
]]></InfoAdditions>
    </iPhone>
    <extensions>
        <extensionID>com.milkmangames.extensions.GoViral</extensionID>
        <extensionID>com.milkmangames.extensions.StoreKit</extensionID>
        <extensionID>com.milkmangames.extensions.RateBox</extensionID>
        <extensionID>com.appsflyer.adobeair</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.admob</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    </extensions>
</application>
```

**Comment by LeapingSwan** [comment]
As further info I ran some more traces on Firebase and got the following info:

firebaseIsAvailable false
Firebase.FIREBASE_SDK_IOS 4.11.0
Firebase.EXTENSION_ID com.myflashlab.air.extensions.firebase.core
Firebase.IOS ios
Firebase.VERSION 6.5.0

So it looks like Firebase itself is there but not for some reason can't be initiated.

I should have said I am testing on a real device.

Thanks

Stephen

**Comment by myflashlab** [comment]
one possible issue could be that you have forgotten to add the ```GoogleService-Info.plist``` file to your project. It must be available at ```File.applicationDirectory.resolvePath("GoogleService-Info.plist").exists```

**Comment by LeapingSwan** [comment]
That fixed it thanks.

It would be great if at some point you guys could publish very brief checklists of things to check (especially if they could be linked to possible problems/ error messages).  I am sure like most developers we do work through the detailed instructions but if you make one mistake it would be great to have a quick 'Check these things if this happens' idiots guide.  Just a suggestion but it would certainly help me and perhaps save me having to ask too many questions.

Anyway thanks for the pointer.

Stephen

**Comment by myflashlab** [comment]
Will try to improve the docs, sure :) happy that it fixed the problem.
