### ISSUE TITLE
Inspector crash on start Android

### ISSUE THREAD

**Issue by Seb-AS** [myflashlab/Firebase-ANE#24]
Hi, I'm able to initialize Firebase without problems using the "if (!Inspector.check(Firebase, true, true))", but when I try to use the Inspector with Auth or DB(without works), it always crash.
I think i'm not missing any dependencies.

![anes](https://cloud.githubusercontent.com/assets/2106935/19168177/4113ed1e-8be5-11e6-9dd8-446c59860335.png)

ReferenceError: Error #1069: Property checkPlatform_Auth not found on com.myflashlab.air.extensions.inspector.Inspector
ReferenceError: Error #1069: Property checkPlatform_DB not found on com.myflashlab.air.extensions.inspector.Inspector
at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at AppEntryCommon/run()
	at global/runtime::AndroidMobileDeviceAppEntry()

**Comment by myflashlab** [comment]
Thanks for reporting this. Please update to [Inspector V1.0.5](https://github.com/myflashlab/ANE-Inspector-Tool/) and the problem is now solved.
