### ISSUE TITLE
Firebase Authentication Sample Code Causes Compiler Errors 

### ISSUE THREAD

**Issue by garymich** [myflashlab/Firebase-ANE#240]
## Environment ##
* Android API Version: 30
* iOS Version: N/A
* AIR SDK Version: 30

## Problem Description ##
I was recently able to get the Firebase core init to work and was able to validate it using the actionscript trace command. My next step was to initialize Firebase Authentication for which I used our sample code. I get 3 compilation errors. Two of them are for: Access of undefined property email and having searched your sample code and it does not contain any definition/declaration for a property or variable named email. Can I presume that I can create a variable named email and assign it an arbitrary value in order to avoid this error?

The other error is: Call to a possibly undefined method getUserInfo. Again, I have searched your sample code and there is no method of that name defined. Can I presume that I can create this methid in my code to avoid this error?

Regarding both these errors, is something missing from the sample code? Please advice at your earliest convenience.

* Copy your Actionscript code.
link to your AS3 sample code: https://github.com/myflashlab/Firebase-ANE/blob/master/AIR/src/MainAuth.as

**Comment by myflashlab** [comment]
> Access of undefined property email and having searched your sample code and it does not contain any definition/declaration for a property or variable named email.

It has, here it is: https://github.com/myflashlab/Firebase-ANE/blob/master/AIR/src/MainAuth.as#L47

> Call to a possibly undefined method getUserInfo. Again, I have searched your sample code and there is no method of that name defined.

Again, it IS! it's a function, check it out: https://github.com/myflashlab/Firebase-ANE/blob/master/AIR/src/MainAuth.as#L454-L482

**Comment by garymich** [comment]
Thank you for the prompt response and my apologies. I really don't understand how I managed to miss that.
