### ISSUE TITLE
Please update the Firebase library

### ISSUE THREAD

**Issue by leossmith** [myflashlab/Firebase-ANE#244]
It is being a while since the last update for firebase. Some bugs and fixes have been added in the native libraries both for ios and android, including the very desired

`mFirebaseAnalytics.setCurrentScreen(this, screenName, null /* class override */);` 

for analytics.

Please update the libraries to the latest version.

**Comment by myflashlab** [comment]
We are doing some final tests on the new versions of ANEs. The update development is already completed :) will start releasing them soon.
