### ISSUE TITLE
Load Jason from Firebase

### ISSUE THREAD

**Issue by heliomarch** [myflashlab/Firebase-ANE#249]
I already, copy the config files from Firebase console to the assets folder along with the SWF. Even though the App is not reading the json that Firebase provides. it picks up from another App.
I bought a new license for this new project. I do not know what it can be.

**Comment by myflashlab** [comment]
For every new project you must re-generate the firebaseCore ANE. Don’t use the old ANE from other projects.

**Comment by heliomarch** [comment]
I do not remember this step. I should generate a new core. Do I use an application that you provide correct? That's right ?

**Comment by myflashlab** [comment]
If you are a club member and you are using ANELAB, then no, just using the ANELAB software is good enough and the new firebaseCore will be generated automatically.

If you’re not using ANELAB, then look inside the zip file you downloaded when purchasing FirebaseCore. There’s an .air software. Install that on your computer and run it. That software will generate the new firebaseCore ANE with your specified config json file.

**Comment by heliomarch** [comment]
haaa I remembered I bought another license from FCM. do I have to buy another license to use the generator for another Core?

**Comment by myflashlab** [comment]
Yes you do. Read here for more details: https://www.myflashlabs.com/licensing/ thanks.

**Comment by heliomarch** [comment]
Okay, I'll make the purchase now. I'm sorry I did not remember the process, there are so many different languages ​​that we work on the same project that I miss. thankful
