### ISSUE TITLE
I can't find firebaseCore.ane

### ISSUE THREAD

**Issue by mrgoonie** [myflashlab/Firebase-ANE#25]
Hey there,

I've registered the Club & downloaded the ANEs package. Then I can't find "firebaseCore.ane", there is only "core/AneMaker-V1.2.0.air", thinking it could be the ANE generator, but it only allow me to browse "google-services.json" for Android only. 

How to create an firebase ANE for iOS?

Thanks,

**Comment by myflashlab** [comment]
The Same generated ANE will work for the iOS too. This has been written on the launching page of the software. To know how to use the software, please read the ```ANEs\firebase\core\ReadMe.txt``` file in the package you downloaded.
