### ISSUE TITLE
firebase-analytics.ane V16.0.1 Missing

### ISSUE THREAD

**Issue by leossmith** [myflashlab/Firebase-ANE#253]
This file is not in the archive with the latest update. The last version folder says 12.0.1

**Comment by myflashlab** [comment]
Could you please be more specefic? That dependency is available [here](https://github.com/myflashlab/common-dependencies-ANE/blob/master/firebase/firebase_analytics.ane) and on ANELAB channel [here](https://github.com/myflashlab/ANE-LAB/tree/master/bucket/DEPENDENCY/firebase-analytics)

**Comment by myflashlab** [comment]
Thanks for reporting that. yes, a typo and I just fixed it.
