### ISSUE TITLE
(Inspector.lastError = Firebase ANE can run on iOS SDK 7.0+) Iphone IOS 10

### ISSUE THREAD

**Issue by Seb-AS** [myflashlab/Firebase-ANE#26]
Hi,
I'm having another problem using the Firebase core, Auth & DB, Android works fine, but IOS is not working, I added the frameworks into(using latest AIR 23): /Applications/Adobe Flash Builder 4.7/eclipse/plugins/com.adobe.flash.compiler_4.7.0.349722/AIRSDK/lib/aot.

without the Inspector is showing "Config file is not found!"

any idea?

thanks
<img width="499" alt="frameworks" src="https://cloud.githubusercontent.com/assets/2106935/19204377/ede07dfa-8cb2-11e6-8470-89272268bb98.png">

   	
        <InfoAdditions><![CDATA[             
        	<key>MinimumOSVersion</key>
        	<string>7.0</string>       
            <key>UIDeviceFamily</key>
            <array>
                <string>1</string>
                <string>2</string>
            </array>            
        ]]></InfoAdditions>

**Comment by myflashlab** [comment]
We have checked the Firebase ANEs with iOS 10 And AIR 23 and there is no problem. Yet, considering that you are receiving a ```Config file is not found!``` error, it means that you have forgotten to include the [GoogleService-Info.plist](https://github.com/myflashlab/Firebase-ANE/tree/master/FD/bin) in your package. check this out: 

https://github.com/myflashlab/Firebase-ANE/wiki/A.2.-Add-Firebase-to-your-app

> If you haven't done so already, copy the final config files you downloaded from Firebase console to the bin folder of your Air project. (Notice: By the bin folder, it's meant the folder in your app where your main app .swf file is. You need to make sure these config files are available in your final .apk or .ipa builds.)

**Comment by Seb-AS** [comment]
Hi, it's working now, I forgot to add  GoogleService-Info.plist :),

But then it's showing with the inspector, if I comment out those lines of code it's working.
I'm using latest Inspector.
Thanks 
(Inspector.lastError = Firebase ANE can run on iOS SDK 7.0+)
if (!Inspector.check(Auth, true, true))
			{
				trace("Inspector.lastError = " + Inspector.lastError);
				return;
			}

**Comment by mrgoonie** [comment]
@Seb-AS I got the same error in #28 but actually if you remove the "return;" line, the code still works.

**Comment by myflashlab** [comment]
So, about the inspector tool... Although we were unable to duplicate the problem on iOS 10, it seems like we need to do some more investigations on this problem to see why that happens.

Yet, a fast workaround would be to comment out the inspector when compiling for iOS. We'll update this post as soon as we have more news about this.

**Comment by myflashlab** [comment]
Ok, good. Please update to [Inspector V1.0.7](https://github.com/myflashlab/ANE-Inspector-Tool) and this problem is now fixed. Thanks for reporting that.
