### ISSUE TITLE
AmazonIapV2Extension.ane Conflict

### ISSUE THREAD

**Issue by 42footPaul** [myflashlab/Firebase-ANE#260]
## Environment ##
* Android Version: <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="26"/>
* AIR Version: 31

## Problem Description ##
We are compiling an app for distribution on the Amazon App Store and need to include the AmazonIapV2Extension.ane in the project. 
We have purchased the Firebase Crashlytics / Core ane's and have added all the dependencies however the the packaging fails when combined with the Amazon IAP ane.
When it's removed the app compiles and packages fine.

``` error
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/gson/annotations/Expose;
        at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
        at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
        at com.android.dx.command.dexer.Main.processClass(Main.java:737)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
        at com.android.dx.command.dexer.Main.access$300(Main.java:83)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:637)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
        at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
        at com.android.dx.command.dexer.Main.run(Main.java:245)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
1 error; aborting
```

```xml
<extensions>
	<extensionID>com.amazon.device.iap.cpt.AmazonIapV2Extension</extensionID>
	<extensionID>com.speakaboos.ane.VideoANE</extensionID>
	<extensionID>com.speakaboos.ane.WebViewANE</extensionID>
	<extensionID>com.speakaboos.ane.AppboyANE</extensionID>
	<extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport.arch</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics.impl</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
	<extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
       <extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector.impl</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.measurementBase</extensionID>	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.stats</extensionID>
 <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
</extensions>
```

I'm guessing it's one of the googlePlayServices ane's. I am going to systematically remove each one by one and try to determine which one it is however they are all listed as dependencies so I'm curious if I won't be introducing the possibility of a crash somewhere by removing one.

**Comment by 42footPaul** [comment]
turns out it is the `overrideAir.ane`
Is this dependency absolutely necessary?

**Comment by myflashlab** [comment]
Yep, the overrideair ANE is needed and other ANEs won’t work without it.

However, the error message says the library “com/google/gson/” is duplicated. We have implemented that library in the overrideair ANE as it’s needed on many ANEs.

The first thing you should try is to contact the developer of that other ANE and ask them to remove that library from their package. That should be OK because the library will still be available in the overrideair.

If that’s not an option, maybe we can remove that library from overrideair ANE. But it takes some days because we are working on our next major ANE updates. So you should wait till we finish the process.

**Comment by 42footPaul** [comment]
Yep - I just confirmed that the gson library is included in the AmazonIapV2Extension.ane and was about to post my findings.

I don't think Amazon is going to be willing to remove it from their ane. 

We do roll a few of our own ane's and could possibly create our own in house amazon purchase ane but likely would not be an option due to development effort / time required.

best case for us is to have it removed from the overrideair ANE. understand it will take some time.
might work best as a dynamic dependency anyway.

I'd be happy to branch the code and do it for you :)

please let us know when that might become available.

**Comment by myflashlab** [comment]
no prob, we'll be releasing our next major ANE updates in a week or two. I marked this also and will include that in the upcoming release.

**Comment by myflashlab** [comment]
OverrideAir V5.6.1 is now released. But please note that you can't just update that one ANE. It has some other connections with other ANEs which means you need to update all your other myflashlabs ANEs also... https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir

Considering that you are using Firebase but you're not using the ANELAB software, you need to download the package again and this time install **AneMaker-V7.0.1.air** and regenerate the FirebaseCore ANE. 

**Note:** If you are using Firebase Auth or Firestore, you should be adding the [gson dependency](https://github.com/myflashlab/common-dependencies-ANE/tree/master/gson) separately as it's no longer in the OverrideAir.

**Comment by 42footPaul** [comment]
I'm having difficulty finding AneMaker-V7.0.1.air
Would you post a link?

**Comment by 42footPaul** [comment]
nevermind
