### ISSUE TITLE
The push notification's icon is displayed in white.

### ISSUE THREAD

**Issue by tamaya3146** [myflashlab/Firebase-ANE#265]
## Environment ##
* Android Version: 8.0
* AIR SDK Version: 31.0
* ANE Version: V7

I customized the push notification's icon using ANELAB 's ResourceManager,
I added The folder in firebaseMessaging.ane:
	・drawable
	・drawable-ldpi
	・drawable-mdpi
	・drawable-hdpi
	・drawable-xhdpi
	・drawable-xxhdpi
	・drawable-xxxhdpi

I am using your company's icon in the test.

But the icon is displayed in white.	

Are there other required settings?

**Comment by myflashlab** [comment]
Your Icons must be transparent. read here for more information: https://stackoverflow.com/questions/28387602/notification-bar-icon-turns-white-in-android-5-lollipop/29494245

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
