### ISSUE TITLE
Anyone have a tutorial that actually gets the FCM.ANE to actually  send a notification?

### ISSUE THREAD

**Issue by thatkidrich** [myflashlab/Firebase-ANE#267]
## Environment ##
* Android Version:
* iOS Version:
12
* AIR Version:
31

I have been trying to get this thing to work. I find their documentation and start projects out of date. 

Does anyone have success with this?

**Comment by myflashlab** [comment]
Can you tell us which part you think is out of date? Following up on wiki docs should do it.

**Comment by thatkidrich** [comment]
I think the issue is Apple doesn't make it clear all the steps that are needed. I have the ANE loading in the app. I get the config to load, everything looks like it should work, in the log, it is clearly connecting to the FCM servers, but it isn't receiving the notification on my phone. And as AIR support dwindles from these services, you guys are the only game in town. Just frustrated and need a little help.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
