### ISSUE TITLE
Companion SWC files

### ISSUE THREAD

**Issue by 42footPaul** [myflashlab/Firebase-ANE#268]
## Problem Description ##
We use Flash Builder for our development IDE however our project uses an extensive proprietary build script and so we do not use the ide project properties to import ANE's into the project.

This means that the code is not aware of the class paths.

All the ANE's we currently use (milkman games, home baked) have a companion swc file used as a bridge for import, code completion and functional access through the ExtensionContext. 

I need to find the easiest way to generate basic companion swc files for the flashlabs ane's we plan to use in the app. right now those are the Firebase Core and Crashlytics.

Any suggestions?

**Comment by myflashlab** [comment]
Contact us privately through myflashlabs.com contact form and we’ll sort this out for you. Thanks
