### ISSUE TITLE
can't generate token in Firebase messaging ANE

### ISSUE THREAD

**Issue by Gokulv617** [myflashlab/Firebase-ANE#269]
## Environment ##
* Android Version: ALL
* iOS Version:
* AIR Version: AIR 30.0

## Problem Description ##
```xml
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-sdk android:targetSdkVersion="26" />

<!-- Required by the firebase_analyticsImpl.ane & firebase-analytics.ane -->
<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE"/>

<!--
	Required by firebase_iid.ane
	Change "air.com.HFG.circlelockinghorns2" to your own app package name
-->
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
<permission android:name="air.com.HFG.circlelockinghorns2.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
<uses-permission android:name="air.com.HFG.circlelockinghorns2.permission.C2D_MESSAGE"/>

  <!-- Activate multidex for older Android support -->
            <application android:name="android.support.multidex.MultiDexApplication">
                <activity>
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN"/>
                        <category android:name="android.intent.category.LAUNCHER"/>
                    </intent-filter>
                    <intent-filter>
                        <action android:name="android.intent.action.VIEW"/>
                        <category android:name="android.intent.category.BROWSABLE"/>
                        <category android:name="android.intent.category.DEFAULT"/>
                        <!-- Change app scheme to your own pakage name -->
                        <data android:scheme="air.com.HFG.circlelockinghorns2" />
                        <!-- Required by firebaseDynamicLinks.ane -->
                        <!-- put your own website name instead of myflashlabs.com -->
				        <!--<data android:scheme="http" android:host="www.myflashlabs.com" />
				        <data android:scheme="https" android:host="www.myflashlabs.com" />-->
                    </intent-filter>
                </activity>
				
 <!-- Required by the firebase_analyticsImpl.ane & firebase-analytics.ane -->
<receiver
	android:name="com.google.android.gms.measurement.AppMeasurementReceiver"
	android:enabled="true"
	android:exported="false"/>
<service
	android:name="com.google.android.gms.measurement.AppMeasurementService"
	android:enabled="true"
	android:exported="false"/>
<service
	android:name="com.google.android.gms.measurement.AppMeasurementJobService"
	android:enabled="true"
	android:exported="false"
	android:permission="android.permission.BIND_JOB_SERVICE"/>
<receiver
	android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver"
	android:enabled="true"
	android:exported="true"
	android:permission="android.permission.INSTALL_PACKAGES">
	<intent-filter>
		<action android:name="com.android.vending.INSTALL_REFERRER"/>
	</intent-filter>
</receiver>

<!--
	Required by the firebase_common.ane
	Change "air.com.HFG.circlelockinghorns2" to your own app package name
-->
<provider
	android:name="com.google.firebase.provider.FirebaseInitProvider"
	android:authorities="air.com.HFG.circlelockinghorns2.firebaseinitprovider"
	android:exported="false"
	android:initOrder="100"/>
	
 <!-- Required by googlePlayServices_basement.ane -->
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
<!--
	Required by firebase_iid.ane
	Change "air.com.HFG.circlelockinghorns2" to your own app package name
-->
<receiver
	android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
	android:exported="true"
	android:permission="com.google.android.c2dm.permission.SEND">
	<intent-filter>
		<action android:name="com.google.android.c2dm.intent.RECEIVE"/>
		<category android:name="air.com.HFG.circlelockinghorns2"/>
	</intent-filter>
</receiver>
<service
	android:name="com.google.firebase.iid.FirebaseInstanceIdService"
	android:exported="true">
	<intent-filter android:priority="-500">
		<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
	</intent-filter>
</service>

<!-- Required by googlePlayServices_base.ane -->
<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
	android:theme="@android:style/Theme.Translucent.NoTitleBar"
	android:exported="false"/>
	
<!-- Required by firebase_messaging.ane -->
<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
	<intent-filter>
		<action android:name="com.google.firebase.MESSAGING_EVENT"/>
	</intent-filter>
</service>
<activity 
	android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
	android:theme="@style/Theme.Transparent"
	android:exported="false"
	android:noHistory="true"
	android:clearTaskOnLaunch="true"
	android:hardwareAccelerated="false"
	android:stateNotNeeded="true">
	<intent-filter>
		<action android:name="MY_INTENT" />
		<category android:name="android.intent.category.DEFAULT" />
	</intent-filter>
</activity>

<extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.arch</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics.impl</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector.impl</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.measurementBase</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.stats</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
  </extensions>

```
```actionscript
function init():void
{
	// remove this line in production build or pass null as the delegate
	//OverrideAir.enableDebugger(myDebuggerDelegate);
	
	var isConfigFound:Boolean = Firebase.init();
	
	if (isConfigFound)
	{
		var config:FirebaseConfig = Firebase.getConfig();
		trace("default_web_client_id = " + 			config.default_web_client_id);
		trace("firebase_database_url = " + 			config.firebase_database_url);
		trace("gcm_defaultSenderId = " + 			config.gcm_defaultSenderId);
		trace("google_api_key = " + 				config.google_api_key);
		trace("google_app_id = " + 					config.google_app_id);
		trace("google_crash_reporting_api_key = " + config.google_crash_reporting_api_key);
		trace("google_storage_bucket = " + 			config.google_storage_bucket);
		//trace("project_id = " + 					config.project_id);
		
		// FCM needs Google Services so, before using FCM, we need to check that first.
		// https://firebase.google.com/docs/cloud-messaging/android/client#sample-play
		if (Firebase.os == Firebase.ANDROID) Firebase.checkGoogleAvailability(onCheckResult);
		else onCheckResult(Firebase.SUCCESS);
	}
	else
	{
		trace("Config file is not found!");
	}
}

 function onCheckResult($result:int):void
{
	trace("onCheckResult");
	switch($result)
	{
		case Firebase.SUCCESS:
			
		trace("checkGoogleAvailability result = SUCCESS");
			
		// now you can use FCM
		initFCM();
			
		break;
		case Firebase.SERVICE_MISSING:
			
			trace("checkGoogleAvailability result = SERVICE_MISSING");
			
		break;
		case Firebase.SERVICE_VERSION_UPDATE_REQUIRED:
			
			trace("checkGoogleAvailability result = SERVICE_VERSION_UPDATE_REQUIRED");
			
		break;
		case Firebase.SERVICE_UPDATING:
			
			trace("checkGoogleAvailability result = SERVICE_UPDATING");
			
		break;
		case Firebase.SERVICE_DISABLED:
			
			trace("checkGoogleAvailability result = SERVICE_DISABLED");
			
		break;
		case Firebase.SERVICE_INVALID:
			
			trace("checkGoogleAvailability result = SERVICE_INVALID");
			
		break;
	}
}


function initFCM():void
{
	trace("initFCM");
	FCM.init();                //place where it gets stuck and doesn't do any action
	
	FCM.listener.addEventListener(FcmEvents.TOKEN_REFRESH, onTokenRefresh);
	FCM.listener.addEventListener(FcmEvents.MESSAGE, onMessage);
}

btn1.addEventListener(MouseEvent.CLICK, getToken);
	
function getToken(e:MouseEvent):void
{
	trace("getToken");
	FCM.getInstanceId(onTokenReceived);
}

function onTokenReceived($token:String, $error:String):void
{
	if($error)
	{
		trace("onTokenReceived error: " + $error);
		trace("onTokenReceived error: " + $error);
	}
	
	if($token)
	{
		trace("token: " + $token);
		trace("token: " + $token);
	}
}

btn2.addEventListener(MouseEvent.CLICK, subscribe);


function subscribe(e:MouseEvent):void
{
	trace("subscribe");
	// optionally you can listen to FcmEvents.ON_SUBSCRIBE to know the result
	if(!FCM.listener.hasEventListener(FcmEvents.ON_SUBSCRIBE))
		FCM.listener.addEventListener(FcmEvents.ON_SUBSCRIBE, onSubscribeResult);
	
	// It will take 24 hours before you can see this topic on the Firebase console
	FCM.subscribeToTopic("news");
}

btn3.addEventListener(MouseEvent.CLICK, unsubscribe);

function unsubscribe(e:MouseEvent):void
{
	trace("unsubscribe");
	// optionally you can listen to FcmEvents.ON_UNSUBSCRIBE to know the result
	if(!FCM.listener.hasEventListener(FcmEvents.ON_UNSUBSCRIBE))
		FCM.listener.addEventListener(FcmEvents.ON_UNSUBSCRIBE, onUnsubscribeResult);
	
	FCM.unsubscribeFromTopic("news");
}

function onSubscribeResult(e:FcmEvents):void
{
	trace("subscribe to topic " + e.topic + ": " + e.isSuccessful);
	trace("subscribe to topic " + e.topic + ": " + e.isSuccessful);
}

function onUnsubscribeResult(e:FcmEvents):void
{
	trace("unsubscribe to topic " + e.topic + ": " + e.isSuccessful);
	trace("unsubscribe to topic " + e.topic + ": " + e.isSuccessful);
}

function onTokenRefresh(e:FcmEvents):void
{
	trace("onTokenRefresh = " + e.token);
	trace("onTokenRefresh = " + e.token);
}

function onMessage(e:FcmEvents):void
{
	trace(e.msg);
	var payload:Object = FCM.parsePayloadFromString(e.msg);
	
	if (payload)
	{
		for (var name:String in payload)
		{
			trace(name + " = " + payload[name]);
		}
	}
}
```

## Steps to Reproduce ##
Normally if I run and click "get token" button nothing is displayed. Token is not generated. I bought the ANE yesterday(04/12/2018) and working it.

## Known Workarounds ##
I have added google-services.json in the apk and also pasted inside the folder.
Firebase core ANE is created with the corresponding google-services.json and air id.

**Comment by Gokulv617** [comment]
Looking for some reply soon

**Comment by Gokulv617** [comment]
@myflashlab Thanks for the reply.
![1](https://user-images.githubusercontent.com/43432782/49560438-73bc3880-f938-11e8-924b-4e067604dc61.png)


I have printed the trace commands which i got while running the APK in mobile device. Please look into this and suggest me a solution

**Comment by myflashlab** [comment]
Thanks, but these are AIR traces. you should send us AndroidStudio logs while you are calling the ```FCM.init();``` method. That should be giving us more insight of what could be going wrong.

1. install AndroidStudio IDE.
2. Create a dummy empty Android project
3. Open the logcat Window
4. Now run your AIR app while your device is connected to your computer.
5. watch out for your devices logs. You must be seeing logs from your app in the logcat window.

**Comment by Gokulv617** [comment]
okay sure i'l try that method and send you.

**Comment by Gokulv617** [comment]
@myflashlab 
Hi i successfully traced device logs in Android studio logcat. But i cant find the correct trace for my APK. Logs are running super fast. Is there a way to find the exact trace logs of my APK ?. Please suggest

**Comment by myflashlab** [comment]
Try playing with filters so the logs would show only your app package name related logs...

**Comment by Gokulv617** [comment]
@myflashlab Hi, this is the logs i'm getting in logcat(Android Studio). Please look in to this and tell me where it went wrong or where should i improvise.


**12-12 13:08:11.237 10064-10064/? I/FA: App measurement is starting up, version: 11400
12-12 13:08:11.237 10064-10064/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 13:08:11.267 10064-10064/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.eterno
12-12 13:08:13.259 10064-10154/? D/FirebaseInstanceId: topic sync succeeded
12-12 13:08:26.952 8640-8640/? D/MTPUSBConnection: onCreate in USBConnection
12-12 13:08:26.952 8640-8640/? V/MTPUSBConnection: Registering broadcast receiver.
12-12 13:08:26.962 8640-8640/? E/MTPUSBConnection: AlertDialog Mode is : TIMEOUT
12-12 13:08:31.297 8640-8640/? D/MTPUSBConnection: on destroy
12-12 13:08:37.913 10760-10775/? I/FA: Collection disabled with firebase_analytics_collection_enabled=0
12-12 13:08:37.923 10760-10775/? I/FA: App measurement is starting up, version: 12451
12-12 13:08:37.923 10760-10775/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 13:08:37.933 10760-10775/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.sec.android.app.samsungapps
12-12 13:08:42.918 10853-10853/? D/CS/ITransactionManagerService: onCreate called
12-12 13:08:42.918 10853-10853/? D/CS/ITransactionManagerService: onBind called
12-12 13:08:48.854 11101-11101/? I/FA: App measurement is starting up, version: 11400
12-12 13:08:48.854 11101-11101/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 13:08:48.984 11101-11101/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.eterno
12-12 13:09:22.587 11377-11377/? D/CS/ITransactionManagerService: onCreate called
12-12 13:09:22.587 11377-11377/? D/CS/ITransactionManagerService: onBind called
12-12 13:09:41.465 11745-11759/? I/FA: Collection disabled with firebase_analytics_collection_enabled=0
12-12 13:09:41.465 11745-11759/? I/FA: App measurement is starting up, version: 12451
12-12 13:09:41.465 11745-11759/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 13:09:41.465 11745-11759/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.sec.android.app.samsungapps
12-12 13:10:03.517 12458-12458/? D/CS/ITransactionManagerService: onCreate called
12-12 13:10:03.527 12458-12458/? D/CS/ITransactionManagerService: onBind called
12-12 13:10:35.267 12846-12860/? I/FA: Collection disabled with firebase_analytics_collection_enabled=0
12-12 13:10:35.267 12846-12860/? I/FA: App measurement is starting up, version: 12451
12-12 13:10:35.267 12846-12860/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 13:10:35.267 12846-12860/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.sec.android.app.samsungapps
12-12 13:10:45.397 13339-13339/? I/FA: App measurement is starting up, version: 11400
12-12 13:10:45.397 13339-13339/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 13:10:45.538 13339-13339/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.eterno
12-12 13:10:45.698 13294-13294/? D/CS/ITransactionManagerService: onCreate called
12-12 13:10:45.698 13294-13294/? D/CS/ITransactionManagerService: onBind called
12-12 13:10:49.571 13466-13479/? I/FA: App measurement is starting up, version: 12780
12-12 13:10:49.571 13466-13479/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 13:10:49.571 13466-13479/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app air.com.HFG.circlelockinghorns2
12-12 13:10:49.662 13466-13479/? E/FA: Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfd.zzgr(Unknown Source)
12-12 13:10:49.872 13466-13479/? I/FA: Tag Manager is not found and thus will not be used
12-12 13:10:50.993 13466-13479/? E/FA: Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfd.zzgr(Unknown Source)
12-12 13:11:01.063 13466-13479/? E/FA: Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfd.zzgr(Unknown Source)
12-12 13:11:03.785 13707-13721/? I/FA: Collection disabled with firebase_analytics_collection_enabled=0
12-12 13:11:03.795 13707-13721/? I/FA: App measurement is starting up, version: 12451
12-12 13:11:03.795 13707-13721/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 13:11:03.795 13707-13721/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.sec.android.app.samsungapps**

**Comment by myflashlab** [comment]
1. notice that ```FCM.getToken();``` is deprecated and shouldn't be used.
2. in the logs, I noticed: 
```
Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfd.zzgr(Unknown Source)
```
These classes are inside this dependency ANE: ```com.myflashlab.air.extensions.dependency.firebase.analytics.impl``` but when logcat says it's an **Unknown Source** that means it's not implemented in the project! Are you sure all the ANEs are correctly implemented in your project? to verify that, do the following:

change your final compiled .apk file name to .zip then open and look inside, look through the directories and you must be seeing all the embedded ANEs there. If something is missing, you must check and make sure your IDE has implemented them correctly.

3. When calling ```FCM.getInstanceId(onTokenReceived);```, do you experience a crash? if not, what do you receive in the callback?
```actionscript
function onTokenReceived($token:String, $error:String):void
{
	if($error)
	{
		trace("onTokenReceived error: " + $error);
	}
				
	if($token)
	{
		trace("token: " + $token);
	}
}
```

**Comment by myflashlab** [comment]
Also, when debugging your app, it's always a good idea to [activate OverrideAir debugging](https://github.com/myflashlab/common-dependencies-ANE/tree/master/overridAir#overrideairenabledebugger) for more information

**Comment by Gokulv617** [comment]
Sorry I just wanna check what is in the token. I googled it and got that keyword. I removed that now in https://github.com/myflashlab/Firebase-ANE/issues/269#issue-387749612

**Comment by Gokulv617** [comment]
@myflashlab , Thanks for the reply. I have added overrideAir debugging now and got this log in logcat. Please look in to this

**12-12 14:59:33.810 13944-13959/? I/FA: Collection disabled with firebase_analytics_collection_enabled=0
12-12 14:59:33.810 13944-13959/? I/FA: App measurement is starting up, version: 12451
12-12 14:59:33.810 13944-13959/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 14:59:33.810 13944-13959/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.sec.android.app.samsungapps
12-12 15:00:01.967 14548-14561/? I/FA: App measurement is starting up, version: 12780
12-12 15:00:01.967 14548-14561/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 15:00:01.967 14548-14561/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app air.com.HFG.circlelockinghorns2
12-12 15:00:02.007 14548-14561/? E/FA: Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfd.zzgr(Unknown Source)
12-12 15:00:02.307 14548-14561/? I/FA: Tag Manager is not found and thus will not be used
12-12 15:00:02.357 14548-14561/? E/FA: Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfd.zzgr(Unknown Source)**

**Comment by myflashlab** [comment]
The argument mismatch error! Are you using the latest version of ANEs? Not just the Firebase Core/fcm ANEs but also the dependency ANEs specially the OverrideAir ANE.

**Comment by Gokulv617** [comment]
@myflashlab ,Thanks for the reply
I'm using overrideAir v5.6.2. Got this in logcat. Please check this once

**12-12 17:48:10.349 21072-21091/? E/FA: Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfd.zzgr(Unknown Source)
12-12 17:48:18.527 21072-21091/? E/FA: Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfd.zzgr(Unknown Source)
12-12 17:48:23.362 21581-21581/? D/CS/ITransactionManagerService: onCreate called
12-12 17:48:23.362 21581-21581/? D/CS/ITransactionManagerService: onBind called
12-12 17:48:23.632 21600-21613/? I/FA: App measurement is starting up, version: 12780
12-12 17:48:23.632 21600-21613/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 17:48:23.632 21600-21613/? I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app air.com.HFG.circlelockinghorns2
12-12 17:48:23.662 21600-21613/? E/FA: Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfd.zzgr(Unknown Source)
12-12 17:48:23.923 21600-21613/? I/FA: Tag Manager is not found and thus will not be used
12-12 17:48:23.973 21600-21613/? E/FA: Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfd.zzgr(Unknown Source)**

**Comment by Gokulv617** [comment]
@myflashlab, I'm using Firebase core v7.0.1. Thank you for the help. It is working now. I'm able to send and receive notifications when outside the app.

Can you please help me send in-app message ? Your help will be greatly appreciated.

**Comment by Gokulv617** [comment]
@myflashlab , waiting for your reply

**Comment by myflashlab** [comment]
Firebase in-app messaging is not yet released. we are still developing it.
