### ISSUE TITLE
firebase messaging

### ISSUE THREAD

**Issue by artl82** [myflashlab/Firebase-ANE#27]
Hi!
Where can I find the com.myflashlab.air.extensions.firebase.fcm ane? I have added com.myflashlab.air.extensions.firebase.core ane and have inited it successfully. Now I need to implement an messages receiving logic. For doing that I cant find the com.myflashlab.air.extensions.firebase.fcm ane. If this ane is deprecated, give me the actual way. Thank you!

**Comment by myflashlab** [comment]
The FCM ANE will be released soon. We have just updated the wiki and asDoc but the ANE itself will be released in a couple of days. please check back soon. Thanks.
