### ISSUE TITLE
firebase in animate CC

### ISSUE THREAD

**Issue by BAAKILI1987** [myflashlab/Firebase-ANE#270]
I WANT BEGIN using firebase analytique and core !
but i m not a developper 
i wokr inn animate cc but i dont know how using package in classe document actionscript; i try to use it but it always defailled , it s difficult !
so is ther an other way to use code actionscript for firebase (in the first frame timeline )
thanks

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
