### ISSUE TITLE
(Auth) Error #1107: The ABC data is corrupt, attempt to read out of bounds.

### ISSUE THREAD

**Issue by mrgoonie** [myflashlab/Firebase-ANE#28]
Hi,

I met this error when I ran the application on iOS:
```
VerifyError: Error #1107: The ABC data is corrupt, attempt to read out of bounds.
	at global$init()
Cannot display source code at this location.
```

I'm not sure what did I missed. 

I already did these steps:
- Create firebaseCore.ane & included it in the FLA
- Added firebaseAuth.ane in the FLA
- Added <InfoAddition> for iPhone in "app.xml" file
- Added the "GoogleService-Info.plist" in the package.
- Added the Firebase Frameworks in the package:
![image](https://cloud.githubusercontent.com/assets/6857382/19310028/4f9c431e-90b2-11e6-90d7-f274aeea67ce.png)

The code is simple: (I already created a movieclip named "loginBtn" and put it on the stage)
```
import com.myflashlab.air.extensions.firebase.core.*;
import com.myflashlab.air.extensions.firebase.auth.*;
import flash.events.MouseEvent;

Firebase.init();

Auth.listener.addEventListener(AuthEvents.CREATE_NEW_USER_RESULT, onCreateNewUserResult);

loginBtn.addEventListener(MouseEvent.CLICK, function(e:MouseEvent){
	Auth.createUserWithEmailAndPassword("email@myflashlabs.com", "123456");
})

function onCreateNewUserResult(e:AuthEvents):void
{
    trace("onCreateNewUserResult result=" + e.result, "     msg=" + e.msg);
}
```

Hmm.. what did I missed? 😢 

Do you have any ideas?

Thanks in advanced!

**Comment by mrgoonie** [comment]
Trying to figure out... do I need to fill in this area?
![image](https://cloud.githubusercontent.com/assets/6857382/19312278/ed1b2fac-90bb-11e6-8654-9a7d904e73c8.png)

**Comment by benkhachouch** [comment]
And thé dependencies ane for Auth

**Comment by mrgoonie** [comment]
I've just copied the iOS Dependency Frameworks & paste in "AIR SDK/lib/aot/stub" already. The error message was gone, instead there are new error message from the Inspector:

`Inspector.lastError = Firebase ANE can run on iOS SDK 7.0+`

But when I checked the manifest xml and saw these lines were there:
```
<key>MinimumOSVersion</key>
<string>7.0</string>
```

What I need to do now?

**Comment by mrgoonie** [comment]
You know what, I figured it out. It's actually not a error message, just a notifications, I did put a "return" after trace that message. So when I removed it, everything works like charms.

But it took me more than an hour without any clues to make the Facebook sign-in works.

Tried: 
```
Auth.signIn(AuthProvider.FACEBOOK);
```

Didn't work! It crashed the app...  😢

**Comment by myflashlab** [comment]
To be able to sign in using an Auth provider, you need to use the ```AuthProvider``` class. take this code as an example: https://github.com/myflashlab/Firebase-ANE/blob/master/FD/src/MainAuth.as#L232-L242

```actionscript
// create a new authProvider object first
var authProvider:AuthProvider = new AuthProvider();

// decide what kind of credential this authProvider instance will hold
authProvider.setEmailAuthProvider("email@myflashlabs.com", "123456");

// and finally feed in the Auth.signIn method with the parsed credential info from the authProvider instance.
Auth.signIn(authProvider.getCredential());
```

Now, instead of using ```authProvider.setEmailAuthProvider(.......```, you should use other Auth provider, Facebook for example.

```actionscript
authProvider.setFacebookAuthProvider("facebook token id here");
```

**Comment by mrgoonie** [comment]
I thought of that too, but I got stuck when I don't know what to put in "facebook token id here".

From my understanding, I've not logged in Facebook, then how can I have the token id?

**Comment by myflashlab** [comment]
Sure, let me explain. You see, the Firebase Auth SDK is a tool to make Auth login process all working with the FIrebase servers. This means that Firebase can use different Auth providers to login your users all in Firebase so you can easily manage them in your application. But different Auth providers have their own way of validating users. It makes sense when thinking that Firebase does not have access to Facebook users database, right? So, you will need another ANE, for example http://www.myflashlabs.com/product/facebook-ane-adobe-air-native-extension/ to sign in the user first, get the required info for example the Facebook token ID, then enter it into the ```setFacebookAuthProvider``` method.

We have not yet built ANEs for other Auth providers just yet but there are other ANEs around the net which you can use for now. building GitHub/Twitter/Google sign in methods are surely in our to-do list.

I hope the information above can help you in understanding how Firebase Auth is designed.

**Comment by mrgoonie** [comment]
I see, thanks for the detailed explanation @myflashlab !

Any ideas when will the Google sign-in be ready?

**Comment by myflashlab** [comment]
We don't have a timetable for that just yet as we are currently busy on our ANE update schedule.
