### ISSUE TITLE
FirebaseCore setup problems

### ISSUE THREAD

**Issue by wooldridgetm** [myflashlab/Firebase-ANE#3]
Hey,

I'm having a problem initializing the **core Firebase extension**; it always throws a runtime error.

I have AIR 22.
I installed the Firebase SDK.
I added my AIR project to the Firebase Console w/ appID '**air.com.tomwo.PokemonNo**'
I download the '**google-services.json**' && included it in my 'bin-debug' folder right next to my SWF.
I'm on V24 of the ANE.

The problem is w/ the following line of code 

`var config:Boolean = Firebase.init();`

always throws the runtime error, "**The extension context does not have a method with the name command.**"

I successfully added the requisite ANEs to my project.
```xml
<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.firebase.auth</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.firebase.auth.common</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.firebase.auth.module</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>

 <!-- firebaseAuth.ane -->
<extensionID>com.myflashlab.air.extensions.firebase.auth</extensionID>
<extensionID>com.myflashlab.air.extensions.firebase.core</extensionID> 
```

Any idea what's going on?

I use IntelliJ.
This application compiles & runs.

Thanks for all your help.

**Comment by myflashlab** [comment]
That error means that the ANE is not embeded in your code. Are you sure you're not running on a simulator?

Besides that, the manifest settings are missing! Please check this and make sure you have added the manifest settings: https://github.com/myflashlab/Firebase-ANE/wiki/A.4.-Initialize-Firebase-in-your-app
