### ISSUE TITLE
Storage permission access error

### ISSUE THREAD

**Issue by benkhachouch** [myflashlab/Firebase-ANE#30]
i get this error
onUploadBytesFailed with errorCode '-13021' and msg: User does not have permission to access this object.

my rules in storage
service firebase.storage {
 match /b/my-assistant-1ab0f.appspot.co/o {
   
match /images/{imageId} {
  allow read,write: if resource.size < 10000 * 10240;
 
}
 }
}
Why?

**Comment by myflashlab** [comment]
Well, this question is directly related to the SDK not the ANE. You should be able to find an answer easier if you ask your question on the FIrebase [Androif](https://github.com/firebase/quickstart-android) or the [iOS](https://github.com/firebase/quickstart-ios) pages.
