### ISSUE TITLE
FCM ANE missing

### ISSUE THREAD

**Issue by replayshot** [myflashlab/Firebase-ANE#31]
Hi, 

I am trying to use your FCM ANE, but when I go to this page, it does not exist, so I cannot purchase the ANE.

thanks much,
Kenn

**Comment by myflashlab** [comment]
Thanks for your interest. The FCM ANE will be ready soon, very soon. We had sent out the beta version a week ago and we are right now fixing the final bugs. It should be ready in a couple of days.
