### ISSUE TITLE
(FCM) Not working. Where I'm doing wrong? 

### ISSUE THREAD

**Issue by flashomer** [myflashlab/Firebase-ANE#33]
Not working. Where I'm doing wrong? 
http://screencast-o-matic.com/watch/cD6T0vjGTI

**Comment by myflashlab** [comment]
In your video, everything seems normal. However, consider the following:

1. Firebase console, although sends out messages immediately, it will not show the stats fast, it usually takes 24 hours for the stats to show up.
2. Messages are being sent successfully as it seems in the video, so you are ok on the sending part.
3. Sometimes, devices are slow in being correctly propagate across Google servers. Try other devices too and see what happens.
4. When the app is in foreground, you will NOT receive a notification. the data will be received in the ```FcmEvents.MESSAGE``` as described in details [here](https://github.com/myflashlab/Firebase-ANE/wiki/G.8-Understanding-FCM-Messages). So, make sure you have put a trace on that event. Maybe you are receiving the messages but have not added the listener?

If you are sure about the above hints, also make sure you have set your manifest .xml file correctly? https://github.com/myflashlab/Firebase-ANE/wiki/G.1-Add-FCM

**Comment by flashomer** [comment]
I try the same problem in my own phone.


manifest .xml 
```
<android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>

    <!--
        Required by firebase_iid.ane
        Change "air.com.doitflash.firebaseCore" to your own app package name
    -->
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <permission android:name="air.com.doitflash.firebaseCore.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="air.com.doitflash.firebaseCore.permission.C2D_MESSAGE" />

    <application>

        <activity>
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>

        <!--
            Required by the firebase_common.ane
            Change "air.com.doitflash.firebaseCore" to your own app package name
        -->
        <provider
            android:name="com.google.firebase.provider.FirebaseInitProvider"
            android:authorities="air.com.doitflash.firebaseCore.firebaseinitprovider"
            android:exported="false"
            android:initOrder="100" />

        <!-- Required by the googlePlayServices_basement.ane -->
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <!--
            Required by firebase_iid.ane
            Change "air.com.doitflash.firebaseCore" to your own app package name
        -->
        <receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.com.doitflash.firebaseCore" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
        <service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>

        <!-- Required by googlePlayServices_base.ane -->
        <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>



		<!-- Required by firebase_messaging.ane -->
		<!-- <service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT"/>
			</intent-filter>
		</service>
		<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
			<intent-filter>
				<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
			</intent-filter>
		</service>
		<activity
			android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent"
			android:theme="@style/Theme.Transparent"
			android:exported="false"
			android:noHistory="true"
			android:clearTaskOnLaunch="true"
			android:hardwareAccelerated="false"
			android:stateNotNeeded="true">
			<intent-filter>
				<action android:name="MY_INTENT" />
				<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>-->



	</application>
</manifest>]]></manifestAdditions>
  </android>

```

**Comment by myflashlab** [comment]
Thanks for posting your AIR manifest file. There are MANY mistakes in how it is used in your project and using the current setting will surely cause problems. Please have a re-look at the comments mentioned in the manifest. One thing that you have forgotten is to replace any instance of ```air.com.doitflash.firebaseCore``` to your own package name. The other wrong thing is that you have commented the required services/activities for the FCM to work. Look under ```<!-- Required by firebase_messaging.ane -->``` those lines must NOT be commented out.

I'd say, please take your time and read the WIKI pages again. If you are trying to use FCM only in your project, First read the WIKI section where it talks about how the Firebase Core ANE must be added and initialized in your project. After successfully finishing that part, move to the FCM WIKI and start implementing it. Doing that carefully will surely solve the problem. 

Please update this ticket whenever you fixed the problem or have more questions in this regard.

**Comment by myflashlab** [comment]
I noticed that you have opened a [new issue](https://github.com/myflashlab/Firebase-ANE/issues/37) So, I am closing this one now. but please try to keep the conversation in one issue as far as the subject is related. This will help other readers find what they are searching for easier. Thanks.

**Comment by Helgiii** [comment]
I have a question: 
Change "air.com.doitflash.firebaseCore" to your own app package name
Well if my package name is ru.CompanyName.ProjectName
should the above mentioned string be replaced with
"air.ru.CompanyName.ProjectName" or
"air.ru.CompanyName.ProjectName.firebaseCore"

right now 
my app can provide a token to me (fcm) device token;
messages are sent from console, but never arrive on the device
and if i try sending a notification from my php server 
and set restricted_package_name: it says 
{"multicast_id":8509513376065392810,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidPackageName"}]}success: 1
if I remove the restricted_package_name it reports success, but still message doesnt arrive on the device

thanks.. I don't know where's the proper place to ask for help\support

**Comment by myflashlab** [comment]
```air.ru.CompanyName.ProjectName``` is correct. to test sending FCM messages, this page might be very helpful: http://www.myflashlabs.com/send-fcm-messages-server/
