### ISSUE TITLE
(FCM) always crash when received message

### ISSUE THREAD

**Issue by nxidea123** [myflashlab/Firebase-ANE#34]
We can success used FCM ANE to get device token, but android application always crash when received message, 
can anyone help?
thanks.

**Comment by myflashlab** [comment]
1) Are you sure you have set the manifet file correctly? https://github.com/myflashlab/Firebase-ANE/wiki/G.1-Add-FCM
2) Are you using the latest AIR SDK?

Send us the logs to see what error message you are receiving so we can help you further.

**Comment by myflashlab** [comment]
Please update us about this issue. Were you able to fix the problem? If any more questions, do ask.
