### ISSUE TITLE
(Auth) sendEmailVerification

### ISSUE THREAD

**Issue by mshaffer12882** [myflashlab/Firebase-ANE#35]
When does the Email and password Authentication actually email the user to confirm there email address?
I also cannot find any API for case 'verifyEmail'? and how to send the user another email if they lost or need to resend a email confirmation.

**Comment by myflashlab** [comment]
The ```sendEmailVerification``` method was not available for the Android SDK until late September but it is now added to the SDK and will be available in our next ANE release. It is already in our to-do list and you can expect that in late November.

For the "Forgotten email" thing, you may use the [sendPasswordResetEmail](https://github.com/myflashlab/Firebase-ANE/wiki/D.2-Init-Authentication#send-a-password-reset-email) method.

**Comment by myflashlab** [comment]
This method is now available in the latest version of the ANE.
