### ISSUE TITLE
(FCM) does not receive messages

### ISSUE THREAD

**Issue by artl82** [myflashlab/Firebase-ANE#36]
Hello!
I have succesfully registered and init FCM. Also I have received token. When my app is killed, I sending a message from the Firebase console to the single device by token. But on device there is no tray messages. I have attached my logcat. There I run application, then stop it, and wait for a messages. App ID com.connectivegames.androidmira 
[logcat.txt](https://github.com/myflashlab/Firebase-ANE/files/558401/logcat.txt)
![2016-10-28_1558](https://cloud.githubusercontent.com/assets/9351079/19807492/04435ce4-9d29-11e6-9262-047d56237d8a.png)

**Comment by myflashlab** [comment]
By looking at the logcat, I didn't seem to find any logs showing any incoming fcm messages. Here are som questions:

1. are you receiving fcm messages when your app is in background or foreground?
2. Are you "Fore Closing" your app to kill it? Android apps which are "Fore Closed" will not receive FCM anymore. That's typical of how Android apps work. instead, kill the app by hitting the back button or removing it from the recent running apps.
3. Is this happening on all your test devices or just a specific device? If so, please let us know what device you are testing on.
4. Please confirm that you have set the [AIR manifest](https://github.com/myflashlab/Firebase-ANE/wiki/G.1-Add-FCM) correctly?

**Comment by artl82** [comment]
1. No I don't
2. I am killing process thru Settings/applications 
3. I have 2 devices for test. Samsung GT-I9301I with Android 4.4.2 On this device I do not receive any messages when my app in background or foreground. 
4. My manifest additions:

**Comment by artl82** [comment]
My manifest additions:
<manifest android:installLocation="auto">
                
				<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="15"/>
                <uses-permission android:name="android.permission.INTERNET"/>
                <uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
                <uses-permission android:name="android.permission.WAKE_LOCK"/>
                <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
                
				
				<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
				<permission android:name="air.com.connectivegames.androidmira.permission.C2D_MESSAGE" android:protectionLevel="signature" />
				<uses-permission android:name="air.com.connectivegames.androidmira.permission.C2D_MESSAGE" />

				<application>

					<activity>
						<intent-filter>
							<action android:name="android.intent.action.MAIN" />
							<category android:name="android.intent.category.LAUNCHER" />
						</intent-filter>
						<intent-filter>
							<action android:name="android.intent.action.VIEW" />
							<category android:name="android.intent.category.BROWSABLE" />
							<category android:name="android.intent.category.DEFAULT" />
						</intent-filter>
					</activity>

					
					<provider
						android:name="com.google.firebase.provider.FirebaseInitProvider"
						android:authorities="air.com.connectivegames.androidmira.firebaseinitprovider"
						android:exported="false"
						android:initOrder="100" />

					
					<meta-data 
						android:name="com.google.android.gms.version" 
						android:value="@integer/google_play_services_version" />

					
					<receiver
						android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
						android:exported="true"
						android:permission="com.google.android.c2dm.permission.SEND" >
						<intent-filter>
							<action android:name="com.google.android.c2dm.intent.RECEIVE" />
							<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
							<category android:name="air.com.connectivegames.androidmira" />
						</intent-filter>
					</receiver>
					<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
					<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
						<intent-filter android:priority="-500">
							<action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
						</intent-filter>
					</service>

					
					<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
							  android:theme="@android:style/Theme.Translucent.NoTitleBar"
							  android:exported="false"/>
					  
					
					<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
						<intent-filter>
							<action android:name="com.google.firebase.MESSAGING_EVENT"/>
						</intent-filter>
					</service>
					<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
						<intent-filter>
							<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
						</intent-filter>
					</service>
					<activity 
						android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
						android:theme="@style/Theme.Transparent"
						android:exported="false"
						android:noHistory="true"
						android:clearTaskOnLaunch="true"
						android:hardwareAccelerated="false"
						android:stateNotNeeded="true">
						<intent-filter>
							<action android:name="MY_INTENT" />
							<category android:name="android.intent.category.DEFAULT" />
						</intent-filter>
					</activity>
					
				</application>
            </manifest>

On my second device which is Asus Nexus 7 Android 5.1.1 if I set 
<extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
I get crash after launch my app. If I commented this line 

then my app start ok.
Here is logcat from Nexus 7
[asus nexus7 crash log android 5.1.1.txt](https://github.com/myflashlab/Firebase-ANE/files/561893/asus.nexus7.crash.log.android.5.1.1.txt)

**Comment by artl82** [comment]
here is some screens 
![2016-10-31_1707_crashes_on_asus_nexus_7](https://cloud.githubusercontent.com/assets/9351079/19856924/aa9e2604-9f8c-11e6-9b82-54969057e12f.png)
![2016-10-31_1707_do_not_crashes_on_asus_nexus_7](https://cloud.githubusercontent.com/assets/9351079/19856925/aaa16d46-9f8c-11e6-8e8c-f44489905c31.png)

![2016-10-31_1709_settings](https://cloud.githubusercontent.com/assets/9351079/19856950/cd72718a-9f8c-11e6-8dc8-37ed5b9ce0b9.png)

**Comment by artl82** [comment]
One problem was solved. I have changed app id in the firebase console, now it is started with "air." and messages start coming. The second problem is still present - on Asus Nexus 7 with Android 5.1.1 my application crashes on start when I add com.myflashlab.air.extensions.firebase.fcm extension id in my manifest.

**Comment by artl82** [comment]
I have opened a new issue about crash.
