### ISSUE TITLE
(FCM) InvokeEvent arguments are empty

### ISSUE THREAD

**Issue by artl82** [myflashlab/Firebase-ANE#38]
Hi!
I have added a listener on InvokeEvent NativeApplication.nativeApplication.addEventListener(InvokeEvent.INVOKE, onInvoke);
When I click on notify message on my device, my app started but InvokeEvent arguments are empty:
![2016-11-01_1226_invoke_event_arguments_are_empty](https://cloud.githubusercontent.com/assets/9351079/19885389/59b3a842-a02f-11e6-9208-bc4f9339de51.png)
I am sending a message from the firebase console and I am adding payload to it (key1:data1)
![2016-11-01_1235_payload_message](https://cloud.githubusercontent.com/assets/9351079/19885517/0e831406-a030-11e6-9358-de399ce08f0a.png)

**Comment by benkhachouch** [comment]
I  am also interested in this issue.
Thanks.

**Comment by myflashlab** [comment]
Is this happening on iOS or Android? Which AIR SDK are you using? Are you sure you have set the manifest settings correctly?

**Comment by artl82** [comment]
This is happening on Android (4.4.2). Using 23 AIR SDK. My manifest additions:
<manifest android:installLocation="auto">
                
				<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="15"/>
                <uses-permission android:name="android.permission.INTERNET"/>
                <uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
                <uses-permission android:name="android.permission.WAKE_LOCK"/>
                <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
                
				
				<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
				<permission android:name="air.com.connectivegames.pokermira.permission.C2D_MESSAGE" android:protectionLevel="signature" />
				<uses-permission android:name="air.com.connectivegames.pokermira.permission.C2D_MESSAGE" />

				<application>

					<activity>
						<intent-filter>
							<action android:name="android.intent.action.MAIN" />
							<category android:name="android.intent.category.LAUNCHER" />
						</intent-filter>
						<intent-filter>
							<action android:name="android.intent.action.VIEW" />
							<category android:name="android.intent.category.BROWSABLE" />
							<category android:name="android.intent.category.DEFAULT" />
						</intent-filter>
					</activity>

					
					<provider
						android:name="com.google.firebase.provider.FirebaseInitProvider"
						android:authorities="air.com.connectivegames.pokermira.firebaseinitprovider"
						android:exported="false"
						android:initOrder="100" />

					
					<meta-data 
						android:name="com.google.android.gms.version" 
						android:value="@integer/google_play_services_version" />

					
					<receiver
						android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
						android:exported="true"
						android:permission="com.google.android.c2dm.permission.SEND" >
						<intent-filter>
							<action android:name="com.google.android.c2dm.intent.RECEIVE" />
							<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
							<category android:name="air.com.connectivegames.pokermira" />
						</intent-filter>
					</receiver>
					<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
					<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
						<intent-filter android:priority="-500">
							<action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
						</intent-filter>
					</service>

					
					<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
							  android:theme="@android:style/Theme.Translucent.NoTitleBar"
							  android:exported="false"/>
					  
					
					<service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
						<intent-filter>
							<action android:name="com.google.firebase.MESSAGING_EVENT"/>
						</intent-filter>
					</service>
					<service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
						<intent-filter>
							<action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
						</intent-filter>
					</service>
					<activity 
						android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
						android:theme="@style/Theme.Transparent"
						android:exported="false"
						android:noHistory="true"
						android:clearTaskOnLaunch="true"
						android:hardwareAccelerated="false"
						android:stateNotNeeded="true">
						<intent-filter>
							<action android:name="MY_INTENT" />
							<category android:name="android.intent.category.DEFAULT" />
						</intent-filter>
					</activity>
					
				</application>
            </manifest>

**Comment by piskulicivan** [comment]
Same problem here. I'm sending Data message. 
When app is in foreground i got arguments - FCM.parsePayloadFromString(e.msg).
But when I click on notification and InvokeEvent is called i **got no arguments** - FCM.parsePayloadFromArguments(event.arguments)

**Comment by benkhachouch** [comment]
have you add a schema in your manifest?

2016-11-09 20:29 GMT+01:00 piskulicivan <notifications@github.com>:

**Comment by piskulicivan** [comment]
Here is my manifest.

<android>
        <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
				<uses-permission android:name="android.permission.INTERNET" />
				<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
				<uses-permission android:name="android.permission.WAKE_LOCK"/>
				
				
				
				<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
				<permission android:name="air.com.thejoyfactory.pokebook.debug.permission.C2D_MESSAGE" android:protectionLevel="signature" />
				<uses-permission android:name="air.com.thejoyfactory.pokebook.debug.permission.C2D_MESSAGE" />
				
				
				<application>

             
					<activity>
						<intent-filter>
						<action android:name="android.intent.action.MAIN" />
						<category android:name="android.intent.category.LAUNCHER" />
						</intent-filter>
						<intent-filter>
						<action android:name="android.intent.action.VIEW" />
						<category android:name="android.intent.category.BROWSABLE" />
						<category android:name="android.intent.category.DEFAULT" />
						<data android:scheme="air.com.thejoyfactory.pokebook.debug" />
						</intent-filter>
				   </activity>
						
						
						<provider
						android:name="com.google.firebase.provider.FirebaseInitProvider"
						android:authorities="air.com.thejoyfactory.pokebook.debug.firebaseinitprovider"
						android:exported="false"
						android:initOrder="100" />
						
						
						<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
						
						
						<receiver
						android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
						android:exported="true"
						android:permission="com.google.android.c2dm.permission.SEND" >
						<intent-filter>
						<action android:name="com.google.android.c2dm.intent.RECEIVE" />
						<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
						<category android:name="air.com.thejoyfactory.pokebook.debug" />
						</intent-filter>
						</receiver>
						<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
						<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
						<intent-filter android:priority="-500">
						<action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
						</intent-filter>
						</service>
						
						
						<activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
						android:theme="@android:style/Theme.Translucent.NoTitleBar"
						android:exported="false"/>
						
						
						
						
						
		                <service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
		                    <intent-filter>
		                        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
		                    </intent-filter>
		                </service>
		                <service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
		                    <intent-filter>
		                        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
		                    </intent-filter>
		                </service>
		                <activity 
		                    android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
		                    android:theme="@style/Theme.Transparent"
		                    android:exported="false"
		                    android:noHistory="true"
		                    android:clearTaskOnLaunch="true"
		                    android:hardwareAccelerated="false"
		                    android:stateNotNeeded="true">
		                    <intent-filter>
		                        <action android:name="MY_INTENT" />
		                        <category android:name="android.intent.category.DEFAULT" />
		                    </intent-filter>
		                </activity>
						
						
						
     
            </application>
            

       			
			</manifest>
			
		]]></manifestAdditions>
    </android>
    <iPhone>
        <InfoAdditions><![CDATA[
			<key>UIDeviceFamily</key>
			<array>
				<string>1</string>
				<string>2</string>
			</array>
		]]></InfoAdditions>
        <requestedDisplayResolution>high</requestedDisplayResolution>
    </iPhone>
<extensions>
      

	    
	    
	
	    
	    
		<extensionID>com.myflashlab.air.extensions.inspector</extensionID>
		
		
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
		
		
		<extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
	
		<extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
		
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
</extensions>

**Comment by bohachu** [comment]
I have the sample problem.
Is there any solution?

**Comment by myflashlab** [comment]
To all who are experiencing this problem on Android, Please try the following steps

1. install the app on your device
2. open the list of recent apps and swipe away your app
3. send a mixed notification fcm from server
4. when the notification is received click on it to open the app
5. Are you seeing the incoming variables in the invoke event now?
6. Now swipe away your app again and send another mixed notification fcm
7. When the notification arrives, click on it to open the app, Are you seeing the data again?

Please let us know if #5 or #7 are happening? or just one of them is happening?

**Comment by bohachu** [comment]
to myflashlab,

I follow your steps and both of these two steps (5 and 7) are not happen.

**Comment by bohachu** [comment]
Dear Sir,

Is there any new update of this issue?

**Comment by bohachu** [comment]
Dear Sir,

Is there any update of this issue?

**Comment by myflashlab** [comment]
we have not been able to duplicate this problem and if we can't duplicate the problem, we won't be able to fix it :-/ However, We are right now upgrading the whole Firebase ANEs to V10.0.0 on Android and 3.10.0 on iOS. When ready, we will do more tests with FCM ANE to see if we are able to duplicate the problem or not and will send you beta versions to check on your side. so, sit tight, we're on it and we'll get back to you a.s.a.p

**Comment by myflashlab** [comment]
Alright, While upgrading the ANE to Firebase 10.0.0 we ran a detailed test on the fcm and we think we know why you are facing this problem. It turned out that it has a very simple solution.

We are not using the Firebase FCM console for sending messages because it's not mature enough and the problem that you are not receiving the data values is because of two reasons: 

1. You are using the Firebase Console. 
2. You are not setting the ```"click_action": "MY_INTENT"``` property.

When using the FCM ANE, to be able receive the key/value data in FCM Mixed Messages, you need to set the ```"click_action": "MY_INTENT"``` property in your ```notification``` node. Without that, your messages will not send the key/value to the AIR INVOKE listener. As I can see in your screenshots, you are using the Firebase Console to send messages and in that console you can't set the ```click_action```. the result is that you are not seeing the key/values.

To solve this problem, we have already wrote a very [short article here](http://www.myflashlabs.com/send-fcm-messages-server/) which teaches you how to send different types FCM messages without using the limited Firebase console. Make sure to read that blog and send FCM messages using that approach. The problem will be solved. Please test and confirm that.

**Comment by benkhachouch** [comment]
Thanks for the solution and the information.

However your tool is interesting to send a notification with data for some people. As part of a mobile application, if you want to send thousands of notifications this is not practical.

**Comment by myflashlab** [comment]
@benkhachouch As mentioned in the article, this is just a tool for you to be able to easily test the fcm messages, for complicated usecases, you should use a server to send out notifications. Unfortunately the current Firebase FCM console is very limited and you can send notification messages only. The console does not support data messages at all and sending mix messages from the console is not yet very helpful, at least for the AIR users, because from the console you can't set the ```"click_action": "MY_INTENT"``` parameter. We are positive that FIrebase team will soon upgrade their console. If we had thought that they are not going to upgrade their console, we would have started to build one ourselves but we are sure they will upgrade the console to support all different sorts of FCM messages. It will happen soon or later.

Nonetheless, using the approach we suggested in the [article](http://www.myflashlabs.com/send-fcm-messages-server/) can go very powerful if you use Firebase documentations. You can do many different things with it. We haven't tested it locally yet as the article is just an idea to get you started, but if you are posting fcm data to ```https://fcm.googleapis.com/fcm/send``` you are able to do EVERYTHING that the console does at the moment + a lot more. for example, you may send messages to group of users subscribed to a specific topic, so, you are not limited at all. Use the article idea and add your own code while posting data to Firebase fcm server endpoint. You'll be amazed on how powerful it is that I'm sure you will never again go back to the Firebase fcm console again 😄

**Comment by myflashlab** [comment]
@artl82 @piskulicivan @bohachu We would appreciate if you are testing the solution and if it is solved, we can close the ticket?

**Comment by benkhachouch** [comment]
Ok for me.The time to find my web bases.

**Comment by bohachu** [comment]
To myflashlab，

We follow your article's instruction to send mixed message from Advanced REST Client but encounter a problem.
It is okay receive mixed message when app is open and in foreground.
When app is in background or killed, it's also received the mixed message but when we click the message to open the app, the app will crash (it's shows app is stop).
So we can not confirm this method can solve the problem.

We put our test project in the url below:
https://drive.google.com/file/d/0B6ONueCRgzNTVWlaeUhlR3pNRlU/view?usp=sharing

Would you please help us to check is there anything thing we do wrong?
Thanks

**Comment by myflashlab** [comment]
NOTICE: @bohachu NEVER SHARE OUR LICENSED ANEs ON PUBLIC PAGES. THIS HAS BEEN CLEARLY EXPLAINED ON THE LICENSE FILE YOU DOWNLOADED ALONG WITH THE ANES AND ALSO ON OUR [LICENSED PAGE](http://www.myflashlabs.com/licensing/) FAMILIARIZE YOURSELF WITH THE TERMS AND CONDITIONS. YOU CAN SEND US YOUR DEMO PROJECTS BUT YOU NEVER HAVE TO INCLUDE THE ANES! WE HAVE THEM ALREADY, RIGHT?!

IF THIS HAPPENS AGAIN I WILL HAVE TO DEACTIVATE YOUR MEMBERSHIP/PRODUCT ACCESS PERMANENTLY. THANKS FOR YOUR UNDERSTANDING.

-------------------
I'm not closing the issue so we can talk on helping other to resolve the problem.

**Comment by bohachu** [comment]
to myflashlab,

We apologize to you for our carelessness and promise you that it will not happen again. 
We removed the file immediately and sorry again for any inconvenience it may cause you.

But we really need your help for this issue and will send demo project to you.

Yours sincerely,

**Comment by bohachu** [comment]
to myflashlab,

https://drive.google.com/file/d/0B6ONueCRgzNTUmpfTzUxN2dwejg/view?usp=sharing
This is new demo project download url without any anes in it.
Sorry again for any inconvenience.

Yours sincerely.

**Comment by myflashlab** [comment]
@bohachu Ok, first things first, in your manifest .xml file I noticed that you have not correctly setup the information and there's no wonder you would receive different error messages. Here's an example: Your package name is ```tw.cameo.TestFirebase``` but you have a permission like: ```<permission android:name="air.com.doitflash.firebaseCore.permission.C2D_MESSAGE" android:protectionLevel="signature" />``` which is wrong! Or you have:

```xml
<provider
	android:name="com.google.firebase.provider.FirebaseInitProvider"
	android:authorities="air.com.doitflash.firebaseCore.firebaseinitprovider"
	android:exported="false"
	android:initOrder="100" />
```
which is again wrong! In the comments on the manifest file, we have written:

```
<!-- 
	Required by the firebase_common.ane 
	Change "air.com.doitflash.firebaseCore" to your own app package name
-->
```

I would suggest that you read the wiki and documentations more carefully and it will surely solve the problem.

**Comment by myflashlab** [comment]
@bohachu And moreover, try upgrading to Firebase V2.0.0

**Comment by bohachu** [comment]
to myflashlab,

Thanks for your help!
Our problem has been solved!
Thanks again!

Yours sincerely.

**Comment by myflashlab** [comment]
Ok, good. I think others have been having a similar problem so I'm closing the ticket now. If any questions, please open a new issue.
