### ISSUE TITLE
FirebaseCore doesnt work

### ISSUE THREAD

**Issue by chemiche** [myflashlab/Firebase-ANE#4]
Hey guys,
We was not able to run our app on device after adding firebase core to the project.
After following all steps in wiki, we receive following error while packaging the app.
<img width="605" alt="screen shot 2016-08-03 at 10 21 20 pm" src="https://cloud.githubusercontent.com/assets/20822519/17376907/b066b164-59c8-11e6-857e-577217f61d8f.png">

The only included extension is FirebaseCore.ane,

**Comment by myflashlab** [comment]
Please answer the following questions:
1. What is your device iOS version?
2. What is the Air SDK version you're using?
3. Have you added the required ```***.framework``` files?

**Comment by david-daal** [comment]
Hi guys.
IOS version is 9.3.1
AIR SDK is 22.0.153
Yes all framework mentioned in guide are added:
in lib/aot/stub
FirebaseAnalytics.framework
FirebaseAuth.framework
FirebaseDatabase.framework
FirebaseInstanceID.framework
GoogleInterchangeUtilities.framework
GoogleNetworkingUtilities.framework
GoogleSymbolUtilities.framework
GoogleUtilities.framework

**Comment by chemiche** [comment]
Hi guys
IOS version is 9.3.1
Air sdk version 22.0.0.153
Yes all frameworks mentioned in guide were added.
lib/aot/stub
FirebaseAnalytics.framework
FirebaseAuth.framework
FirebaseDatabase.framework
FirebaseInstanceID.framework
GoogleInterchangeUtilities.framework
GoogleNetworkingUtilities.framework
GoogleSymbolUtilities.framework
GoogleUtilities.framework

**Comment by myflashlab** [comment]
And what iOS device model your running on?

Considering that you are running on intellij, double check if the Air SDK which you have copied the frameworks to is the one that the IDE is using to compile your project?

**Comment by david-daal** [comment]
It's iphone 5.
And yes I've double checked and Air SDK is the correct one

**Comment by myflashlab** [comment]
by having a closer look at the error message, it seems like it's not directly related to the Firebase ANEs at all... check this out, https://www.google.com/search?q=undefined+symbol&ie=utf-8&oe=utf-8#q=undefined+symbols+for+architecture+armv7+%22libruntimeinterpreter.arm-air.a%22

**Comment by chemiche** [comment]
Well this error occurs when Firebase.init() is called and doesn't when that line is commented out.
