### ISSUE TITLE
Password authentication very slow

### ISSUE THREAD

**Issue by vagrantrobbie** [myflashlab/Firebase-ANE#41]
I find sometimes authenticating using 

authProvider.setEmailAuthProvider(email, password);
Auth.signIn(authProvider.getCredential());

Can respond very slow. Between 10 seconds and a minute. This is on both Android and iOS. I am in New Zealand but this seems very long. Any thoughts on why this might be?

**Comment by myflashlab** [comment]
Hadn't heard a similar report. However, it seems like the Firebase team could be your best contact about this question. In the ANE, we are mirroring native events so if they are being received with a delay or something, you should look into the server side, i.e, asking the Firebase team directly.

https://github.com/firebase/quickstart-android  
https://github.com/firebase/quickstart-ios
