### ISSUE TITLE
(Auth) Auth.RESULT_AUTH_RECENT_LOGIN_REQUIERD - spelling

### ISSUE THREAD

**Issue by mshaffer12882** [myflashlab/Firebase-ANE#42]
Should be:
Auth.RESULT_AUTH_RECENT_LOGIN_REQUIRED

not:
Auth.RESULT_AUTH_RECENT_LOGIN_REQUIERD

**Comment by myflashlab** [comment]
Firebase V5.0.0 will have this fixed.
