### ISSUE TITLE
(Auth) Access of undefined property msg in package event.

### ISSUE THREAD

**Issue by mshaffer12882** [myflashlab/Firebase-ANE#43]
Strange problem.

if i use:
private function onCreateNewUserResult( event:AuthEvents ):void{}
I get the error:
Access of undefined property msg in package event.

if i use:
private function onCreateNewUserResult( e:AuthEvents ):void{}
It compiles no problem.  Not sure why I can't use the var event?

**Comment by myflashlab** [comment]
You probably are using the ```event``` variable somewhere else in your code which are conflicting with each other.

**Comment by mshaffer12882** [comment]
I checked last night before I posted but I will double check today and come up with a basic test project I will post.  

Matthew Shaffer 
Software Engineering & IT Services
Phone: 707.334.4434
Email: matthewshaffer@outlook.com

**Comment by mshaffer12882** [comment]
private function createUserWithEmailAndPassword( email:String, password:String ):void 
     {
            trace("createUserWithEmailAndPassword");

            Auth.init();
            Auth.listener.addEventListener( AuthEvents.CREATE_NEW_USER_RESULT,                         this.onCreateNewUserResult );
            Auth.createUserWithEmailAndPassword( email, password );
        }

        private function onCreateNewUserResult( event:AuthEvents ):void
        {
            trace("onCreateNewUserResult");
            trace( event.msg );   
        }


I can confirm that this is giving me an error.  When I change event to e or another var it compiles no problem.

**Comment by myflashlab** [comment]
We are not able to duplicate this problem. However, In your code above you have a ```private``` function inside another private function. I don't think the compiler would allow something like that.

**Comment by myflashlab** [comment]
Sorry my bad :) You don't have a private inside another one, the indents fooled my eyes!

**Comment by myflashlab** [comment]
By the second look, I think the problem is that you are referring to your ```onCreateNewUserResult``` function by calling ```this.onCreateNewUserResult```. 

I think you should remove the ```this```. because it will refer to the calling private function that is ```createUserWithEmailAndPassword```. remove the ```this``` and see how it goes.

**Comment by mshaffer12882** [comment]
Yes, my fault.  The use of the this keyword was correct.  However, the problem was I had a package named event and for some reason IntelliJ was code completing to the event var in the private function, but the Air23 compiler was looking at the event package.  Sorry for wasting your time.
