### ISSUE TITLE
( Auth ) Still logged in if disabling or deleting User?

### ISSUE THREAD

**Issue by Soshaapp** [myflashlab/Firebase-ANE#44]
If I disable or delete a User in Firebase console,  I still get a valid User i the AuthEvents.AUTH_STATE_CHANGED handler?

That should not be the case right?

/Martin

**Comment by myflashlab** [comment]
I can't remember the link but this is a bug on the Firebase side. Please follow that on Firebase github:

https://github.com/firebase/quickstart-android  
https://github.com/firebase/quickstart-ios

**Comment by Soshaapp** [comment]
Ok,  thanx :)
