### ISSUE TITLE
Adobe Air Plugin

### ISSUE THREAD

**Issue by benkhachouch** [myflashlab/Firebase-ANE#45]
hello,
I asked Google if they were not going to make an Adobe Air Firebase plugin?
****"
the answer

Hi there,

Thank you for reaching out to us. I really appreciate that you took the time to share your ideas.

We know that many developers, such as yourself, are interested in support for Adobe Air. It's something we're looking into and it's being prioritized accordingly, although I can't provide any specific details at the moment. Sorry about that. 

In the meantime, make sure to keep an eye out on our blog and release notes for information on the latest updates and features.

Best Regards,"****

Have you more news?

Thanks

Mourada

**Comment by myflashlab** [comment]
We would appreciate if you use the GitHub repository for tech questions about the ANE only. For other questions, please contact us directly through myflashlabs.com Thanks.
