### ISSUE TITLE
(DB) Duplicated TRANSACTION_PROGRESS event.

### ISSUE THREAD

**Issue by MAC-Joyco** [myflashlab/Firebase-ANE#47]
Testing transactions, I noticed a behavior that I do not know if it is normal.
When running a transaction to increment a counter (previously defined with value > 1), the TRANSACTION_PROGRESS event is called twice, the first time mutableData.value and mutableData.key are null, and the second time mutableData.value has the right value.

At the end, the operation seems to work, but in the first call to the TRANSACTION_PROGRESS event with null values in mutableData, the code call to mutableData.setValue(1) and mutableData.continueSuccess() and I do not know if that will have harmful side effects.

The code:

```
	override public function incLikesInfo(
		_listener:FirebaseEventListener,
		_requestId:int,
		_puzzle:String,
		_param:String
	):void{			
		var _uref:DBReference = DB.getReference(LIKES_PATH).child(_puzzle).child(_param);
		mRequests[_uref] = {
			requestId: _requestId,
			listener: _listener
		};
		_uref.addEventListener(DBEvents.TRANSACTION_PROGRESS, onUpdateLikesInfoProgress);
		_uref.addEventListener(DBEvents.TRANSACTION_FAILURE, onUpdateLikesInfoFailure);			
		_uref.addEventListener(DBEvents.TRANSACTION_COMPLETE, onUpdateLikesInfoSuccess);

		runTransaction(_uref, 4);
	}
		
	private function runTransaction(_uref:DBReference, _retries:int):void{
		if (!_uref.runTransaction()){
			if (_retries > 0) {
				trace("Transaction is currently busy, try again in a few seconds");
				_retries--;
				mStarling.juggler.delayCall(runTransaction, 500, _uref, _retries);
			} else {
				onUpdateLikesInfoFailureByRef(_uref);
			}
		}
	}
		
	private function onUpdateLikesInfoProgress(_e:DBEvents):void{
		trace("FirebaseSupport.onUpdateLikesInfoProgress: mutableData.key = "+_e.mutableData.key + " , mutableData.value = "+_e.mutableData.value);
				
		if (_e.mutableData.value){
			// increment the current value by one
			_e.mutableData.setValue(_e.mutableData.value + 1);
		} else {
			// if current value is not available, let's be the first one who writes it!
			_e.mutableData.setValue(1);
		}				
		_e.mutableData.continueSuccess();
	}
		
	private function onUpdateLikesInfoFailure(_e:DBEvents):void{
		onUpdateLikesInfoFailureByRef(_e.target as DBReference);
	}

	private function onUpdateLikesInfoFailureByRef(_ref:DBReference):void{
		callFirebaseListenerCancelled(getRequestInfo(_ref));

		_ref.removeEventListener(DBEvents.TRANSACTION_PROGRESS, onUpdateLikesInfoProgress);
		_ref.removeEventListener(DBEvents.TRANSACTION_FAILURE, onUpdateLikesInfoFailure);
		_ref.removeEventListener(DBEvents.TRANSACTION_COMPLETE, onUpdateLikesInfoSuccess);
	}
		
	private function onUpdateLikesInfoSuccess(_e:DBEvents):void{
		var _ref:DBReference = _e.target as DBReference;			
		callFirebaseListenerFinished(getRequestInfo(_ref));

		_ref.removeEventListener(DBEvents.TRANSACTION_PROGRESS, onUpdateLikesInfoProgress);
		_ref.removeEventListener(DBEvents.TRANSACTION_FAILURE, onUpdateLikesInfoFailure);
		_ref.removeEventListener(DBEvents.TRANSACTION_COMPLETE, onUpdateLikesInfoSuccess);
	}
```
And the console output:

> FirebaseSupport.onUpdateLikesInfoProgress: mutableData.key = null , mutableData.value = null
> FirebaseSupport.onUpdateLikesInfoProgress: mutableData.key = null , mutableData.value = 4532

It is the expected behavior?
Are the calls to mutableData.setValue(1) and mutableData.continueSuccess() in the first event call are harmless?

Thanks in advance,
Marco

**Comment by myflashlab** [comment]
Well, the mutableData.value is null if the value is not present on the server and you are the first person who is trying to write a value to it. But if I'm correct, you're saying that it always comes null the first time! I will have a closer look into this but before that Please first read this post: https://github.com/myflashlab/Firebase-ANE/issues/22#issuecomment-251149796

Secondly, tell me what happens if your server value is ```4532``` for example and you receive null for the first call and you set the value to ```1```? does the server number change to ```1```?

**Comment by MAC-Joyco** [comment]
Thanks for the reply,
Yes, mutableData.value is null the first time, although there is a value for the counter in the server. In the example I explained above that value was 4532.
Upon receiving the duplicate event, the first time mutableData.value is null, and the callback run as if it did not exist in the server, calling to mutableData.setValue(1) and mutableData.continueSuccess(), but these calls does not seem to have any effect, because shortly the event is received again with mutableData.value = 4532 and the increase is successful. Then, at the end it seems to work, but I do not know if the first event received with mutableData.value = null (having value in server) that causes calls to setValue(1) and continueSuccess(), can cause some collateral issue when running with thousands of users. And by my tests, this happens whenever a counter is incremented.

On the other hand, I have read the link you comment and my code above seems to be fine according to all that is explained there.

Regards!

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
