### ISSUE TITLE
Amazon Kindle Fire compatibility.

### ISSUE THREAD

**Issue by MAC-Joyco** [myflashlab/Firebase-ANE#48]
Is there any possibility of compatibility with Amazon Kindle Fire devices?

**Comment by myflashlab** [comment]
We haven't tested this but Firebase needs Google Play Services to be present at the device. considering that Amazon Kindle devices don't have any of Google Play Services apps, I don't think they can run Firebase at all. I'm not sure if I'm correct though. We haven't tested.
