### ISSUE TITLE
( FirebaseUser ) linkWithCredential, terminates the debug session and sends the App to background!

### ISSUE THREAD

**Issue by Soshaapp** [myflashlab/Firebase-ANE#49]
[ AIR SDK 23, ANE PACK 32, iPhone 5S ]

var email : String = "test@test.com";
var password = "123456";

var authProvider : AuthProvider = new AuthProvider();
authProvider.setEmailAuthProvider( email, password );

FirebaseUser.listener.addEventListener( FirebaseUserEvents.LINK_WITH_RESULT, linkAnonymousResult );
FirebaseUser.linkWithCredential( authProvider );

This will terminate the debug session and send the App to background!

/Martin

**Comment by myflashlab** [comment]
would you try to use the ```authProvider.getCredential()``` instead of passing the ```authProvider``` variable itself?

**Comment by Soshaapp** [comment]
Thanx Buddy, my bad :(
