### ISSUE TITLE
Offline Data persistence

### ISSUE THREAD

**Issue by Fabrice-Montfort** [myflashlab/Firebase-ANE#5]
Hi MyFlashLabs Team,

This is not really an issue, just a question.

I'm looking to enable data persistence (writing on disk). So when i launch my app without internet connection, my data are available on the device and the app can work normaly.

I've tested offline capabilities with success on your ANE. Start my app online, then switch off internet connection, perform queries (write / read / etc), then switch on internet connection and get the data synced with firebase servers. That works great.

But no luck when my app start with no internet connection... maybe I've missed something. Any tought much appreciated.

Official Firebase Doc (https://www.firebase.com/docs/ios/guide/offline-capabilities.html) did mention this : 

[Firebase defaultConfig].persistenceEnabled = YES;

Is there something similar in the ANE ?

Thanks for your answers.

Regards,

Fabrice

**Comment by myflashlab** [comment]
we do have the ```DB.persistenceEnabled = true;``` method. however, [read this](https://firebase.google.com/docs/database/android/offline-capabilities#section-offline-behavior)
it says:

> By enabling persistence, any data that we sync while online will be persisted to disk and available offline, even when we restart the app. This means our app will work as it would online using the local data stored in the cache.

Only that part of the database which has been accessed before when the app was online will be cached.

I hope this helps.

**Comment by myflashlab** [comment]
Let me know if you have more questions in regard to this ticket? Thanks.
