### ISSUE TITLE
Firebase.init() issue

### ISSUE THREAD

**Issue by veselekov** [myflashlab/Firebase-ANE#53]
Hi 

I recently updated from the beta ane to the commercial ane.

All was working fine until suddenly the Firebase.init() started returning false
At first it was manifesting as a crash on startup as I would call DB.init() and Auth.init() 
Once I removed these and traced Firebase.init() I noticed it was returning false

So I re-downloaded the plist and remade the ane and imported it and the plist into my bin dirrectory.

The ane still isn't init()

Any idea what is causing this seemingly random occurence?

Cheers

**Comment by myflashlab** [comment]
If you are testing on iOS and the ```Firebase.init()``` returns ```false``` it means that the ANE has not find your ```GoogleService-Info.plist``` in the ```File.applicationDirectory```. Make sure it is available there and it is being packaged in the final .ipa.

**Comment by veselekov** [comment]
Redownloading the .plist and putting it in the directory fixed it. I had the json in instead.
