### ISSUE TITLE
(DB) Data in order that I added

### ISSUE THREAD

**Issue by benkhachouch** [myflashlab/Firebase-ANE#54]
About firebase database ane
I do a chat in the form of a list. I wish to get the texts in the order in which I added them. But they are in a random order when I use e.dataSnapshot. 
there is not a Function as e.dataSnapshot.getChildren () ?
thanks

**Comment by benkhachouch** [comment]
there is a solution in database rules with  ".indexOn* but is more complicated.

**Comment by myflashlab** [comment]
So, you think we should close this issue? I'm not sure if you have more questions in this regard?

**Comment by benkhachouch** [comment]
Ok.thanks you
