### ISSUE TITLE
(Core) Updated to Firebase 2 but i get an error due to overrideAir

### ISSUE THREAD

**Issue by leossmith** [myflashlab/Firebase-ANE#55]
I upgraded our app to the latest Firebase, but when I try to compile, I get the following error:

Error occurred while packaging the application:

> dx tool failed:
> UNEXPECTED TOP-LEVEL EXCEPTION:
> java.lang.IllegalArgumentException: already added: Lcom/adobe/air/ActivityResultCallback;
> 
> 	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
> 	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
> 	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
> 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
> 	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
> 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
> 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
> 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
> 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
> 	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
> 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:511)
> 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:281)
> 	at com.android.dx.command.dexer.Main.run(Main.java:247)
> 	at com.android.dx.command.dexer.Main.main(Main.java:215)
> 	at com.android.dx.command.Main.main(Main.java:106)

If i remove the overrideAIR ane, it compiles without any errors, but i get an error on launching the app.
I have updated all the ANEs from firebase and common files to the latest.

**Comment by myflashlab** [comment]
overrideAir.ane is now needed and must be present when compiling your app. However, the error log says that ```com/adobe/air/ActivityResultCallback``` already added, which makes me think that you are using some other ANEs which are conflicting with this. could you confirm that? and also, would you confirm that you are using the latest AIR SDK? try AIR 24 and see if that would solve the problem?

**Comment by leossmith** [comment]
Hi,

I am using AIR 23 on my test. I also use other ANEs (the most likely to conflict is Distriqt Core). What classes are included in the overrideAIR?

**Comment by myflashlab** [comment]
try removing ANEs from other providers and see if that would fix the problem? I guess it will. And possibly, start using AIR 24. (**note:** If there's an ANE that we don't have it yet on the club package, let us know what it is and we might consider building it :)

**Comment by bingyulee** [comment]
Dear Sir,

I got the same error message.
I am using AIR 24 but the error is still exists.
And I need the other ane so I can not remove it from my project.
Is there any other way to solve this problem?
