### ISSUE TITLE
(FCM)got InternalServerError in iOS side

### ISSUE THREAD

**Issue by redsparrowWang** [myflashlab/Firebase-ANE#57]
hello, i implemented FCM1.2 to Android and ios, and worked very well. can to recevies push notification from FCM console and Advenced REST client.
but, currentlly got this error in ios side, and cann't recevice push notification. i didn't chang any setting, andorid side still work fine.
i checked FCM manual https://firebase.google.com/docs/cloud-messaging/http-server-ref?hl=en about InternalServerError, but no more helpfuly infomation, could you tell me what need to check? thanks.

**// here is Advanced REST client response info when sending push notification**
```
Response headers
Status:200: OK
Content-Type: application/json; charset=UTF-8
Date: Mon, 05 Dec 2016 10:30:03 GMT
Expires: Mon, 05 Dec 2016 10:30:03 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
Server: GSE
Alt-Svc: quic=":443"; ma=2592000; v="36,35,34"
Accept-Ranges: none
Vary: Accept-Encoding
Transfer-Encoding: chunked
```

```
{
"multicast_id": my multicast_id,
"success": 0,
"failure": 1,
"canonical_ids": 0,
"results": [
      {
        "error": "InternalServerError"
    }
],
}
```

**Comment by myflashlab** [comment]
well, ```InternalServerError``` means that something has gone wrong on the server side before even the message is received by the app/ANE. I have no idea why that is happening but you may have more luck if ask the firebase team directly.

**Comment by redsparrowWang** [comment]
thank for your response, 
i will be contact firebase team.
thanks.

**Comment by redsparrowWang** [comment]
hi, I solved it.
Finded some FCM console status info look like has exceptation at 2016-11-30~2016-12-01
https://status.firebase.google.com
I think maybe got something influence, and try to reuplod my APNs certification .p12 files to FCM console
now,ios side working again, hope this infomation can be help other people.
thanks.

**Comment by Rushang08** [comment]
Hi 
@redsparrowWang  i have re upload certification .p12 but still showing InternalServerError.

**Comment by redsparrowWang** [comment]
@Rushang08 

Hi, Rushang08

like myflashlab said:"means that something has gone wrong on the server side before even the message is received by the app/ANE."

i think i just lucky, find server error log and only reupload .p12 file solved it, but case by case, i think first you should be to check associated settings with the server on firebase console. 
app name,
app ID,
server token key,
certification file,
certification password
If possible, please re-set it again, so that more easily find the problem, i think ^_^.

If still didn't solve, should be contact firebase team will better,you know "InternalServerError " means too abstract, only firebase team self know what that specifically means, and don't be worry, them service not bad.

hope make some help,good luck.

**Comment by Rushang08** [comment]
@redsparrowWang 
Hi @redsparrowWang 
         Thanks for your reply. it solved but if i say its not related to re upload certification then its true because its firebase problem. it automatic working after 6-10 hrs.

**Comment by redsparrowWang** [comment]
@Rushang08 
solved! great, that ok,
 i said case by case, in my case i just reupload .p12 file and solved is as soon, i thank isn't timeing problem, so only firebase team self know that specifically reason.

write somthing help other people. ^_^/
