### ISSUE TITLE
(Auth) set Photo url of a user

### ISSUE THREAD

**Issue by benkhachouch** [myflashlab/Firebase-ANE#61]
How set photo url of a user.

it is read only.

Thanks

Mourada

**Comment by myflashlab** [comment]
Have you tried the [updateProfile()](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/firebase/auth/FirebaseUser.html#updateProfile()) method?

**Comment by benkhachouch** [comment]
Thanks You!
