### ISSUE TITLE
Not able to find com.myflashlab.air.extensions.firebase.fcm ane

### ISSUE THREAD

**Issue by swebert** [myflashlab/Firebase-ANE#63]
Where exactly this ane are. Please provide us. the link because I can't access initFCM() method which Adobe animate throws error
missing:
   <extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>

**Comment by myflashlab** [comment]
To be able to implement the FCM ANE, you first need to setup the Firebase Core and then add the FCM ANE found here: http://www.myflashlabs.com/product/fcm-firebase-air-native-extension/

Try reading the [Wiki](https://github.com/myflashlab/Firebase-ANE/wiki) docs for more information. Moreover, we have [sample .as usage](https://github.com/myflashlab/Firebase-ANE/tree/master/FD/src) in our repository which can help you more.

**Comment by swebert** [comment]
I have setup firebase core and its dependency. And last firebase.mesaaging.  I am getting config file from messaging and.  While importing package  import com.myflashlab.air.extensions.firebase.core.*; I am getting but not import com.myflashlab.air.extensions.firebase.fcm.*;

**Comment by swebert** [comment]
All I am saying I cannot import this classimport com.myflashlab.air.extensions.firebase.fcm.*; I have added every ane as mentioned here  https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

**Comment by myflashlab** [comment]
Would you please post your manifest .xml file? Also tell us what is your IDE. In the meanwhile, you may wish to watch [these videos](https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O) based on your IDE. You may find some helpful information in them.

**Comment by swebert** [comment]
I am using Adobe animate Cc. 
<?xml version="1.0" encoding="utf-8" standalone="no" ?>

<application xmlns="http://ns.adobe.com/air/application/20.0">
  <id>com.callystro.IndiaShelter</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel/>
  <filename>GCMExample</filename>
  <description/>
  <name>GCMExample</name>
  <copyright/>
  <initialWindow>
    <content>GCMExample.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>false</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  
  <android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.PROCESS_OUTGOING_CALLS"/>
<uses-permission android:name="android.permission.READ_CALL_LOG"/>
<uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
<uses-permission android:name="android.permission.CALL_PHONE"/>
<uses-permission android:name="android.permission.CALL_PRIVILEGED"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
<permission android:name="air.com.callystro.IndiaShelter.permission.C2D_MESSAGE" android:protectionLevel="signature" />
<uses-permission android:name="air.com.callystro.IndiaShelter.permission.C2D_MESSAGE" />
  <application>

        <activity>
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />

                
                <data android:scheme="air.com.callystro.IndiaShelter" />
            </intent-filter>
        </activity>

        
        <provider
            android:name="com.google.firebase.provider.FirebaseInitProvider"
            android:authorities="air.com.callystro.IndiaShelter.firebaseinitprovider"
            android:exported="false"
            android:initOrder="100" />

        
        <meta-data 
            android:name="com.google.android.gms.version" 
            android:value="@integer/google_play_services_version" />

        
        <receiver
            android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="air.com.callystro.IndiaShelter" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
        <service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
            <intent-filter android:priority="-500">
                <action android:name="com.google.firebase.INSTANCEID_EVENT" />
            </intent-filter>
        </service>

        
        <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                  android:theme="@android:style/Theme.Translucent.NoTitleBar"
                  android:exported="false"/>
 <service android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingService">
                    <intent-filter>
                        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
                    </intent-filter>
                </service>
                <service android:name="com.myflashlab.firebase.fcm.MyFirebaseInstanceIDService">
                    <intent-filter>
                        <action android:name="com.google.firebase.INSTANCEID_EVENT"/>
                    </intent-filter>
                </service>
                <activity 
                    android:name="com.myflashlab.firebase.fcm.MyFirebaseMessagingIntent" 
                    android:theme="@style/Theme.Transparent"
                    android:exported="false"
                    android:noHistory="true"
                    android:clearTaskOnLaunch="true"
                    android:hardwareAccelerated="false"
                    android:stateNotNeeded="true">
                    <intent-filter>
                        <action android:name="MY_INTENT" />
                        <category android:name="android.intent.category.DEFAULT" />
                    </intent-filter>
                </activity>
    </application>
			</manifest>]]></manifestAdditions>
  </android>
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.inspector</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
  </extensions>
</application>

As3 Code

import com.myflashlab.air.extensions.firebase.core.Firebase;
import com.myflashlab.air.extensions.firebase.core.FirebaseConfig;
import com.myflashlab.air.extensions.dependency.AndroidSupport;
import com.myflashlab.air.extensions.dependency.Firebase_common;
import com.myflashlab.air.extensions.dependency.Firebase_iid;
import com.myflashlab.air.extensions.dependency.Firebase_messaging;
import com.myflashlab.air.extensions.dependency.GooglePlayServices_base;
import com.myflashlab.air.extensions.dependency.GooglePlayServices_basement;
import com.myflashlab.air.extensions.dependency.GooglePlayServices_tasks;
import com.myflashlab.air.extensions.dependency.OverrideAir;
import com.myflashlab.air.extensions.dependency.AndroidSupport;
import com.myflashlab.air.extensions.firebase.*;


// initialize the Firebase as early as possible in your project
var isConfigFound:Boolean = Firebase.init();

/*

f (isConfigFound)
{
    var config:FirebaseConfig = Firebase.getConfig();
    trace("default_web_client_id = " +          config.default_web_client_id);
    trace("firebase_database_url = " +          config.firebase_database_url);
    trace("gcm_defaultSenderId = " +            config.gcm_defaultSenderId);
    trace("google_api_key = " +                 config.google_api_key);
    trace("google_app_id = " +                  config.google_app_id);
    trace("google_crash_reporting_api_key = " + config.google_crash_reporting_api_key);
    trace("google_storage_bucket = " +          config.google_storage_bucket);
}
else
{
    trace("Config file is not found!");
}



if (!Inspector.check(Firebase, true, false))
{
    // if the check method returns false, it means that the target ANE can't run
    // on this platform. in this case, you should avoid initializing the target ANE
    trace("Inspector.lastError = " + Inspector.lastError);
}


if (Firebase.os == Firebase.ANDROID) Firebase.checkGoogleAvailability(onCheckResult);
else onCheckResult(Firebase.SUCCESS);

function onCheckResult($result:int):void
{
    switch($result)
    {
        case Firebase.SUCCESS:

            trace("checkGoogleAvailability result = SUCCESS");

            // now you can use FCM
            initFCM();

        break;
        case Firebase.SERVICE_MISSING:

            trace("checkGoogleAvailability result = SERVICE_MISSING");

        break;
        case Firebase.SERVICE_VERSION_UPDATE_REQUIRED:

            trace("checkGoogleAvailability result = SERVICE_VERSION_UPDATE_REQUIRED");

        break;
        case Firebase.SERVICE_UPDATING:

            trace("checkGoogleAvailability result = SERVICE_UPDATING");

        break;
        case Firebase.SERVICE_DISABLED:

            trace("checkGoogleAvailability result = SERVICE_DISABLED");

        break;
        case Firebase.SERVICE_INVALID:

            trace("checkGoogleAvailability result = SERVICE_INVALID");

        break;
    }
}

**Comment by myflashlab** [comment]
@swebert the two links above are not opening. Anyhow, as I mentioned in my first reply, beside the Firebase Core+the dependencies, you also need to purchase the [FCM ANE](http://www.myflashlabs.com/product/fcm-firebase-air-native-extension/). You'll have the ANE after the purchase.

If you wish to have all the ANEs at once, you may consider [joining the club](http://www.myflashlabs.com/product/myflashlabs-club-membership/).
