### ISSUE TITLE
(Auth) FirebaseUser.linkWithCredential doesn't work

### ISSUE THREAD

**Issue by majidatidrai** [myflashlab/Firebase-ANE#64]
I already added this:

```
FirebaseUser.listener.addEventListener(FirebaseUserEvents.UNLINK_RESULT, onUnlink);
FirebaseUser.listener.addEventListener(FirebaseUserEvents.LINK_WITH_RESULT, onLink);
```

But after I use "FirebaseUser.linkWithCredential" with passed credential, the events seem never fired:

```
var authProvider: AuthProvider = new AuthProvider();
trace(token); // this show the facebook token already
authProvider.setFacebookAuthProvider(token);
var credential:Object = authProvider.getCredential();
FirebaseUser.linkWithCredential(credential);
```

Please check.

**Comment by myflashlab** [comment]
Note that the user should be logged in first with another method before you can use this method. And besides, this method is only available to the club members. Would you please confirm that? If so, also post your AS code here and also connect your device to AndroidStudio or xcode and send us possible error codes you might see there.

**Comment by majidatidrai** [comment]
Hey I figured it out, it's Firebase login flow, if you logged in with Google first as a primary account, then you signed out, and you can never sign in with Facebook with same email address, you have to log back in with your Google account and link it to Facebook.. hmm... I can see a discrimination here 🤓

**Comment by myflashlab** [comment]
Thanks for your finding. I'm sure others will find this information helpful.
