### ISSUE TITLE
(Core) Firebase Build Error Andriod

### ISSUE THREAD

**Issue by mindthstudio** [myflashlab/Firebase-ANE#66]
Firebase build error with Feathers 3.1.1 , Air 24.0

this my AppFCM01-app.xml [here](http://mindthztudio.com/imgs/AppFCM01-app.xml.txt)

![image](http://mindthztudio.com/imgs/error.jpg)

**Comment by myflashlab** [comment]
Do you mean that it works in a regular project without using Starling/feathers? We have users who are using Firebase with Starling with no problem.

Are you sure the dependency ANEs are all compiling in your build? and besides that, in your manifest you have used the fcm ane but you haven't added its required dependency: firebase_messaging.ane. These dependencies are explained here https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

**Comment by mindthstudio** [comment]
thanks myflashlab

: )
