### ISSUE TITLE
(Auth) unable to use firebase authorization with adobe animate pro

### ISSUE THREAD

**Issue by kglad** [myflashlab/Firebase-ANE#67]
when i try to use MainAuth (from https://github.com/myflashlab/Firebase-ANE/blob/master/FD/src/MainAuth.as) i have problems.

i do see the output from:
if (isConfigFound){
var config:FirebaseConfig = Firebase.getConfig();
				C.log("default_web_client_id = " + 				config.default_web_client_id);
				C.log("firebase_database_url = " + 				config.firebase_database_url);
				C.log("gcm_defaultSenderId = " + 				config.gcm_defaultSenderId);
				C.log("google_api_key = " + 					config.google_api_key);
				C.log("google_app_id = " + 						config.google_app_id);
				C.log("google_crash_reporting_api_key = " + 	config.google_crash_reporting_api_key);
				C.log("google_storage_bucket = " + 				config.google_storage_bucket);

and these match my firebase console settings.

but tapping the buttons results in no output to the display and tapping 'is signed in' results in:

TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.myflashlab.air.extensions.firebase.auth::Auth/updateFirebaseUserClass()
	at com.myflashlab.air.extensions.firebase.auth::Auth$/get isLoggin()

in addition, if i add:

if (!Inspector.check(Auth, true, true))
			{
				trace("Inspector.lastError = " + Inspector.lastError);
				return;
			}

to initFirebaseAuth(), upon startup i see:

ReferenceError: Error #1065: Variable Firebase is not defined.
	at global/flash.utils::getDefinitionByName()
	at com.myflashlab.air.extensions.inspector::Inspector$/check()
	at com.kglad::Main_Test_Auth/initFirebaseAuth()[F:\_Jobs\Matt_Trainer\Starling_HelloWorld\final_files\com\kglad\Main_Test_Auth.as:195]
	at com.kglad::Main_Test_Auth/init()[F:\_Jobs\Matt_Trainer\Starling_HelloWorld\final_files\com\kglad\Main_Test_Auth.as:161]
	at com.kglad::Main_Test_Auth()[F:\_Jobs\Matt_Trainer\Starling_HelloWorld\final_files\com\kglad\Main_Test_Auth.as:93]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at AppEntryCommon/run()
	at global/runtime::AndroidMobileDeviceAppEntry()
Cannot display source code at this location.

can you determine what i'm doing wrong from this info?

**Comment by myflashlab** [comment]
1. Are you sure you are using the latest version of the Inspector ANE?
2. Whenever you receive an error message like ```Cannot access a property or method of a null object reference```, it means that some ANEs have not been correctly embedded in your project. Make sure they are available in your build. [These videos might help](https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O).

**Comment by kglad** [comment]
thank you for the response.  i really appreciate it.


1.  i'm using version 2.0.0 of ANE-inspector (per the changelog.txt in the inspector MyFlashClub\anes\ANE-Inspector-Tool-master\ChangeLog.txt).  also the changelog.txt in the directory where i extracted MyFlashLabClub_ANEs_packageV34.zip shows:


MyFlashLabs ANE Club

*Nov 27, 2016 - Package #34*
* Updated Firebase collection to V2.0.0


all my ane's show last modified date as 11/28, except ANE-inspector (11/27) (and, of course, firebaseCore).



2.  i've checked my dependencies and as best i can tell all the needed ane's are embedded.  here's the relevant part of my descriptor.xml


  <android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.c2dm.permission.RECEIVE"/>
<uses-permission android:name="android.permission.rmission.C2D_MESSAGE"/>
</manifest>]]></manifestAdditions>
  </android>


  <extensions>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.realtimeDB</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.database</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.database.connection</extensionID>
    <extensionID>com.myflashlab.air.extensions.inspector</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.crash</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.crash</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics.impl</extensionID>
  </extensions>
</application>


thank you,

keith gladstien


________________________________

**Comment by kglad** [comment]
also, a possible clue:

when i debug on my nexus 7, i see this in the debug stack:

![screenshot - 12_21_2016 9_52_57 am](https://cloud.githubusercontent.com/assets/24682078/21400113/611f259c-c763-11e6-8961-7b16423d5d56.png)

**Comment by kglad** [comment]
after check dependencies more carefully, i see this at https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

![screenshot - 12_21_2016 10_36_06 am](https://cloud.githubusercontent.com/assets/24682078/21401740/3fd8ae9c-c76a-11e6-8f18-c915894d9c4f.png)

but i see no firebase_authCommon.ane and no firebase_authModule.ane in MyFlashLabClub_ANEs_packageV34.zip

i found MyFlashClub\anes\common-dependencies-ane-master\firebase\firebase_common.ane which is close but nothing with module in the name.

**Comment by kglad** [comment]
i found those ane's but i had to look through google's archived pages and adding them caused bigger problems, so i don't think that's a good idea.  they are older (9/16) ane's and i'm pretty sure mixing them with newer (11/16) ane's is a bad idea.

![screenshot - 12_21_2016 11_16_17 am](https://cloud.githubusercontent.com/assets/24682078/21402819/16945612-c76f-11e6-9c1d-67e61cd42ba1.png)

**Comment by myflashlab** [comment]
The latest version of the [inspector tool](https://github.com/myflashlab/ANE-Inspector-Tool#changelog) is V1.0.14. Make sure you are using that because this version works with Firebase V2.0.0.

If you are calling the following and the debugger halts on the first line, it means that the inspector ANE itself is not even embedded into the project. Are you seeing the ```trace``` output in your console?
```actionscript
if (!Inspector.check(Auth, true, true))
{
	trace("Inspector.lastError = " + Inspector.lastError);
	return;
}
```

Can you create a simple demo project and send it to us so we can run your test app here and find the problem in your setup? (do not include any of the licensed ANEs).

**Comment by kglad** [comment]
you were correct.

1)  my inspector tool was not up-to-date and
2)  i had a descriptor file problem.

thank you very much for all your help.  this issue is closed.

**Comment by kglad** [comment]
thank you.


those problems were solved with the latest ane and correcting my descriptor.xml.


now i'm trying to figure out how to read the firebase database data.  i can't see a way to enumerate over the keys/values of a DBReference or DBQuery.  how do you do that?


kg




________________________________
