### ISSUE TITLE
(FCM) Firebase.checkGoogleAvailability never returning

### ISSUE THREAD

**Issue by glennbull** [myflashlab/Firebase-ANE#68]
I'm just setting up Firebase FMC for the first time.  I have setup Firebase core without problems using the samples provided on this site, but as I'm trying to setup the FMC side I've found that using the sample code is not working.  I call the SetupFCM function after Firebase has been initialized successfully.  In my output I see the 'in here' phrase appear, but then never see the 'result checked' phrase called.  What possible reasons could there be that the checkGoogleAvailability function does not return?  I'm testing on a Nexus 6P with nougat.  Here's the code I refer to above.  Inspector also runs succesfully and I (believe) I have all the required additions for the core firebase ANEs and the FMC ane in place.
```actionscript
function SetupFCM() : void {
	if (Firebase.os == Firebase.ANDROID) {
		trace('in here');
		Firebase.checkGoogleAvailability( onCheckResult );
	} else {
		trace('in here 2');
		onCheckResult(Firebase.SUCCESS);
	}
}

function onCheckResult ($result : int) : void {
	trace('result checked');
}
```

**Comment by myflashlab** [comment]
Try connecting your device to your pc while watching the AndroidStudio logcat and see what it outputs when ```Firebase.checkGoogleAvailability( onCheckResult );``` is called?

**Comment by myflashlab** [comment]
This issue has not been answered for a long time so I am closing it now but if you have more information to be added, please let us know to reopen it. Thanks.
