### ISSUE TITLE
ld: framework not found FirebaseAnalytics

### ISSUE THREAD

**Issue by ringodotnl** [myflashlab/Firebase-ANE#69]
Trying to add admob this is the error on IOS build. Android build no issues.
error: ld: framework not found FirebaseAnalytics

**Comment by ringodotnl** [comment]
Ah seems you have to copy all inside:
Firebase\Analytics to YOUR SDK]/lib/aot/stub

**Comment by brian-studioRouleau** [comment]
Thanks friend!
