### ISSUE TITLE
"framework not found GoogleIphoneUtilities"

### ISSUE THREAD

**Issue by veselekov** [myflashlab/Firebase-ANE#70]
On compile for iOS I get the error "framework not found GoogleIphoneUtilities"
Is this missing from the dependencies or am I doing something wrong.

**Comment by veselekov** [comment]
My new motto for developing with firebase
"Before you do anything. Update your fucking ANE's!"
Fixed when I updated to 2.0

**Comment by myflashlab** [comment]
correct. This has been mentioned in the changelogs https://github.com/myflashlab/Firebase-ANE#changelog
