### ISSUE TITLE
[FCM] iOS not receiving push notifications

### ISSUE THREAD

**Issue by veselekov** [myflashlab/Firebase-ANE#71]
Hi,

I've updated all of my ANE's and have recieved my token using this code to get it on my computer fast
```
function saveTxtFile(inputTxt: String, OUTPUT_FILE_NAME: String): void {
	var file: File = new File();
	file = File.documentsDirectory.resolvePath(OUTPUT_FILE_NAME + ".txt");
        var stream: FileStream = new FileStream();
	stream.open(file, FileMode.WRITE);
	stream.writeUTFBytes(inputTxt);
	stream.close();
}
```

Once I've sent the message it says it was sent on Firebase. However it isn't coming through on the ios side. Is this an ANE issue or a iOS/Apple Developer issue

Cheers

**Comment by veselekov** [comment]
The issue was that you are required to enter the FCM Tab under project settings in the Firebase Console. Might wanna add that to the instructions guys had me puzzled for a long time.

**Comment by myflashlab** [comment]
@veselekov could you send a screenshot from where you say FCM tab under project settings? This is how we see the Firebase console. The **Notifications** item on the left.
![capture](https://cloud.githubusercontent.com/assets/1692948/21633322/52cc8e02-d263-11e6-82b9-17513e4525db.PNG)
