### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by benkhachouch** [myflashlab/Firebase-ANE#72]
Hello. 

I am impatient.
 What new about fcm and dynamics links?
Difficult to make applications completed in the state.

Regards.

**Comment by myflashlab** [comment]
FCM has been ready for a while now you can use it right now! And DynamicLinks is ready for Android and we are working on the iOS side... You'll be updated soon.

**Comment by benkhachouch** [comment]
Hello

FCM
what news about:
Send Multiple Messages
Send to Device Groups
Send Upstream Message

the wiki is empty about that.

Regards

2017-01-08 11:40 GMT+01:00 MyFlashLabs <notifications@github.com>:
