### ISSUE TITLE
Storage ANE JSON Error

### ISSUE THREAD

**Issue by jasonJamEther** [myflashlab/Firebase-ANE#73]
I am getting an error when trying to upload a bytearray to storage using:

finalBitmapData = myBitmap.bitmapData; (my bitmap is on screen so I know it is not empty)
var encoder:JPGEncoder = new JPGEncoder(80);
var imageByteArray:ByteArray = encoder.encode(finalBitmapData);

var storageRef:StorageReference = Storage.getReference();
var profileRef:StorageReference = storageRef.child("profiles/" + FirebaseUser.userId + ".jpg");
var task:UploadTask = profileRef.putBytes(imageByteArray);

The error I am getting is:
 SyntaxError: Error #1132: Invalid JSON parse input.
	at Error$/throwError()
	at JSON$/parse()
	at com.myflashlab.air.extensions.firebase.storage::StorageReference/putBytes()

It appears to be a bug as this is the same bytearray I was uploading to parse.com. If it is not a bug can you let me know what I am doing wrong? Air for Android 23.  I have the latest myflashlabs firebase builds and dependency files as of 2 weeks ago.

**Comment by jasonJamEther** [comment]
Any word on this?

**Comment by jasonJamEther** [comment]
Can I please get some feedback on this?

**Comment by myflashlab** [comment]
Would you let us know if you are experiencing this problem on Android only? or is it happening on iOS also?

**Comment by jasonJamEther** [comment]
My app is only an Android app so I can't test for ios.

**Comment by myflashlab** [comment]
well, we created the very exact same thing and it's working fine both on Android and iOS! Will you be able to create a FlashDevelop Sample project (Without including the licensed ANEs of course.) and send it to us so we can duplicate the problem?

hint: Are you sure your ```FirebaseUser.userId``` is returning a correct string?

**Comment by jasonJamEther** [comment]
What library are you using to generate your bytearray? I am using JPGEncoder from the as3corelib.

**Comment by myflashlab** [comment]
Yes, we are also using ```com.adobe.images.JPGEncoder```

**Comment by jasonJamEther** [comment]
Ok I figured out what I was missing. I hadn't included one of the dependencies. At a glance I thought that
com.myflashlab.air.extensions.dependency.firebase.storage    was the same as com.myflashlab.air.extensions.firebase.storage .  Adding the missing ane corrected the issue. Thank you for your support in this.
