### ISSUE TITLE
(FCM)set custom push notification icon

### ISSUE THREAD

**Issue by stolons** [myflashlab/Firebase-ANE#76]
I want to set custom push notification icon on iOS and Android (not application default icon, i want to set other PNG image)
try to set "icon" as notification parameter when send notification, but didn't work.
could i confirm that firebase message ane possable support custom push notification icon ?, and how did i need to do, thanks.

**Comment by myflashlab** [comment]
custom icons can be set using the [ane resource manager tool](https://github.com/myflashlab/Resource-Manager-AIR). We will be adding the instructor soon. Please hang on.

**Comment by JamesSmith2** [comment]
Can you give us the default labels for icons?

**Comment by stolons** [comment]
is this question for me ? 
what do you want to do when you got my icon?

**Comment by JamesSmith2** [comment]
Hi,

No its for MyFlashLabs, i want to change icons, but don't know default file labels for it.

**Comment by redsparrowWang** [comment]
Hi,JamesSmith2
 read this will be help you [http://www.myflashlabs.com/send-fcm-messages-server/]

 `{
  "notification": 
  {
    "title": "Title",
    "text": "Your Text",
`
it will be set your notification title and sub text look like labels for icons, hope can be help :P
this issues for custom icon and we waiting for myflashlab response. him said ”Please hang on.”

**Comment by JamesSmith2** [comment]
So when sending: "title": "test" the icon will be test.png ?

**Comment by redsparrowWang** [comment]
JamesSmith2：So when sending: "title": "test" the icon will be test.png ?

no, not this mean, default notification icon is your app icon, and it sould be set in app's setting file. 
and we just want to chang notification icon to other icon ,not change app icon.
Android can be use android system icon by set icon code, but it's impossable in iOS side. 

so, in this case we just want to change notification icon, not system icon, not app icon, set other icon

i see you question just want to change icon's label? is't? ,so just set title or text will be done.

**Comment by myflashlab** [comment]
Ok, First make sure you have updated yourself with Firebase ANEs V4.0.0 then read this article: http://www.myflashlabs.com/custom-icon-sound-fcm-air-native-extension/

If you have more questions, do ask.

**Comment by redsparrowWang** [comment]
got it and it's working fine, Thanks :-D

**Comment by myflashlab** [comment]
@stolons @JamesSmith2 Should we close the ticket?

**Comment by JamesSmith2** [comment]
All good from here.

**Comment by redsparrowWang** [comment]
hi my flashlab.
ane resource manager tool. feature very well and can be meets our needs, thanks 

could i extension to another question?

when got a notification, want to show a icon(A) in OS status bar,
when drop down the OS status bar , want to show other icon(B) at notification menu
status bar icon and menu icon are different icon, is't impossible?

**Comment by myflashlab** [comment]
@redsparrowWang Nope, this functionality is not yet available on Firebase. not for now at least.

**Comment by maheenkhalid** [comment]
Hey @myflashlab My application does not show any icon when I recieve the notification when app is in background. I have read that it should show the default icon of the app. But for me it is a plain white square. Am I missing anything?

**Comment by myflashlab** [comment]
If I'm correct, you're talking about the Android FCM part and how it tints the icon. Well, making the notification look white tint is how Android doing it since Android 5! read the following for more information:
https://developer.android.com/about/versions/android-5.0-changes.html  
https://material.io/guidelines/style/icons.html#icons-product-icons  

If you want your notification icon to be more recognizable on Android, you can use a different icon than your application main icon. To do this, this post will help you: http://www.myflashlabs.com/custom-icon-sound-fcm-air-native-extension/

**Comment by redsparrowWang** [comment]
@myflashlab  got it, thanks for your response :-)
