### ISSUE TITLE
(FCM) Is there any way to set custom push notification sound?

### ISSUE THREAD

**Issue by bingyulee** [myflashlab/Firebase-ANE#77]
We want to custom the notification sound. We follow https://api.playfab.com/docs/push-for-android this article set the custom sound and place the sound file in res/raw folder but fail. Is there any way to set custom push notification sound?

**Comment by myflashlab** [comment]
To support custom icons and sounds for FCM ANE we have started a revolutionary workaround called the "" we are working on the ANEs to soon add the required wiki/docs for you to know how to do such custom things in ANEs (Not just Firebase ANEs) Please wait till we finish our development tasks on this regard.

**Comment by JamesSmith2** [comment]
Can you give us the default labels for icons ?

**Comment by bingyulee** [comment]
Dear Sir,

Is there any new progress on this workaround?

**Comment by myflashlab** [comment]
Unfortunately custom sounds are not working on the Android side (They work on the iOS side). And it seems like this is a bug from Adobe's side. We are investigating this problem and will update this ticket when we have the final answer. However, you can have custom icons for your notifications on the Android side if you put your custom icons inside the ```drawable``` resource folder using the [Resource Manager Tool](http://www.myflashlabs.com/adobe-air-native-extension-resources-project/)

**Note:** Custom icons are not supported by Firebase on iOS devices.

**Comment by myflashlab** [comment]
You will find this article very helpful: http://www.myflashlabs.com/custom-icon-sound-fcm-air-native-extension/
