### ISSUE TITLE
Firebase INIT

### ISSUE THREAD

**Issue by joyola** [myflashlab/Firebase-ANE#79]
**My code**

```
public class firebase extends Sprite {
		public function firebase() {
			var isConfigFound:Boolean = Firebase.init();
			if (isConfigFound)
			{
			    var config:FirebaseConfig = Firebase.getConfig();
			    trace("default_web_client_id = " +          config.default_web_client_id);
			    trace("firebase_database_url = " +          config.firebase_database_url);
			    trace("gcm_defaultSenderId = " +            config.gcm_defaultSenderId);
			    trace("google_api_key = " +                 config.google_api_key);
			    trace("google_app_id = " +                  config.google_app_id);
			    trace("google_crash_reporting_api_key = " + config.google_crash_reporting_api_key);
			    trace("google_storage_bucket = " +          config.google_storage_bucket);
			
				DB.init();
			}
		}
```

**Error**

> Using Apache Flex SDK 4.13 Debugger Adapter (Worker support).
> [Info] Listening to port 7935.
> [Info] Connection as server to player via 7935 established.
> Exception fault: ArgumentError: Error #3500: The extension context does not have a method with the name command.
> 	at flash.external::ExtensionContext/_call()
> 	at flash.external::ExtensionContext/call()
> 	at com.myflashlab.air.extensions.firebase.core::Firebase$/init()
> 	at com.powerflasher.SampleApp::firefaba()[/Users/joyola/Documents/workspace/firefaba++/src/com/powerflasher/SampleApp/firefaba.as:12]
> 	at runtime::ContentPlayer/loadInitialContent()
> 	at runtime::ContentPlayer/playRawContent()
> 	at runtime::ContentPlayer/playContent()
> 	at runtime::AppRunner/run()
> 	at ADLAppEntry/run()
> 	at global/runtime::ADLEntry()
> [Loading] Loaded: firefaba++.swf

**Configuration**

![screen shot 2017-01-27 at 11 49 07](https://cloud.githubusercontent.com/assets/4267418/22374988/1bbf812c-e487-11e6-819b-17c78ca8df82.png)

![screen shot 2017-01-27 at 11 54 18](https://cloud.githubusercontent.com/assets/4267418/22375067/5f040516-e487-11e6-8e87-4c78f7889993.png)

I HAVE THE SAME ERROR IN FLASH BUILDER

What is the problem?

**Comment by joyola** [comment]
Also I have reviewed:

Inspector.check(Firebase, true, false) == TRUE

Inspector.check(Firebase, true, true) == TRUE

**Comment by myflashlab** [comment]
> The extension context does not have a method with the name command.

@joyola This error means that the ANE has not been correctly implemented in your project. Are you sure you have ready the wiki pages completely? Moreover, you may find watching these videos helpful: https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by joyola** [comment]
Hi.

Imposible setup Firebase in FDT ide.

Anyway I have setup Firebase in Flash Builder.  It works fantastic only in debug mode.

**Run mode:**
![screenshot_2017-02-28-10-02-30](https://cloud.githubusercontent.com/assets/4267418/23406367/63576cdc-fd9d-11e6-8dfe-c9aa9ac4fbd4.png)

**Debug Mode:**
![screenshot_2017-02-28-10-04-00](https://cloud.githubusercontent.com/assets/4267418/23406368/635824ce-fd9d-11e6-8a13-7a912c029dc3.png)

Environment: Apache Flex 4.15 FP20.0 AIR20.0 -swf-version=31 (flash builder 4.7)

I am testing the demo application available in GitHub. But I have the same problem in my application.

Any idea???

**Comment by myflashlab** [comment]
Use the [Inspector tool](https://github.com/myflashlab/ANE-Inspector-Tool) to see if you have correctly embedded the dependencies? That might be the problem you have on the FDT side.

About FB, you should note that FlashBuilder is changing your package name when you build for debug or release. Make sure that is not happening. We have explained this issue on this video: https://www.youtube.com/watch?v=Z7K3QDUUEf0&index=2&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

And by the way, V4.0.0 of Firebase collection is now released. Make sure you are updating your dependency files based on what is described in this page: https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

**Comment by myflashlab** [comment]
Please let us know if you have more questions in this regard?
