### ISSUE TITLE
(Auth) signInAnonymously()

### ISSUE THREAD

**Issue by benkhachouch** [myflashlab/Firebase-ANE#8]
hello,

can we use signInAnonymously()
it seems no active?

thanks

**Comment by myflashlab** [comment]
This feature is not yet completed. There are a lot of work to be done and we are on it...

**Comment by GV3** [comment]
Hi @myflashlab,

one short recommendation :)

I've noticed that you are closing all issues when you answer, and although I know you guys are right, and there're tons of things to be done, it might make more sense to keep the issues OPEN and tag them or assign them a milestone.

That way is easier for the community to follow what's happening, to vote on open issues, to prioritize and to have an idea of when will what be happening.

I'll give you the example of @joshtynjala (FeathersUI) a great AS3 coder who manages the issues as described above:

https://github.com/BowlerHatLLC/feathers/issues?utf8=%E2%9C%93&q=is%3Aopen

This would be really useful, please consider it :)

Thanks and keep up the great work!

**Comment by myflashlab** [comment]
Noted and will do. Thanks. As soon as our current to-do list is finished, we will go through the old issues and mark them appropriately.

**Comment by myflashlab** [comment]
This feature is now added to the upcoming release. As soon as V1.2.0 is released, you can sign in users anonymously by passing ```null``` to the ```signIn()``` method.

**Comment by benkhachouch** [comment]
Super!!

2016-09-25 10:30 GMT+02:00 MyFlashLabs <notifications@github.com>:
