### ISSUE TITLE
Google Play Services and Android Support

### ISSUE THREAD

**Issue by sfxworks** [myflashlab/Firebase-ANE#80]
aaaaaaaanyway at all I can get this working with Distriqt's NativeMaps? I like both of your projects. I tried dissecting them [using this guide](http://blogs.adobe.com/airodynamics/2014/06/13/using-multiple-anes-having-common-jars-as-packageddependency/) and made some progress, but I got lost and stumbled upon a new error that probably was caused by me deleting the wrong things.

You are both great. But each of you has resources that the other does not..

**Comment by myflashlab** [comment]
We hear you @sfxworks And we are working with full power to make the MyFLashLabs Club package as complete as possible. We will soon have all the ANEs that the AIR community would need so there will be no conflict problem in future. :)
