### ISSUE TITLE
Slow app startup with Analytics

### ISSUE THREAD

**Issue by chichilatte** [myflashlab/Firebase-ANE#81]
Hi, we installed Firebase Core & Analytics into our AIR Android project and it more than doubled our app startup time from ~3.5secs to ~9secs on a range of fairly average devices. After running a few *really* simple tests it looks like it's caused by a combination of...

* The 12 ANEs it takes to get Firebase Analytics working 
* A large resources folder (28MB, 4000 files)

I also ran tests with a large resources folder + couple of other ANEs (GoViral and SystemProperties) instead of Firebase, and startup times were fine.

Really need a fix for this! Thanks.

**Comment by myflashlab** [comment]
@chichilatte These things can only be fixed by Adobe SDK compiler. To get Firebase to work, you will need all these dependencies. However, if you were using our ANEs last year, you would had seen that we used to combine all dependency ANEs into one ANE but we changed that behavior to improve the performance. Right now, our ANEs are loading ONLY the necessary dependencies and if you are using Firebase core+Analytics, then you need to load the dependencies and they are all the minimal requirements.

> A large resources folder (28MB, 4000 files)

What do you mean by "large resource" folder? you don't need to include any resource folders for the core+analytics.

**Comment by chichilatte** [comment]
Hi there, thanks for getting back. Just to be clear: it's all working, our events are being tracked in Firebase, it's just causing very slow startup. I've only included the 12 ANE files needed for Core and Analytics (following your instructions carefully)...

* androidSupport.ane
* firebase_analyticsImpl.ane
* firebase_common.ane
* firebase_iid.ane
* firebase-analytics.ane
* firebaseAnalytics.ane
* firebaseCore.ane
* googlePlayServices_appinvite.ane
* googlePlayServices_base.ane
* googlePlayServices_basement.ane
* googlePlayServices_tasks.ane
* overrideAir.ane

The resources folder is our folder, needed for our app. Nothing to do with Firebase. But when we package an apk which includes a big folder and the 12 Firebase ANEs the app is extremely slow to startup.  I did a few tests but the important ones were...

* a blank AIR app with Firebase ANEs
* a blank AIR app with a large resources folder
* a blank AIR app with Firebase ANEs *and* a large resources folder

It was only the last one that was very slow to start up.

**Comment by chichilatte** [comment]
Basically what I'm asking is: is there something unusual that the Firebase ANEs are doing, or is this just what AIR does when there are 12 ANEs + large resources?

**Comment by myflashlab** [comment]
hmm, We really don't know/ I think the Firebase team or the AIR team should be answering this question. What we have done is to make the Firebase SDK available on the AIR platform and we have absolutely no idea on what they are doing deep inside :) Maybe Firebase SDK is looking into your resource folder and does some optimization required for its analytics but this is ONLY a wild guess. You should ask them. Thanks for sharing it with us though. 

Moreover, if you ever received an answer from them about this, we'd be super happy if you share it with us also. That would be interesting to know why your resource folder + Firebase makes the startup take longer!
