### ISSUE TITLE
Null data save error on Firebase Database

### ISSUE THREAD

**Issue by tfnsyl** [myflashlab/Firebase-ANE#82]
Hi, I have a problem on DBReference.setValue method. 

If data has a null value inside, the program doesn't proceed to **SET_VALUE_SUCCESS** or **SET_VALUE_FAILURE** listeners.

As the code below, the `onDataSuccess` and `onDataError` never shows up.

> var data:Object = {key1:"val1",key2:null} 
> 
> var ref:DBReference = DB.getReference(tableName);
> var currentData:DBReference = ref.child(referenceID);
> 
> currentData.addEventListener(DBEvents.SET_VALUE_SUCCESS, onDataSuccess);
> currentData.addEventListener(DBEvents.SET_VALUE_FAILURE, onDataError);
> 
> currentData.setValue(data);
> 
> function onDataSuccess(e:DBEvents):void
> {
> 	trace("onDataSuccess");
> }
> 
> 
> function onDataError(e:DBEvents):void
> {
> 	trace("onDataError: " + e.msg);
> }

I have also updated Firebase ANE to the latest version and problem continues. 

The only solution I found is to convert data by `JSON.stringify(data)`, replacing null values to something like `""` and to parse it again. But this may be so expensive in some situations. 

Is this related to Firebase SDK or may it be from ANE?

**Comment by myflashlab** [comment]
For deleting data from the server side, you should pass ```""``` to ```updateChildren()``` or call ```removeValue()```

Read more about this here    
https://github.com/myflashlab/Firebase-ANE/wiki/B.4-Save-Data#delete-data

However, updating the ```setValue``` method is also in our to-do list. so the setValue method can also accept ```""``` to remove a value.

Let me know if you have more question.

**Comment by myflashlab** [comment]
The ```setValue``` is now updated and you can set values to null directly by passing an empty String to a value. We will close this ticket as soon as we release the new version of the ANEs.

**Comment by myflashlab** [comment]
Update to V4.0.0 This issue must have been fixed now.
