### ISSUE TITLE
(Auth) FirebaseUser.isEmailVerified will not update after FirebaseUser.reload() has been run

### ISSUE THREAD

**Issue by mshaffer12882** [myflashlab/Firebase-ANE#84]
When I run FirebaseUser.reload() it does not update the FirebaseUser.isEmailVerified var.

I tested to make sure FirebaseUser.reload() was working by running FirebaseUser.updateEmail and then checking to see if the users email address was updated and it was.  So it seems isolated to the isEmailVerified var.  Please look into this.  

Thanks!

**Comment by myflashlab** [comment]
Thanks fro the detailed information. We will look into this and see what we can find.

**Comment by myflashlab** [comment]
@mshaffer12882 This issue has been addressed in our upcoming release of Firebase ANE V4.0.0 When V4 is out (hopefully this week), please test it and see if everything works as expected or not. Thanks.

**Comment by yehyatt** [comment]
You should refresh the user object after verification as follows :

```
usertask = mAuth.getCurrentUser().reload();
usertask.addOnSuccessListener(new OnSuccessListener() {
@override
public void onSuccess(Void aVoid) {
user = mAuth.getCurrentUser();
boolean useremailveri = user.isEmailVerified();
String useremailuid = user.getUid();
}
});
```
