### ISSUE TITLE
Core gives classNotFoundException

### ISSUE THREAD

**Issue by JamesSmith2** [myflashlab/Firebase-ANE#85]
I have double checked all .xml manifests and the code debugged step by setup, the error appears when Firebase.Init() is called. When running in Debug mode the error does not appear. Only when just running apk on phone.

`java.lang.ClassNotFoundException: Didn't find class "com.adobe.air.AndroidActivityWrapper$ActivityResultCallback"`

**Comment by myflashlab** [comment]
You need to run the Android side in a captive mode. Firebase ANEs can't run on shared AIR runtimes. They need the captive mode.

**Comment by myflashlab** [comment]
So, is the problem fixed or you have more question?

**Comment by JamesSmith2** [comment]
Hi,
Sorry for late response, yes problem is fixed, Intellij idea didn't run it correctly. Thank you.
