### ISSUE TITLE
(DL) dynamics links and google play

### ISSUE THREAD

**Issue by benkhachouch** [myflashlab/Firebase-ANE#86]
Is it necessary to publish the application on google play to create dynamic links for test ?

Thanks.

**Comment by myflashlab** [comment]
No it's not. You can test dynamic links without uploading to the stores. 

**NOTE:** On the iOS side, you will need the appStore ID. Which you can trick it by sending another appStore ID while you are still testing your app. However, to avoid extra confusion, it's good have the apps already uploaded and ready on the stores.
