### ISSUE TITLE
(FCM) FCM$/getToken()

### ISSUE THREAD

**Issue by MyMyGames** [myflashlab/Firebase-ANE#88]
```

trace("token = " + FCM.getToken());

```

Main errorID: 1009 name: TypeError message: Error #1009: Cannot access a property or method of a null object reference.  StackTrace: TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.myflashlab.air.extensions.firebase.fcm::FCM$/getToken()
	at com.filler::GameAnd/initFCM()[C:\_WorkDir\RainbowProjects\src\com\filler\GameAnd.as:193]
	at com.filler::GameAnd/onCheckResult()[C:\_WorkDir\RainbowProjects\src\com\filler\GameAnd.as:150]
	at Function/http://adobe.com/AS3/2006/builtin::call()
	at com.myflashlab.air.extensions.firebase.core::Firebase/onStatus()

**Comment by MyMyGames** [comment]
```
FCM.listener.addEventListener(FcmEvents.MESSAGE, onMessage);
```

Main errorID: 1009 name: TypeError message: Error #1009: at com.myflashlab.air.extensions.firebase.fcm::FCM$/get listener()

**Comment by MyMyGames** [comment]
In tutorial "Initialize Firebase FCM" not present function initFCM

```
        case Firebase.SUCCESS:

            trace("checkGoogleAvailability result = SUCCESS");

            // now you can use FCM
            initFCM();

        break;
```

ADD TO WIKI:
```
private function initFCM():void
{
	FCM.init();
///....
}
```

**Comment by myflashlab** [comment]
Maybe we should make it a bit bolder, thanks. But it's there in the wiki:

> After you made sure that Google Services are available, simply call FCM.init(); and the FCM service will start in your app. As soon as this method is called for the first time on the iOS side, a dialog will be presented to you asking for user permissions to send push notifications.
