### ISSUE TITLE
missing dependencies when integrating Firebase-AUTH / CORE

### ISSUE THREAD

**Issue by syberkitten** [myflashlab/Firebase-ANE#89]
Trying to integrate firebase-auth, I've followed the instructions (https://github.com/myflashlab/Firebase-ANE/wiki/A.4.-Initialize-Firebase-in-your-app)

and added both ANE's (firebaseAuth.ane and firebaseCore.ane) 

yet the compiler complains not having the following deps:        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
   <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.auth</extensionID>

**Comment by syberkitten** [comment]
should these dependencies be part of the core.ane ?
I'm targeting -swf-version=35
and using air SDK 25, with IntelliJ 14.

**Comment by myflashlab** [comment]
yes, of course you should add the dependencies also. For each Firebase ANE that you use, you can know what dependencies it relies on by studying this page: https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md

**Comment by syberkitten** [comment]
You closed the issue, but I'm using the Core.ANE
I asked since i was assuming it to work.

I'm using the version found in:
MyFlashLabClub_ANEs_packageV36

being a kickstarter supporter -)

**Comment by syberkitten** [comment]
Ok, Got all the dependency ANE's from the commons repository, but compiler claims them to be missing, here is my app manifest.xml,
can you point to  what can be misplaced, does the order play part?

`
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>


        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>

        

        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.auth</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.auth</extensionID>
`

**Comment by syberkitten** [comment]
Should I be adding the .swc files?

**Comment by syberkitten** [comment]
Ok, after few hours of struggle managed to get it working.
Had to re-create a new core ANE using the ANE-Maker, and app compiles -))

Cheers
