### ISSUE TITLE
(FCM new feature) vote for sending upstream message

### ISSUE THREAD

**Issue by jimmymjing** [myflashlab/Firebase-ANE#92]
Hello, I'm trying to implement live chat in the game and I find using fcm with xmpp protocol is probably the right way to get it done. As currently sending upstream message is not available in FCM ane, please vote or leave a comment if any of you also have a desire for such a feature. Thanks so much!

**Comment by benkhachouch** [comment]
I agréé. I vote for this

**Comment by tfnsyl** [comment]
i vote for that feature, too.

**Comment by 22Round** [comment]
+1

**Comment by Soshaapp** [comment]
Firebase just added Cloud Functions!

https://firebase.google.com/features/functions/

That should be the best solution for Notifications being triggered by DB  :)

**Comment by benkhachouch** [comment]
commented less than a minute ago
<https://github.com/myflashlab/Firebase-ANE/issues/96#issuecomment-285932164>

If I understood the firebase google exemples correctly, we only need token
made by fcm ane?

Thanks

**Comment by benkhachouch** [comment]
After having long waited, too much waited, I switched to onesignal ane by Marpies which allows to send notifications from the mobile.
https://github.com/marpies/onesignal-ane

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
