### ISSUE TITLE
App crashing after getting back from background

### ISSUE THREAD

**Issue by tzenkner** [myflashlab/Firebase-ANE#93]
Hi, im using firebase analytics, crashlog and storage at the moment. Everything works fine but when im getting the app back in the foreground it is crashing with following stack trace (received in firebase console):

Exception java.lang.IllegalArgumentException:
com.adobe.fre.FREContext.dispatchStatusEventAsync (FREContext.java)
com.myflashlab.firebase.core.AirCommand.onConnected (AirCommand.java:327)
com.google.android.gms.common.internal.zzm.zzq ()
com.google.android.gms.internal.zzaal.zzo ()
com.google.android.gms.internal.zzaaj.zzvE ()
com.google.android.gms.internal.zzaaj.onConnected ()
com.google.android.gms.internal.zzaan.onConnected ()
com.google.android.gms.internal.zzzy.onConnected ()
com.google.android.gms.common.internal.zzl$1.onConnected ()
com.google.android.gms.common.internal.zzf$zzj.zzwZ ()
com.google.android.gms.common.internal.zzf$zza.zzc ()
com.google.android.gms.common.internal.zzf$zza.zzu ()
com.google.android.gms.common.internal.zzf$zze.zzxa ()
com.google.android.gms.common.internal.zzf$zzd.handleMessage ()
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:241)
android.app.ActivityThread.main (ActivityThread.java:6217)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:865)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:755)

Do you know about this issue?

Currently im using Air sdk 24 and 25 beta, crashing on both. The device is running with android sdk 24 and android 7

Cheers

**Comment by myflashlab** [comment]
Try updating to Firebase V4.0.0 and see if that happens again? And also tell us if you are seeing this problem on only one device? or that is happening on other devices you are testing?

**Comment by tzenkner** [comment]
I did the update and also added the newest common dependencies, also tried on a different device but still the same:


com.adobe.fre.FREContext.dispatchStatusEventAsync (FREContext.java)
com.myflashlab.firebase.core.AirCommand.onConnected (AirCommand.java:359)
com.google.android.gms.common.internal.zzm.zzq ()
com.google.android.gms.internal.zzaat.zzo ()
com.google.android.gms.internal.zzaar.zzwi ()
com.google.android.gms.internal.zzaar.onConnected ()
com.google.android.gms.internal.zzaav.onConnected ()
com.google.android.gms.internal.zzaag.onConnected ()
com.google.android.gms.common.internal.zzl$1.onConnected ()
com.google.android.gms.common.internal.zzf$zzj.zzxG ()
com.google.android.gms.common.internal.zzf$zza.zzb ()
com.google.android.gms.common.internal.zzf$zza.zzu ()
com.google.android.gms.common.internal.zzf$zze.zzxH ()
com.google.android.gms.common.internal.zzf$zzd.handleMessage ()
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5525)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:730)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:620)

Air sdk 24 device has android sdk 23, android 6.0

im targeting this:
<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="24"/>

**Comment by tzenkner** [comment]
I used the override air debug method, traces after waking up are like this:

[trace] ------------------
[trace] $ane = FirebaseCore
[trace] $class = AirCommand
[trace] $msg = connectToGoogleApi > Connecting to google API
[trace] ------------------
[trace] ------------------
[trace] $ane = FirebaseCore
[trace] $class = AirCommand
[trace] $msg = connectToGoogleApi > Creating a new Google API client
[trace] ------------------
[trace] ------------------
[trace] $ane = FirebaseCore
[trace] $class = AirCommand
[trace] $msg = connectToGoogleApi > Created a new Google API client
[trace] ------------------
[trace] ------------------
[trace] $ane = FirebaseCore
[trace] $class = AirCommand
[trace] $msg = connectToGoogleApi > called GOOGLE_API_CLIENT.connect()
[trace] ------------------
[trace] ------------------
[trace] $ane = FirebaseCore
[trace] $class = AirCommand
[trace] $msg = connectToGoogleApi > Connecting to google API
[trace] ------------------

then it exits

**Comment by myflashlab** [comment]
Ok, it seems like for some reason the ANE is getting disposed when you are leaving the app. That's why when you return to your app, it cannot dispatch the results back to the AIR side. Please check and make sure that you are not disposing the Firebase ANEs when closing your app...

**Comment by tzenkner** [comment]
I have no idea why this is effecting the stuff on reactivate the app, but yout inspector ane caused the issue.
When i remove the following block it's working correctly:

if (!Inspector.check(FirebaseAnalytics, true, true)) {
	trace("Inspector.lastError = " + Inspector.lastError);
}

Now after bringing it back to foreground i get the traces like above but with success at the end:
------------------
[trace] $ane = FirebaseCore
[trace] $class = AirCommand
[trace] $msg = onConnected > GOOGLE_API_CONNECTION_SUCCESS
[trace] ------------------

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
