### ISSUE TITLE
(Auth) V4.0 Question

### ISSUE THREAD

**Issue by mshaffer12882** [myflashlab/Firebase-ANE#94]
First, thanks for V4.0 very excited to try out all the new features!

But, I have a question.  I see that Auth now has verifyPasswordResetCode($code:String):void
however, I do not see a method to  send the user a reset code.  Maybe I'm missing something?

**Comment by myflashlab** [comment]
This documentation should give you the answer: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/firebase/auth/Auth.html#checkActionCode()

This code will have been generated by [sendPasswordResetEmail](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/firebase/auth/Auth.html#sendPasswordResetEmail()) or [sendEmailVerification](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/firebase/auth/FirebaseUser.html#sendEmailVerification())

**Comment by mshaffer12882** [comment]
Sorry, I'm still confused.  Both sendPasswordResetEmail() and sendEmailVerification() methods seem to only send an email with a link.  Isn't verifyPasswordResetCode($code:String):void support to verify a code that was sent to the users email address?

Thanks for you time and help!

**Comment by myflashlab** [comment]
hmm, ok, check [this link](http://stackoverflow.com/questions/37490586/firebase-how-to-generate-confirmation-code) it's talking about JS but should be the same for Android/iOS.

**Comment by mshaffer12882** [comment]
Thanks!  I understand how it works now.  Seems the work flow could be better on the firebase side.  Like having a method to send the code or a link.  Thanks again for your time it is greatly appreciated!
