### ISSUE TITLE
Android 6.0 Intent cancelled when app killed

### ISSUE THREAD

**Issue by JamesSmith2** [myflashlab/Firebase-ANE#95]
Hi,

Nexus 5X with Android version 7 works fine when app killed, but with 6.0 i can't receive any notifications when app force closed on background. When i leave it on background everything works fine.
Using latest V4.0 core files.

Log:
`03-10 12:20:59.861 28056-10266/? I/SendBroadcastPermission: action:com.google.android.c2dm.intent.RECEIVE, mPermissionType:0
03-10 12:20:59.861 28056-10266/? I/SendBroadcastPermission: action:com.google.android.c2dm.intent.RECEIVE, mPermissionType:0
03-10 12:20:59.863 28056-28056/? W/GCM-DMM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=air.com.xxx.app (has extras) }`

**Comment by myflashlab** [comment]
Notice that Force Closing an app on Android means that the user does not want to hear anymore about the app. For the notifications to work, your app must be in foreground/background/closed programmatically. ```NativeApplication.nativeApplication.exit();```

**Comment by myflashlab** [comment]
Let us know if you have more questions on this regard?
