### ISSUE TITLE
(FCM) Public XMPP server

### ISSUE THREAD

**Issue by benkhachouch** [myflashlab/Firebase-ANE#96]
FCM Upstream needs a Public XMPP server or are there other solutions?
where find free servers?

**Comment by Soshaapp** [comment]
Have you seen the new [https://firebase.google.com/features/functions/](Cloud Functions for Firebase?)

Now we don't need our own servers anymore! :)

**Comment by Soshaapp** [comment]
Have you seen the new Cloud Functions for Firebase?

 https://firebase.google.com/features/functions/

Now we don't need our own servers anymore! :)

**Comment by benkhachouch** [comment]
C'est de la bombe!

**Comment by benkhachouch** [comment]
If I understood the firebase  google exemples correctly, we only need token made by fcm ane?

**Comment by benkhachouch** [comment]
If I understood the firebase  google exemples correctly, we only need token made by fcm ane?

**Comment by benkhachouch** [comment]
If I understood the firebase google exemples correctly, we only need token made by fcm ane?or by third party?
