### ISSUE TITLE
(Help) Update to v4.0.0

### ISSUE THREAD

**Issue by mrgoonie** [myflashlab/Firebase-ANE#97]
Hello there,

I got some troubles after updating Firebase ANE to version 4.0.0 as below screenshot:

![image](https://cloud.githubusercontent.com/assets/6857382/24198023/a73f455a-0f36-11e7-85d3-0cca43c93254.png)

I have no clues to fix it so far, please give me a hand !

Detail:
```
Error occurred while packaging the application:


Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MyFlashLabsClass", referenced from:
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.auth.a(exFirebaseAuth.o)
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.analytics.a(exFirebaseAnalytics.o)
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.analytics.a(BaseClassFirebaseAnalytics.o)
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.realtimeDB.a(BaseClassFirebaseDB.o)
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.realtimeDB.a(exFirebaseDB.o)
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.core.a(exFirebaseCore.o)
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.storage.a(exFirebaseStorage.o)
      ...
  "_OBJC_CLASS_$_GTMOAuth2Authentication", referenced from:
      objc-class-ref in GoogleSignIn(GIDSignIn_e54dfbe83cb15a7fcc18625d90569ccb.o)
      objc-class-ref in GoogleSignIn(GIDAuthentication_fe6e375386112a406f3d37478fe557b3.o)
  "_OBJC_CLASS_$_GTMOAuth2SignIn", referenced from:
      objc-class-ref in GoogleSignIn(GIDSignIn_e54dfbe83cb15a7fcc18625d90569ccb.o)
      objc-class-ref in GoogleSignIn(GIDAuthentication_fe6e375386112a406f3d37478fe557b3.o)
  "_OBJC_CLASS_$_GTMOAuth2Keychain", referenced from:
      objc-class-ref in GoogleSignIn(GIDSignIn_e54dfbe83cb15a7fcc18625d90569ccb.o)
  "_OBJC_CLASS_$_GTMOAuth2ViewControllerTouch", referenced from:
      objc-class-ref in GoogleSignIn(GIDSignIn_e54dfbe83cb15a7fcc18625d90569ccb.o)
ld: symbol(s) not found for architecture arm64

```

Thank you !

**Comment by mrgoonie** [comment]
To add in, I'm using AIR SDK 25 and built for iOS. 

Not sure if this error is some conflicted error or missing ANE error...

**Comment by mrgoonie** [comment]
Anyway, the dependency integration guide seems to have some mistakes, it shouldn't be "firebaseCore.ane" for each of those, should it?

Screenshot: http://imgur.com/a/gUBi5

**Comment by mrgoonie** [comment]
Solved. For who got the same issue, you might want to start copying those framework files to the fresh air sdk, don't replace/merge with the current one.

**Comment by syberkitten** [comment]
@mrgoonie having the same issue, can you please explain that do you mean:
"start copying those framework files to the fresh air sdk" ?

1. what is a fresh air sdk?
2. what files are you referring to, the ios library files? 
"FirebaseAnalytics.framework
FirebaseCore.framework
FirebaseInstanceID.framework
GoogleToolboxForMac.framework"
3. What is the difference between replacing and copying fresh?
(replacing is making a new copy, there should be no difference)

Thanks... :)

**Comment by syberkitten** [comment]
I've opened a new issue here:
https://github.com/myflashlab/Firebase-ANE/issues/110

**Comment by mrgoonie** [comment]
My advise is: 
1. Delete your current AIR SDK folder.
2. Download the new one on http://www.adobe.com/devnet/air/air-sdk-download.html
3. Copy those dependency frameworks (*.framework) into "AIR SDK/lib/aot/stub/"
4. Retry on building your app.

What is the difference between replacing and copying fresh? 
-> Good question. I think the reason is when you do replace , some old files are still there, and they cause conflicting with the new files.

**Comment by myflashlab** [comment]
Although what @mrgoonie suggests works but you really don't have to delete the AIR SDK altogether. instead, delete all the Firebase .framework files you had there before and copy the new ones there.

And again, @mrgoonie is right when he says not to replace the frameworks. you should delete the old ones first because some files inside the old frameworks may still exist if you replace them and they might throw some linking problems.

And for the ANE dependencies, always try to make sure you are using the latest versions.

**Comment by mrgoonie** [comment]
Yea, but you don't always remember all old Firebase *.framework files to delete, there is a lot of files, so the fastest way is.. delete all of them! 😆

**Comment by syberkitten** [comment]
Thanks for the notes, I've done so already,
but will give another go with a more "sterile" approach
just to make sure... will update 👍
