### ISSUE TITLE
Remote Config update issue

### ISSUE THREAD

**Issue by Selonie** [myflashlab/Firebase-ANE#98]
When updating to the latest firebaseRemoteConfig.ane taken from MyFlashLabClub_ANEs_packageV37.zip. I get the exception
PRO = false
PRO_MSG = "Grrr! This feature is only available to MyFlashLabs Club members. If you haven't checked out our Club yet, it's time to do so. read here: http://www.myflashlabs.com/product/myflashlabs-club-membership/"
Am I missing something - as Grrr! I am a member
I've updated the dependencies and Core, firebase.init has been called - The gameServices.ane from the same package has updated and is working as expected, my progress has stopped here.
Building for Android, Air 24.
Help would be appreciated
Thanks

**Comment by myflashlab** [comment]
you're right, we have made a mistake! we will fix this soon in the next coming update. if you are in a hurry though, send us an email through myflashlabs contact page and we'll send you the correct .ane quickly. sorry for the inconvenient. Some times a simple task of copying a file can be mistaken.
