### ISSUE TITLE
Could not build ipa

### ISSUE THREAD

**Issue by babakasol** [myflashlab/Firebase-ANE#99]
Hi,
I am using firebase messaging ANE in my project, but while building i get an error 

**Error occurred while packaging the application:
Id: framework not found FirebaseMessaging**

I have included the framework and dependencies still unable to resolve the issue.
Please help!

**Comment by myflashlab** [comment]
This Error means that you are missing ```FirebaseMessaging.framework```
Read this documentation very carefully: https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md It's very easy to miss some frameworks.

NOTICE: When you are updating your frameworks, NEVER overwrite them. Instead delete the old ones first and then copy the new ones in to your AIR-SDK/lib/aot folder.

**Comment by babakasol** [comment]
Thank you for the reply...

I was missing on some frameworks, but the issue remains the same.

"I am using FCM v3.0.0 and FirebaseCore v4.0.0, can that be a issue?"

**Comment by myflashlab** [comment]
Of course that could be a problem! please refer to the dependencies file linked above and make sure you are using the correct ANEs with each other.

**Comment by babakasol** [comment]
now i am using the correct frameworks and v4.0.0 ANEs as per to the dependencies file linked above still i get the same "missing framewoks issue" ?

Please help!

**Comment by myflashlab** [comment]
Please post over your manifest .xml file so we can have a look at it here...

**Comment by babakasol** [comment]
framework issue is resolved but now getting this error

Error occurred while packaging the application:

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MyFlashLabsClass", referenced from:
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.fcm.a(exFirebaseFcm.o)
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.fcm.a(BaseClassFirebaseFcm.o)
      objc-class-ref in libcom.myflashlab.air.extensions.firebase.core.a(exFirebaseCore.o)
ld: symbol(s) not found for architecture armv7

any idea what i am missing now.

**Comment by myflashlab** [comment]
> Undefined symbols for architecture armv7:
"OBJC_CLASS$_MyFlashLabsClass", referenced from:

This means that you are not using the latest OverrideAIR dependency ANE. I would suggest you to read this page more carefully: https://github.com/myflashlab/Firebase-ANE/blob/master/Dependencies.md it will tell you what dependencies are needed and what version of them.

**Comment by babakasol** [comment]
Thank you guys issue resolved...
